// @generated by tools/protocol-codegen/generate.mjs from protocol/gateway/v2/manifest.json and protocol/gateway/v2/schema.json.
// DO NOT EDIT MANUALLY.

use serde::{Deserialize, Serialize};
use std::io::{BufRead, Write};
use std::future::Future;
use std::pin::Pin;

pub use codepet_core_sdk::{ClientId, Cursor, DeviceDescriptor, DeviceId, EventCursor, NativeResourceId, PageInfo, ProtocolError, ProtocolVersion, ProviderInstanceId, ProviderPluginId, RequestId, RoutedResourceId, RpcError, TimestampMs, VersionRange};

pub const PROTOCOL_VERSION: ProtocolVersion = 2;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct Approval {
    pub resource: RoutedResourceId,
    pub conversation: RoutedResourceId,
    pub turn: RoutedResourceId,
    pub kind: String,
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub status: ApprovalStatus,
    pub decisions: Vec<ApprovalDecision>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub requested_at: Option<TimestampMs>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resolved_at: Option<TimestampMs>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<ApprovalDecision>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ApprovalDecision {
    #[serde(rename = "approve")]
    Approve,
    #[serde(rename = "deny")]
    Deny,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ApprovalRequestedEvent {
    pub approval: Approval,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ApprovalResolveRequest {
    pub approval: RoutedResourceId,
    pub decision: ApprovalDecision,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ApprovalResolveResponse {
    pub approval: Approval,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ApprovalResolvedEvent {
    pub approval: Approval,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ApprovalStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "denied")]
    Denied,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ChoiceOption {
    pub id: String,
    pub display_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disabled_reason: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ChoiceSet {
    pub options: Vec<ChoiceOption>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_id: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct Conversation {
    pub resource: RoutedResourceId,
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preview: Option<String>,
    pub status: ConversationStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub permission_level: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_effort: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub selection: Option<TurnSelection>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workspace_root: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<TimestampMs>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<TimestampMs>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active_turn: Option<TurnTask>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationAcquireInteractionRequest {
    pub conversation: RoutedResourceId,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationAcquireInteractionResponse {
    pub selection: TurnSelection,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lease_expires_at: Option<TimestampMs>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationContent {
    pub content_id: NativeResourceId,
    pub kind: ConversationContentKind,
    pub text: String,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConversationContentKind {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "reasoning-summary")]
    ReasoningSummary,
    #[serde(rename = "command")]
    Command,
    #[serde(rename = "output")]
    Output,
    #[serde(rename = "activity-summary")]
    ActivitySummary,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationCreateRequest {
    pub route: GatewayProviderRoute,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    pub permission_level: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_effort: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workspace_root: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationCreateResponse {
    pub conversation: Conversation,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationGetRequest {
    pub conversation: RoutedResourceId,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationGetResponse {
    pub conversation: Conversation,
    pub items: Vec<ConversationItem>,
    pub snapshot_cursor: EventCursor,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationItem {
    pub resource: RoutedResourceId,
    pub turn: RoutedResourceId,
    pub conversation: RoutedResourceId,
    pub kind: ConversationItemKind,
    pub status: ConversationItemStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub role: Option<ConversationItemRole>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    pub contents: Vec<ConversationContent>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub related_item: Option<RoutedResourceId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub approval: Option<Approval>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConversationItemKind {
    #[serde(rename = "message")]
    Message,
    #[serde(rename = "reasoning")]
    Reasoning,
    #[serde(rename = "command")]
    Command,
    #[serde(rename = "file-change")]
    FileChange,
    #[serde(rename = "tool")]
    Tool,
    #[serde(rename = "approval")]
    Approval,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConversationItemRole {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "assistant")]
    Assistant,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConversationItemStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "interrupted")]
    Interrupted,
    #[serde(rename = "declined")]
    Declined,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "denied")]
    Denied,
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationListRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub route: Option<GatewayProviderRoute>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<Cursor>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<u64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationListResponse {
    pub conversations: Vec<Conversation>,
    pub page_info: PageInfo,
    pub snapshot_cursor: EventCursor,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationSearchRequest {
    pub route: GatewayProviderRoute,
    pub search_term: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<Cursor>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<u64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationSearchResponse {
    pub conversations: Vec<Conversation>,
    pub page_info: PageInfo,
    pub snapshot_cursor: EventCursor,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConversationStatus {
    #[serde(rename = "idle")]
    Idle,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "waiting-approval")]
    WaitingApproval,
    #[serde(rename = "waiting-user-input")]
    WaitingUserInput,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "archived")]
    Archived,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationUpsertedEvent {
    pub conversation: Conversation,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct Device {
    pub device_id: DeviceId,
    pub display_name: String,
    pub status: DeviceStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_seen_at: Option<TimestampMs>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct DeviceListRequest {

}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct DeviceListResponse {
    pub devices: Vec<Device>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum DeviceStatus {
    #[serde(rename = "online")]
    Online,
    #[serde(rename = "offline")]
    Offline,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct DeviceStatusChangedEvent {
    pub device: Device,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub previous_status: Option<DeviceStatus>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct EventSubscribeRequest {
    pub after_cursor: EventCursor,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct EventSubscribeResponse {
    pub subscribed_after_cursor: EventCursor,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct FlatModelCatalog {
    pub kind: FlatModelCatalogKind,
    pub models: Vec<ChoiceOption>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_selection: Option<FlatModelSelection>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum FlatModelCatalogKind {
    #[serde(rename = "flat")]
    Flat,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct FlatModelSelection {
    pub kind: FlatModelCatalogKind,
    pub model_id: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct GatewayCapabilities {
    pub revision: String,
    pub methods: Vec<GatewayCapability>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub turn_send: Option<TurnSendCapabilities>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum GatewayCapability {
    #[serde(rename = "conversation.list")]
    ConversationList,
    #[serde(rename = "conversation.search")]
    ConversationSearch,
    #[serde(rename = "conversation.get")]
    ConversationGet,
    #[serde(rename = "conversation.create")]
    ConversationCreate,
    #[serde(rename = "turn.send")]
    TurnSend,
    #[serde(rename = "turn.interrupt")]
    TurnInterrupt,
    #[serde(rename = "approval.resolve")]
    ApprovalResolve,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct GatewayHostIdentity {
    pub device_id: DeviceId,
    pub descriptor: DeviceDescriptor,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct GatewayProviderRoute {
    pub device_id: DeviceId,
    pub provider_plugin_id: ProviderPluginId,
    pub provider_instance_id: ProviderInstanceId,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct GroupedModelCatalog {
    pub kind: GroupedModelCatalogKind,
    pub providers: Vec<GroupedModelProvider>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_selection: Option<GroupedModelSelection>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum GroupedModelCatalogKind {
    #[serde(rename = "grouped")]
    Grouped,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct GroupedModelProvider {
    pub id: String,
    pub display_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub models: Vec<ChoiceOption>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct GroupedModelSelection {
    pub kind: GroupedModelCatalogKind,
    pub provider_id: String,
    pub model_id: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct HandshakeRequest {
    pub client_id: ClientId,
    pub device: DeviceDescriptor,
    pub client_version: String,
    pub supported_versions: VersionRange,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_event_cursor: Option<EventCursor>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct HandshakeResponse {
    pub selected_version: ProtocolVersion,
    pub server_name: String,
    pub server_version: String,
    pub device: GatewayHostIdentity,
    pub devices: Vec<Device>,
    pub providers: Vec<ProviderInstance>,
    pub event_cursor: EventCursor,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct HarnessDescriptor {
    pub id: String,
    pub display_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ModelCatalog {
    FlatModelCatalog(FlatModelCatalog),
    GroupedModelCatalog(GroupedModelCatalog),
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ModelSelection {
    FlatModelSelection(FlatModelSelection),
    GroupedModelSelection(GroupedModelSelection),
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderInstance {
    pub route: GatewayProviderRoute,
    pub plugin_id: ProviderPluginId,
    pub display_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    pub harness: HarnessDescriptor,
    pub status: ProviderStatus,
    pub capabilities: GatewayCapabilities,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderListRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub device_id: Option<DeviceId>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderListResponse {
    pub providers: Vec<ProviderInstance>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProviderStatus {
    #[serde(rename = "disconnected")]
    Disconnected,
    #[serde(rename = "connecting")]
    Connecting,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "unavailable")]
    Unavailable,
    #[serde(rename = "error")]
    Error,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderStatusChangedEvent {
    pub provider: ProviderInstance,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub previous_status: Option<ProviderStatus>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnInput {
    pub kind: TurnInputKind,
    pub text: String,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum TurnInputKind {
    #[serde(rename = "text")]
    Text,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnInterruptRequest {
    pub conversation: RoutedResourceId,
    pub turn: RoutedResourceId,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnInterruptResponse {
    pub turn: TurnTask,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnOutputDeltaEvent {
    pub turn: RoutedResourceId,
    pub conversation: RoutedResourceId,
    pub item_id: NativeResourceId,
    pub content_id: NativeResourceId,
    pub kind: ConversationContentKind,
    pub delta: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnSelection {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub access_mode_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_effort_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<ModelSelection>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnSendCapabilities {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub access_mode: Option<ChoiceSet>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_effort: Option<ChoiceSet>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model_catalog: Option<ModelCatalog>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnSendRequest {
    pub conversation: RoutedResourceId,
    pub client_request_id: RequestId,
    pub capability_revision: String,
    pub input: TurnInput,
    pub selection: TurnSelection,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnSendResponse {
    pub accepted: bool,
    pub turn: TurnTask,
    pub user_item: Option<ConversationItem>,
    pub effective_selection: TurnSelection,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum TurnStatus {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "waiting-approval")]
    WaitingApproval,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "interrupted")]
    Interrupted,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnTask {
    pub resource: RoutedResourceId,
    pub conversation: RoutedResourceId,
    pub status: TurnStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub display_summary: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub started_at: Option<TimestampMs>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<TimestampMs>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<TimestampMs>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnUpsertedEvent {
    pub turn: TurnTask,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProtocolDispatchLane {
    Normal,
    Control,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProtocolMethod {
    #[serde(rename = "protocol.handshake")]
    ProtocolHandshake,
    #[serde(rename = "event.subscribe")]
    EventSubscribe,
    #[serde(rename = "device.list")]
    DeviceList,
    #[serde(rename = "provider.list")]
    ProviderList,
    #[serde(rename = "conversation.list")]
    ConversationList,
    #[serde(rename = "conversation.search")]
    ConversationSearch,
    #[serde(rename = "conversation.get")]
    ConversationGet,
    #[serde(rename = "conversation.acquireInteraction")]
    ConversationAcquireInteraction,
    #[serde(rename = "conversation.create")]
    ConversationCreate,
    #[serde(rename = "turn.send")]
    TurnSend,
    #[serde(rename = "turn.interrupt")]
    TurnInterrupt,
    #[serde(rename = "approval.resolve")]
    ApprovalResolve,
}

impl ProtocolMethod {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ProtocolHandshake => "protocol.handshake",
            Self::EventSubscribe => "event.subscribe",
            Self::DeviceList => "device.list",
            Self::ProviderList => "provider.list",
            Self::ConversationList => "conversation.list",
            Self::ConversationSearch => "conversation.search",
            Self::ConversationGet => "conversation.get",
            Self::ConversationAcquireInteraction => "conversation.acquireInteraction",
            Self::ConversationCreate => "conversation.create",
            Self::TurnSend => "turn.send",
            Self::TurnInterrupt => "turn.interrupt",
            Self::ApprovalResolve => "approval.resolve",
        }
    }

    pub const fn dispatch_lane(self) -> ProtocolDispatchLane {
        match self {
            Self::ProtocolHandshake => ProtocolDispatchLane::Normal,
            Self::EventSubscribe => ProtocolDispatchLane::Normal,
            Self::DeviceList => ProtocolDispatchLane::Normal,
            Self::ProviderList => ProtocolDispatchLane::Normal,
            Self::ConversationList => ProtocolDispatchLane::Normal,
            Self::ConversationSearch => ProtocolDispatchLane::Normal,
            Self::ConversationGet => ProtocolDispatchLane::Normal,
            Self::ConversationAcquireInteraction => ProtocolDispatchLane::Normal,
            Self::ConversationCreate => ProtocolDispatchLane::Normal,
            Self::TurnSend => ProtocolDispatchLane::Normal,
            Self::TurnInterrupt => ProtocolDispatchLane::Normal,
            Self::ApprovalResolve => ProtocolDispatchLane::Normal,
        }
    }

    pub const fn capability(self) -> Option<GatewayCapability> {
        match self {
            Self::ProtocolHandshake => None,
            Self::EventSubscribe => None,
            Self::DeviceList => None,
            Self::ProviderList => None,
            Self::ConversationList => Some(GatewayCapability::ConversationList),
            Self::ConversationSearch => Some(GatewayCapability::ConversationSearch),
            Self::ConversationGet => Some(GatewayCapability::ConversationGet),
            Self::ConversationAcquireInteraction => None,
            Self::ConversationCreate => Some(GatewayCapability::ConversationCreate),
            Self::TurnSend => Some(GatewayCapability::TurnSend),
            Self::TurnInterrupt => Some(GatewayCapability::TurnInterrupt),
            Self::ApprovalResolve => Some(GatewayCapability::ApprovalResolve),
        }
    }
}

impl std::str::FromStr for ProtocolMethod {
    type Err = ();

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "protocol.handshake" => Ok(Self::ProtocolHandshake),
            "event.subscribe" => Ok(Self::EventSubscribe),
            "device.list" => Ok(Self::DeviceList),
            "provider.list" => Ok(Self::ProviderList),
            "conversation.list" => Ok(Self::ConversationList),
            "conversation.search" => Ok(Self::ConversationSearch),
            "conversation.get" => Ok(Self::ConversationGet),
            "conversation.acquireInteraction" => Ok(Self::ConversationAcquireInteraction),
            "conversation.create" => Ok(Self::ConversationCreate),
            "turn.send" => Ok(Self::TurnSend),
            "turn.interrupt" => Ok(Self::TurnInterrupt),
            "approval.resolve" => Ok(Self::ApprovalResolve),
            _ => Err(()),
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProtocolEventName {
    #[serde(rename = "device.statusChanged")]
    DeviceStatusChanged,
    #[serde(rename = "provider.statusChanged")]
    ProviderStatusChanged,
    #[serde(rename = "conversation.upserted")]
    ConversationUpserted,
    #[serde(rename = "turn.upserted")]
    TurnUpserted,
    #[serde(rename = "turn.outputDelta")]
    TurnOutputDelta,
    #[serde(rename = "approval.requested")]
    ApprovalRequested,
    #[serde(rename = "approval.resolved")]
    ApprovalResolved,
}

impl ProtocolEventName {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::DeviceStatusChanged => "device.statusChanged",
            Self::ProviderStatusChanged => "provider.statusChanged",
            Self::ConversationUpserted => "conversation.upserted",
            Self::TurnUpserted => "turn.upserted",
            Self::TurnOutputDelta => "turn.outputDelta",
            Self::ApprovalRequested => "approval.requested",
            Self::ApprovalResolved => "approval.resolved",
        }
    }
}

impl std::str::FromStr for ProtocolEventName {
    type Err = ();

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "device.statusChanged" => Ok(Self::DeviceStatusChanged),
            "provider.statusChanged" => Ok(Self::ProviderStatusChanged),
            "conversation.upserted" => Ok(Self::ConversationUpserted),
            "turn.upserted" => Ok(Self::TurnUpserted),
            "turn.outputDelta" => Ok(Self::TurnOutputDelta),
            "approval.requested" => Ok(Self::ApprovalRequested),
            "approval.resolved" => Ok(Self::ApprovalResolved),
            _ => Err(()),
        }
    }
}

pub const JSON_RPC_PARSE_ERROR: i64 = -32700;
pub const JSON_RPC_INVALID_REQUEST: i64 = -32600;
pub const JSON_RPC_METHOD_NOT_FOUND: i64 = -32601;
pub const JSON_RPC_INVALID_PARAMS: i64 = -32602;
pub const JSON_RPC_INTERNAL_ERROR: i64 = -32603;
pub const DEFAULT_MAX_JSON_LINE_BYTES: usize = 1024 * 1024;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "method")]
pub enum ProtocolRequest {
    #[serde(rename = "protocol.handshake")]
    ProtocolHandshake {
        jsonrpc: String,
        id: RequestId,
        params: HandshakeRequest,
    },
    #[serde(rename = "event.subscribe")]
    EventSubscribe {
        jsonrpc: String,
        id: RequestId,
        params: EventSubscribeRequest,
    },
    #[serde(rename = "device.list")]
    DeviceList {
        jsonrpc: String,
        id: RequestId,
        params: DeviceListRequest,
    },
    #[serde(rename = "provider.list")]
    ProviderList {
        jsonrpc: String,
        id: RequestId,
        params: ProviderListRequest,
    },
    #[serde(rename = "conversation.list")]
    ConversationList {
        jsonrpc: String,
        id: RequestId,
        params: ConversationListRequest,
    },
    #[serde(rename = "conversation.search")]
    ConversationSearch {
        jsonrpc: String,
        id: RequestId,
        params: ConversationSearchRequest,
    },
    #[serde(rename = "conversation.get")]
    ConversationGet {
        jsonrpc: String,
        id: RequestId,
        params: ConversationGetRequest,
    },
    #[serde(rename = "conversation.acquireInteraction")]
    ConversationAcquireInteraction {
        jsonrpc: String,
        id: RequestId,
        params: ConversationAcquireInteractionRequest,
    },
    #[serde(rename = "conversation.create")]
    ConversationCreate {
        jsonrpc: String,
        id: RequestId,
        params: ConversationCreateRequest,
    },
    #[serde(rename = "turn.send")]
    TurnSend {
        jsonrpc: String,
        id: RequestId,
        params: TurnSendRequest,
    },
    #[serde(rename = "turn.interrupt")]
    TurnInterrupt {
        jsonrpc: String,
        id: RequestId,
        params: TurnInterruptRequest,
    },
    #[serde(rename = "approval.resolve")]
    ApprovalResolve {
        jsonrpc: String,
        id: RequestId,
        params: ApprovalResolveRequest,
    },
}

impl ProtocolRequest {
    pub fn from_method_params(
        method: ProtocolMethod,
        id: RequestId,
        params: serde_json::Value,
    ) -> Result<Self, ProtocolError> {
        let jsonrpc = "2.0".to_string();
        match method {
            ProtocolMethod::ProtocolHandshake => Ok(Self::ProtocolHandshake {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode protocol.handshake request params", error))?,
            }),
            ProtocolMethod::EventSubscribe => Ok(Self::EventSubscribe {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode event.subscribe request params", error))?,
            }),
            ProtocolMethod::DeviceList => Ok(Self::DeviceList {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode device.list request params", error))?,
            }),
            ProtocolMethod::ProviderList => Ok(Self::ProviderList {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode provider.list request params", error))?,
            }),
            ProtocolMethod::ConversationList => Ok(Self::ConversationList {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode conversation.list request params", error))?,
            }),
            ProtocolMethod::ConversationSearch => Ok(Self::ConversationSearch {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode conversation.search request params", error))?,
            }),
            ProtocolMethod::ConversationGet => Ok(Self::ConversationGet {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode conversation.get request params", error))?,
            }),
            ProtocolMethod::ConversationAcquireInteraction => Ok(Self::ConversationAcquireInteraction {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode conversation.acquireInteraction request params", error))?,
            }),
            ProtocolMethod::ConversationCreate => Ok(Self::ConversationCreate {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode conversation.create request params", error))?,
            }),
            ProtocolMethod::TurnSend => Ok(Self::TurnSend {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode turn.send request params", error))?,
            }),
            ProtocolMethod::TurnInterrupt => Ok(Self::TurnInterrupt {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode turn.interrupt request params", error))?,
            }),
            ProtocolMethod::ApprovalResolve => Ok(Self::ApprovalResolve {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode approval.resolve request params", error))?,
            }),
        }
    }

    pub fn jsonrpc_version(&self) -> &str {
        match self {
            Self::ProtocolHandshake { jsonrpc, .. } => jsonrpc,
            Self::EventSubscribe { jsonrpc, .. } => jsonrpc,
            Self::DeviceList { jsonrpc, .. } => jsonrpc,
            Self::ProviderList { jsonrpc, .. } => jsonrpc,
            Self::ConversationList { jsonrpc, .. } => jsonrpc,
            Self::ConversationSearch { jsonrpc, .. } => jsonrpc,
            Self::ConversationGet { jsonrpc, .. } => jsonrpc,
            Self::ConversationAcquireInteraction { jsonrpc, .. } => jsonrpc,
            Self::ConversationCreate { jsonrpc, .. } => jsonrpc,
            Self::TurnSend { jsonrpc, .. } => jsonrpc,
            Self::TurnInterrupt { jsonrpc, .. } => jsonrpc,
            Self::ApprovalResolve { jsonrpc, .. } => jsonrpc,
        }
    }

    pub fn id(&self) -> &RequestId {
        match self {
            Self::ProtocolHandshake { id, .. } => id,
            Self::EventSubscribe { id, .. } => id,
            Self::DeviceList { id, .. } => id,
            Self::ProviderList { id, .. } => id,
            Self::ConversationList { id, .. } => id,
            Self::ConversationSearch { id, .. } => id,
            Self::ConversationGet { id, .. } => id,
            Self::ConversationAcquireInteraction { id, .. } => id,
            Self::ConversationCreate { id, .. } => id,
            Self::TurnSend { id, .. } => id,
            Self::TurnInterrupt { id, .. } => id,
            Self::ApprovalResolve { id, .. } => id,
        }
    }

    pub const fn method(&self) -> ProtocolMethod {
        match self {
            Self::ProtocolHandshake { .. } => ProtocolMethod::ProtocolHandshake,
            Self::EventSubscribe { .. } => ProtocolMethod::EventSubscribe,
            Self::DeviceList { .. } => ProtocolMethod::DeviceList,
            Self::ProviderList { .. } => ProtocolMethod::ProviderList,
            Self::ConversationList { .. } => ProtocolMethod::ConversationList,
            Self::ConversationSearch { .. } => ProtocolMethod::ConversationSearch,
            Self::ConversationGet { .. } => ProtocolMethod::ConversationGet,
            Self::ConversationAcquireInteraction { .. } => ProtocolMethod::ConversationAcquireInteraction,
            Self::ConversationCreate { .. } => ProtocolMethod::ConversationCreate,
            Self::TurnSend { .. } => ProtocolMethod::TurnSend,
            Self::TurnInterrupt { .. } => ProtocolMethod::TurnInterrupt,
            Self::ApprovalResolve { .. } => ProtocolMethod::ApprovalResolve,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProtocolEventParams<T> {
    #[serde(rename = "eventCursor")]
    pub event_cursor: EventCursor,
    pub payload: T,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "method")]
pub enum ProtocolEvent {
    #[serde(rename = "device.statusChanged")]
    DeviceStatusChanged {
        jsonrpc: String,
        params: ProtocolEventParams<DeviceStatusChangedEvent>,
    },
    #[serde(rename = "provider.statusChanged")]
    ProviderStatusChanged {
        jsonrpc: String,
        params: ProtocolEventParams<ProviderStatusChangedEvent>,
    },
    #[serde(rename = "conversation.upserted")]
    ConversationUpserted {
        jsonrpc: String,
        params: ProtocolEventParams<ConversationUpsertedEvent>,
    },
    #[serde(rename = "turn.upserted")]
    TurnUpserted {
        jsonrpc: String,
        params: ProtocolEventParams<TurnUpsertedEvent>,
    },
    #[serde(rename = "turn.outputDelta")]
    TurnOutputDelta {
        jsonrpc: String,
        params: ProtocolEventParams<TurnOutputDeltaEvent>,
    },
    #[serde(rename = "approval.requested")]
    ApprovalRequested {
        jsonrpc: String,
        params: ProtocolEventParams<ApprovalRequestedEvent>,
    },
    #[serde(rename = "approval.resolved")]
    ApprovalResolved {
        jsonrpc: String,
        params: ProtocolEventParams<ApprovalResolvedEvent>,
    },
}

impl ProtocolEvent {
    pub fn jsonrpc_version(&self) -> &str {
        match self {
            Self::DeviceStatusChanged { jsonrpc, .. } => jsonrpc,
            Self::ProviderStatusChanged { jsonrpc, .. } => jsonrpc,
            Self::ConversationUpserted { jsonrpc, .. } => jsonrpc,
            Self::TurnUpserted { jsonrpc, .. } => jsonrpc,
            Self::TurnOutputDelta { jsonrpc, .. } => jsonrpc,
            Self::ApprovalRequested { jsonrpc, .. } => jsonrpc,
            Self::ApprovalResolved { jsonrpc, .. } => jsonrpc,
        }
    }

    pub fn event_cursor(&self) -> &EventCursor {
        match self {
            Self::DeviceStatusChanged { params, .. } => &params.event_cursor,
            Self::ProviderStatusChanged { params, .. } => &params.event_cursor,
            Self::ConversationUpserted { params, .. } => &params.event_cursor,
            Self::TurnUpserted { params, .. } => &params.event_cursor,
            Self::TurnOutputDelta { params, .. } => &params.event_cursor,
            Self::ApprovalRequested { params, .. } => &params.event_cursor,
            Self::ApprovalResolved { params, .. } => &params.event_cursor,
        }
    }

    pub fn set_event_cursor(&mut self, cursor: EventCursor) {
        match self {
            Self::DeviceStatusChanged { jsonrpc, params } => {
                *jsonrpc = "2.0".to_string();
                params.event_cursor = cursor;
            },
            Self::ProviderStatusChanged { jsonrpc, params } => {
                *jsonrpc = "2.0".to_string();
                params.event_cursor = cursor;
            },
            Self::ConversationUpserted { jsonrpc, params } => {
                *jsonrpc = "2.0".to_string();
                params.event_cursor = cursor;
            },
            Self::TurnUpserted { jsonrpc, params } => {
                *jsonrpc = "2.0".to_string();
                params.event_cursor = cursor;
            },
            Self::TurnOutputDelta { jsonrpc, params } => {
                *jsonrpc = "2.0".to_string();
                params.event_cursor = cursor;
            },
            Self::ApprovalRequested { jsonrpc, params } => {
                *jsonrpc = "2.0".to_string();
                params.event_cursor = cursor;
            },
            Self::ApprovalResolved { jsonrpc, params } => {
                *jsonrpc = "2.0".to_string();
                params.event_cursor = cursor;
            },
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JsonRpcResponsePayload {
    Ok { result: serde_json::Value },
    Error { error: RpcError },
}

#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct JsonRpcResponse {
    pub jsonrpc: String,
    pub id: Option<RequestId>,
    #[serde(flatten)]
    pub response: JsonRpcResponsePayload,
}

impl<'de> Deserialize<'de> for JsonRpcResponse {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = serde_json::Value::deserialize(deserializer)?;
        parse_jsonrpc_response(value).map_err(|error| serde::de::Error::custom(error.to_string()))
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JsonRpcNotification {
    pub jsonrpc: String,
    pub method: String,
    #[serde(default, skip_serializing_if = "serde_json::Value::is_null")]
    pub params: serde_json::Value,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JsonRpcRequestRejection {
    pub id: RequestId,
    pub method: String,
    pub error: RpcError,
}

impl JsonRpcRequestRejection {
    pub fn into_response(self) -> JsonRpcResponse {
        JsonRpcResponse {
            jsonrpc: "2.0".to_string(),
            id: Some(self.id),
            response: JsonRpcResponsePayload::Error { error: self.error },
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum JsonRpcInboundRequest {
    Typed(ProtocolRequest),
    Rejected(JsonRpcRequestRejection),
}

#[derive(Clone, Debug, PartialEq)]
pub enum ProviderWireMessage {
    Request(JsonRpcInboundRequest),
    Response(JsonRpcResponse),
    Notification(JsonRpcNotification),
    Event(ProtocolEvent),
}

#[derive(Clone, Debug, PartialEq)]
pub struct JsonRpcInboundError {
    pub id: Option<RequestId>,
    pub error: RpcError,
}

impl JsonRpcInboundError {
    pub fn into_response(self) -> JsonRpcResponse {
        JsonRpcResponse {
            jsonrpc: "2.0".to_string(),
            id: self.id,
            response: JsonRpcResponsePayload::Error { error: self.error },
        }
    }
}

impl std::fmt::Display for JsonRpcInboundError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(formatter, "JSON-RPC error {}: {}", self.error.code, self.error.message)
    }
}

impl std::error::Error for JsonRpcInboundError {}

pub type ProtocolFuture<'a, T> = Pin<Box<dyn Future<Output = Result<T, ProtocolError>> + Send + 'a>>;

pub trait ProtocolServer: Send + Sync {
    fn protocol_handshake<'a>(&'a self, _request: HandshakeRequest) -> ProtocolFuture<'a, HandshakeResponse> {
        Box::pin(async { Err(method_not_implemented("protocol.handshake")) })
    }

    fn event_subscribe<'a>(&'a self, _request: EventSubscribeRequest) -> ProtocolFuture<'a, EventSubscribeResponse> {
        Box::pin(async { Err(method_not_implemented("event.subscribe")) })
    }

    fn device_list<'a>(&'a self, _request: DeviceListRequest) -> ProtocolFuture<'a, DeviceListResponse> {
        Box::pin(async { Err(method_not_implemented("device.list")) })
    }

    fn provider_list<'a>(&'a self, _request: ProviderListRequest) -> ProtocolFuture<'a, ProviderListResponse> {
        Box::pin(async { Err(method_not_implemented("provider.list")) })
    }

    fn conversation_list<'a>(&'a self, _request: ConversationListRequest) -> ProtocolFuture<'a, ConversationListResponse> {
        Box::pin(async { Err(method_not_implemented("conversation.list")) })
    }

    fn conversation_search<'a>(&'a self, _request: ConversationSearchRequest) -> ProtocolFuture<'a, ConversationSearchResponse> {
        Box::pin(async { Err(method_not_implemented("conversation.search")) })
    }

    fn conversation_get<'a>(&'a self, _request: ConversationGetRequest) -> ProtocolFuture<'a, ConversationGetResponse> {
        Box::pin(async { Err(method_not_implemented("conversation.get")) })
    }

    fn conversation_acquire_interaction<'a>(&'a self, _request: ConversationAcquireInteractionRequest) -> ProtocolFuture<'a, ConversationAcquireInteractionResponse> {
        Box::pin(async { Err(method_not_implemented("conversation.acquireInteraction")) })
    }

    fn conversation_create<'a>(&'a self, _request: ConversationCreateRequest) -> ProtocolFuture<'a, ConversationCreateResponse> {
        Box::pin(async { Err(method_not_implemented("conversation.create")) })
    }

    fn turn_send<'a>(&'a self, _request: TurnSendRequest) -> ProtocolFuture<'a, TurnSendResponse> {
        Box::pin(async { Err(method_not_implemented("turn.send")) })
    }

    fn turn_interrupt<'a>(&'a self, _request: TurnInterruptRequest) -> ProtocolFuture<'a, TurnInterruptResponse> {
        Box::pin(async { Err(method_not_implemented("turn.interrupt")) })
    }

    fn approval_resolve<'a>(&'a self, _request: ApprovalResolveRequest) -> ProtocolFuture<'a, ApprovalResolveResponse> {
        Box::pin(async { Err(method_not_implemented("approval.resolve")) })
    }
}

fn method_not_implemented(method: &str) -> ProtocolError {
    ProtocolError {
        code: "method_not_implemented".to_string(),
        message: format!("protocol method is not implemented: {method}"),
        retryable: false,
        details: None,
    }
}

pub async fn dispatch<S: ProtocolServer + ?Sized>(server: &S, request: ProtocolRequest) -> JsonRpcResponse {
    match request {
        ProtocolRequest::ProtocolHandshake { jsonrpc, id, params } => {
            let response = match server.protocol_handshake(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::EventSubscribe { jsonrpc, id, params } => {
            let response = match server.event_subscribe(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::DeviceList { jsonrpc, id, params } => {
            let response = match server.device_list(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::ProviderList { jsonrpc, id, params } => {
            let response = match server.provider_list(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::ConversationList { jsonrpc, id, params } => {
            let response = match server.conversation_list(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::ConversationSearch { jsonrpc, id, params } => {
            let response = match server.conversation_search(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::ConversationGet { jsonrpc, id, params } => {
            let response = match server.conversation_get(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::ConversationAcquireInteraction { jsonrpc, id, params } => {
            let response = match server.conversation_acquire_interaction(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::ConversationCreate { jsonrpc, id, params } => {
            let response = match server.conversation_create(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::TurnSend { jsonrpc, id, params } => {
            let response = match server.turn_send(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::TurnInterrupt { jsonrpc, id, params } => {
            let response = match server.turn_interrupt(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::ApprovalResolve { jsonrpc, id, params } => {
            let response = match server.approval_resolve(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        }
    }
}

pub struct ProtocolDispatcher<S> {
    server: S,
}

impl<S> ProtocolDispatcher<S> {
    pub const fn new(server: S) -> Self {
        Self { server }
    }

    pub const fn server(&self) -> &S {
        &self.server
    }
}

impl<S: ProtocolServer> ProtocolDispatcher<S> {
    pub async fn dispatch(&self, request: ProtocolRequest) -> JsonRpcResponse {
        dispatch(&self.server, request).await
    }
}

pub type ProtocolTransportFuture<'a> = Pin<Box<dyn Future<Output = Result<serde_json::Value, ProtocolError>> + Send + 'a>>;

pub type ProtocolInboundFuture<'a> = Pin<Box<dyn Future<Output = Result<ProviderWireMessage, JsonRpcInboundError>> + Send + 'a>>;

pub trait ProtocolTransport: Send + Sync {
    fn request<'a>(&'a self, method: ProtocolMethod, params: serde_json::Value) -> ProtocolTransportFuture<'a>;
    fn next_message<'a>(&'a self) -> ProtocolInboundFuture<'a>;
}

pub struct ProtocolClient<T> {
    transport: T,
}

impl<T> ProtocolClient<T> {
    pub const fn new(transport: T) -> Self {
        Self { transport }
    }

    pub const fn transport(&self) -> &T {
        &self.transport
    }
}

impl<T: ProtocolTransport> ProtocolClient<T> {
    pub fn protocol_handshake<'a>(&'a self, request: HandshakeRequest) -> ProtocolFuture<'a, HandshakeResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ProtocolHandshake, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn event_subscribe<'a>(&'a self, request: EventSubscribeRequest) -> ProtocolFuture<'a, EventSubscribeResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::EventSubscribe, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn device_list<'a>(&'a self, request: DeviceListRequest) -> ProtocolFuture<'a, DeviceListResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::DeviceList, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn provider_list<'a>(&'a self, request: ProviderListRequest) -> ProtocolFuture<'a, ProviderListResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ProviderList, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn conversation_list<'a>(&'a self, request: ConversationListRequest) -> ProtocolFuture<'a, ConversationListResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ConversationList, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn conversation_search<'a>(&'a self, request: ConversationSearchRequest) -> ProtocolFuture<'a, ConversationSearchResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ConversationSearch, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn conversation_get<'a>(&'a self, request: ConversationGetRequest) -> ProtocolFuture<'a, ConversationGetResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ConversationGet, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn conversation_acquire_interaction<'a>(&'a self, request: ConversationAcquireInteractionRequest) -> ProtocolFuture<'a, ConversationAcquireInteractionResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ConversationAcquireInteraction, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn conversation_create<'a>(&'a self, request: ConversationCreateRequest) -> ProtocolFuture<'a, ConversationCreateResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ConversationCreate, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn turn_send<'a>(&'a self, request: TurnSendRequest) -> ProtocolFuture<'a, TurnSendResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::TurnSend, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn turn_interrupt<'a>(&'a self, request: TurnInterruptRequest) -> ProtocolFuture<'a, TurnInterruptResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::TurnInterrupt, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn approval_resolve<'a>(&'a self, request: ApprovalResolveRequest) -> ProtocolFuture<'a, ApprovalResolveResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ApprovalResolve, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn next_message<'a>(&'a self) -> ProtocolInboundFuture<'a> {
        self.transport.next_message()
    }
}

fn rpc_method_error(error: ProtocolError) -> RpcError {
    let message = error.message.clone();
    let data = serde_json::to_value(error).ok().and_then(|value| match value {
        serde_json::Value::Object(entries) => Some(entries.into_iter().collect()),
        _ => None,
    });
    RpcError { code: -32000, message, data }
}

fn rpc_codec_error(context: &str, error: serde_json::Error) -> RpcError {
    RpcError { code: JSON_RPC_INTERNAL_ERROR, message: format!("{context}: {error}"), data: None }
}

fn codec_error(context: &str, error: serde_json::Error) -> ProtocolError {
    ProtocolError {
        code: "protocol_codec_error".to_string(),
        message: format!("{context}: {error}"),
        retryable: false,
        details: None,
    }
}

fn inbound_error(id: Option<RequestId>, code: i64, message: impl Into<String>) -> JsonRpcInboundError {
    JsonRpcInboundError {
        id,
        error: RpcError { code, message: message.into(), data: None },
    }
}

fn inbound_protocol_error(error: JsonRpcInboundError) -> ProtocolError {
    ProtocolError {
        code: format!("json_rpc_{}", error.error.code),
        message: error.error.message,
        retryable: false,
        details: error.error.data,
    }
}

fn object_has_only(object: &serde_json::Map<String, serde_json::Value>, allowed: &[&str]) -> bool {
    object.keys().all(|key| allowed.contains(&key.as_str()))
}

fn object_request_id(object: &serde_json::Map<String, serde_json::Value>) -> Option<RequestId> {
    object.get("id").and_then(serde_json::Value::as_str).map(str::to_string)
}

fn validate_jsonrpc(version: &str) -> Result<(), ProtocolError> {
    if version == "2.0" {
        return Ok(());
    }
    Err(ProtocolError {
        code: "unsupported_jsonrpc_version".to_string(),
        message: format!("unsupported JSON-RPC version: {version}"),
        retryable: false,
        details: None,
    })
}

fn validate_inbound_jsonrpc(object: &serde_json::Map<String, serde_json::Value>, id: Option<RequestId>) -> Result<(), JsonRpcInboundError> {
    match object.get("jsonrpc").and_then(serde_json::Value::as_str) {
        Some("2.0") => Ok(()),
        _ => Err(inbound_error(id, JSON_RPC_INVALID_REQUEST, "jsonrpc must be exactly 2.0")),
    }
}

fn parse_jsonrpc_response(value: serde_json::Value) -> Result<JsonRpcResponse, JsonRpcInboundError> {
    let object = value.as_object().ok_or_else(|| inbound_error(None, JSON_RPC_INVALID_REQUEST, "JSON-RPC response must be an object"))?;
    let id = match object.get("id") {
        Some(serde_json::Value::String(value)) => Some(value.clone()),
        Some(serde_json::Value::Null) => None,
        _ => return Err(inbound_error(None, JSON_RPC_INVALID_REQUEST, "JSON-RPC response id must be a string or null")),
    };
    validate_inbound_jsonrpc(object, id.clone())?;
    let has_result = object.contains_key("result");
    let has_error = object.contains_key("error");
    if has_result == has_error {
        return Err(inbound_error(id, JSON_RPC_INVALID_REQUEST, "JSON-RPC response must contain exactly one of result or error"));
    }
    if !object_has_only(object, &["jsonrpc", "id", if has_result { "result" } else { "error" }]) {
        return Err(inbound_error(id, JSON_RPC_INVALID_REQUEST, "JSON-RPC response contains unknown fields"));
    }
    let response = if has_result {
        JsonRpcResponsePayload::Ok { result: object["result"].clone() }
    } else {
        let error = serde_json::from_value(object["error"].clone())
            .map_err(|error| inbound_error(id.clone(), JSON_RPC_INVALID_REQUEST, format!("invalid JSON-RPC error object: {error}")))?;
        JsonRpcResponsePayload::Error { error }
    };
    Ok(JsonRpcResponse { jsonrpc: "2.0".to_string(), id, response })
}

pub fn decode_wire_message(value: &[u8]) -> Result<ProviderWireMessage, JsonRpcInboundError> {
    let value: serde_json::Value = serde_json::from_slice(value)
        .map_err(|error| inbound_error(None, JSON_RPC_PARSE_ERROR, format!("parse error: {error}")))?;
    let object = value.as_object().ok_or_else(|| inbound_error(None, JSON_RPC_INVALID_REQUEST, "JSON-RPC message must be an object"))?;
    let id = object_request_id(object);
    validate_inbound_jsonrpc(object, id.clone())?;

    if let Some(method_value) = object.get("method") {
        let method = method_value.as_str().ok_or_else(|| inbound_error(id.clone(), JSON_RPC_INVALID_REQUEST, "JSON-RPC method must be a string"))?.to_string();
        if object.contains_key("id") {
            let id = id.ok_or_else(|| inbound_error(None, JSON_RPC_INVALID_REQUEST, "JSON-RPC request id must be a string"))?;
            if !object_has_only(object, &["jsonrpc", "id", "method", "params"]) {
                return Err(inbound_error(Some(id), JSON_RPC_INVALID_REQUEST, "JSON-RPC request contains unknown fields"));
            }
            if method.parse::<ProtocolMethod>().is_err() {
                return Ok(ProviderWireMessage::Request(JsonRpcInboundRequest::Rejected(JsonRpcRequestRejection {
                    id,
                    method: method.clone(),
                    error: RpcError { code: JSON_RPC_METHOD_NOT_FOUND, message: format!("method not found: {method}"), data: None },
                })));
            }
            return match serde_json::from_value(value) {
                Ok(request) => Ok(ProviderWireMessage::Request(JsonRpcInboundRequest::Typed(request))),
                Err(error) => Ok(ProviderWireMessage::Request(JsonRpcInboundRequest::Rejected(JsonRpcRequestRejection {
                    id,
                    method: method.clone(),
                    error: RpcError { code: JSON_RPC_INVALID_PARAMS, message: format!("invalid params for {method}: {error}"), data: None },
                }))),
            };
        }

        if !object_has_only(object, &["jsonrpc", "method", "params"]) {
            return Err(inbound_error(None, JSON_RPC_INVALID_REQUEST, "JSON-RPC notification contains unknown fields"));
        }
        if method.parse::<ProtocolEventName>().is_ok() {
            let event = serde_json::from_value(value)
                .map_err(|error| inbound_error(None, JSON_RPC_INVALID_PARAMS, format!("invalid event params for {method}: {error}")))?;
            return Ok(ProviderWireMessage::Event(event));
        }
        return Ok(ProviderWireMessage::Notification(JsonRpcNotification {
            jsonrpc: "2.0".to_string(),
            method,
            params: object.get("params").cloned().unwrap_or(serde_json::Value::Null),
        }));
    }

    parse_jsonrpc_response(value).map(ProviderWireMessage::Response)
}

pub fn encode_request(value: &ProtocolRequest) -> Result<Vec<u8>, ProtocolError> {
    validate_jsonrpc(value.jsonrpc_version())?;
    serde_json::to_vec(value).map_err(|error| codec_error("encode request", error))
}

pub fn decode_request(value: &[u8]) -> Result<ProtocolRequest, ProtocolError> {
    match decode_wire_message(value).map_err(inbound_protocol_error)? {
        ProviderWireMessage::Request(JsonRpcInboundRequest::Typed(request)) => Ok(request),
        ProviderWireMessage::Request(JsonRpcInboundRequest::Rejected(rejection)) => Err(inbound_protocol_error(JsonRpcInboundError {
            id: Some(rejection.id),
            error: rejection.error,
        })),
        _ => Err(ProtocolError {
            code: "unexpected_json_rpc_message".to_string(),
            message: "expected JSON-RPC request".to_string(),
            retryable: false,
            details: None,
        }),
    }
}

pub fn encode_response(value: &JsonRpcResponse) -> Result<Vec<u8>, ProtocolError> {
    validate_jsonrpc(&value.jsonrpc)?;
    serde_json::to_vec(value).map_err(|error| codec_error("encode response", error))
}

pub fn decode_response(value: &[u8]) -> Result<JsonRpcResponse, ProtocolError> {
    match decode_wire_message(value).map_err(inbound_protocol_error)? {
        ProviderWireMessage::Response(response) => Ok(response),
        _ => Err(ProtocolError {
            code: "unexpected_json_rpc_message".to_string(),
            message: "expected JSON-RPC response".to_string(),
            retryable: false,
            details: None,
        }),
    }
}

pub fn encode_event(value: &ProtocolEvent) -> Result<Vec<u8>, ProtocolError> {
    validate_jsonrpc(value.jsonrpc_version())?;
    serde_json::to_vec(value).map_err(|error| codec_error("encode event", error))
}

pub fn decode_event(value: &[u8]) -> Result<ProtocolEvent, ProtocolError> {
    match decode_wire_message(value).map_err(inbound_protocol_error)? {
        ProviderWireMessage::Event(event) => Ok(event),
        _ => Err(ProtocolError {
            code: "unexpected_json_rpc_message".to_string(),
            message: "expected JSON-RPC event".to_string(),
            retryable: false,
            details: None,
        }),
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct JsonLineCodec {
    max_frame_bytes: usize,
}

impl JsonLineCodec {
    pub fn new(max_frame_bytes: usize) -> Result<Self, ProtocolError> {
        if max_frame_bytes == 0 {
            return Err(ProtocolError {
                code: "invalid_frame_limit".to_string(),
                message: "JSON line frame limit must be greater than zero".to_string(),
                retryable: false,
                details: None,
            });
        }
        Ok(Self { max_frame_bytes })
    }

    pub const fn max_frame_bytes(&self) -> usize {
        self.max_frame_bytes
    }

    fn frame_payload(&self, mut payload: Vec<u8>) -> Result<Vec<u8>, ProtocolError> {
        if payload.len() > self.max_frame_bytes {
            return Err(ProtocolError {
                code: "json_line_frame_too_large".to_string(),
                message: format!("JSON line frame exceeds {} bytes", self.max_frame_bytes),
                retryable: false,
                details: None,
            });
        }
        if payload.contains(&b'\n') || payload.contains(&b'\r') {
            return Err(ProtocolError {
                code: "invalid_json_line_frame".to_string(),
                message: "JSON line payload contains a physical line break".to_string(),
                retryable: false,
                details: None,
            });
        }
        payload.push(b'\n');
        Ok(payload)
    }

    pub fn encode_message(&self, message: &ProviderWireMessage) -> Result<Vec<u8>, ProtocolError> {
        let payload = match message {
            ProviderWireMessage::Request(JsonRpcInboundRequest::Typed(request)) => encode_request(request)?,
            ProviderWireMessage::Request(JsonRpcInboundRequest::Rejected(_)) => {
                return Err(ProtocolError {
                    code: "cannot_encode_rejected_request".to_string(),
                    message: "a rejected inbound request is not a wire request".to_string(),
                    retryable: false,
                    details: None,
                });
            }
            ProviderWireMessage::Response(response) => encode_response(response)?,
            ProviderWireMessage::Notification(notification) => {
                validate_jsonrpc(&notification.jsonrpc)?;
                serde_json::to_vec(notification).map_err(|error| codec_error("encode notification", error))?
            }
            ProviderWireMessage::Event(event) => encode_event(event)?,
        };
        self.frame_payload(payload)
    }

    pub fn decode_line(&self, line: &[u8]) -> Result<ProviderWireMessage, JsonRpcInboundError> {
        let mut payload = line;
        if payload.ends_with(b"\n") {
            payload = &payload[..payload.len() - 1];
            if payload.ends_with(b"\r") {
                payload = &payload[..payload.len() - 1];
            }
        }
        if payload.len() > self.max_frame_bytes {
            return Err(inbound_error(None, JSON_RPC_INVALID_REQUEST, format!("JSON line frame exceeds {} bytes", self.max_frame_bytes)));
        }
        if payload.contains(&b'\n') || payload.contains(&b'\r') {
            return Err(inbound_error(None, JSON_RPC_INVALID_REQUEST, "JSON line frame contains multiple physical lines"));
        }
        decode_wire_message(payload)
    }

    pub fn read_message<R: BufRead>(&self, reader: &mut R) -> Result<Option<ProviderWireMessage>, JsonRpcInboundError> {
        let mut frame = Vec::with_capacity(self.max_frame_bytes.min(8192));
        let mut oversized = false;
        loop {
            let (consumed, complete) = {
                let available = reader.fill_buf()
                    .map_err(|error| inbound_error(None, JSON_RPC_INTERNAL_ERROR, format!("read JSON line frame: {error}")))?;
                if available.is_empty() {
                    if oversized {
                        return Err(inbound_error(None, JSON_RPC_INVALID_REQUEST, format!("JSON line frame exceeds {} bytes", self.max_frame_bytes)));
                    }
                    if frame.is_empty() {
                        return Ok(None);
                    }
                    return self.decode_line(&frame).map(Some);
                }
                let newline = available.iter().position(|byte| *byte == b'\n');
                let payload_bytes = newline.unwrap_or(available.len());
                if !oversized && frame.len().saturating_add(payload_bytes) > self.max_frame_bytes {
                    oversized = true;
                }
                if !oversized {
                    frame.extend_from_slice(&available[..payload_bytes]);
                }
                (newline.map_or(payload_bytes, |index| index + 1), newline.is_some())
            };
            reader.consume(consumed);
            if complete {
                if oversized {
                    return Err(inbound_error(None, JSON_RPC_INVALID_REQUEST, format!("JSON line frame exceeds {} bytes", self.max_frame_bytes)));
                }
                if frame.ends_with(b"\r") {
                    frame.pop();
                }
                return self.decode_line(&frame).map(Some);
            }
        }
    }

    pub fn write_message<W: Write>(&self, writer: &mut W, message: &ProviderWireMessage) -> Result<(), ProtocolError> {
        let frame = self.encode_message(message)?;
        writer.write_all(&frame).map_err(|error| ProtocolError {
            code: "json_line_write_failed".to_string(),
            message: format!("write JSON line frame: {error}"),
            retryable: true,
            details: None,
        })
    }
}

impl Default for JsonLineCodec {
    fn default() -> Self {
        Self { max_frame_bytes: DEFAULT_MAX_JSON_LINE_BYTES }
    }
}
