// @generated by tools/protocol-codegen/generate.mjs from protocol/channel/lan/v1/manifest.json and protocol/channel/lan/v1/schema.json.
// DO NOT EDIT MANUALLY.

use serde::{Deserialize, Serialize};


pub use codepet_core_sdk::{ClientId, DeviceDescriptor, DeviceId, TimestampMs};

pub const CHANNEL_LAN_SCHEMA_VERSION: u64 = 1;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct CurrentCredentialDeleteResponse {
    pub revoked: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct LanHostIdentity {
    pub device_id: DeviceId,
    pub descriptor: DeviceDescriptor,
    pub identity_fingerprint: String,
}

#[derive(Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PairingExchangeRequest {
    pub pairing_secret: String,
    pub client_id: ClientId,
    pub device: DeviceDescriptor,
}

impl std::fmt::Debug for PairingExchangeRequest {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("PairingExchangeRequest")
            .field("pairing_secret", &"<redacted>")
            .field("client_id", &self.client_id)
            .field("device", &self.device)
            .finish()
    }
}

#[derive(Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PairingExchangeResponse {
    pub device: LanHostIdentity,
    pub gateway_url: String,
    pub credential: String,
}

impl std::fmt::Debug for PairingExchangeResponse {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("PairingExchangeResponse")
            .field("device", &self.device)
            .field("gateway_url", &self.gateway_url)
            .field("credential", &"<redacted>")
            .finish()
    }
}

#[derive(Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PairingQrPayload {
    pub version: u64,
    pub host_device_id: DeviceId,
    pub display_name: String,
    pub https_base_url: String,
    pub cert_sha256: String,
    pub pairing_id: String,
    pub pairing_secret: String,
    pub expires_at: TimestampMs,
}

impl std::fmt::Debug for PairingQrPayload {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("PairingQrPayload")
            .field("version", &self.version)
            .field("host_device_id", &self.host_device_id)
            .field("display_name", &self.display_name)
            .field("https_base_url", &self.https_base_url)
            .field("cert_sha256", &self.cert_sha256)
            .field("pairing_id", &self.pairing_id)
            .field("pairing_secret", &"<redacted>")
            .field("expires_at", &self.expires_at)
            .finish()
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PairingRequestCreateRequest {
    pub host_device_id: DeviceId,
    pub client_id: ClientId,
    pub device: DeviceDescriptor,
    pub client_nonce: String,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum PairingRequestState {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PairingRequestStatusResponse {
    pub request_id: String,
    pub state: PairingRequestState,
    pub device: LanHostIdentity,
    pub expires_at: TimestampMs,
    pub confirmation_code: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gateway_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub credential: Option<String>,
}

impl std::fmt::Debug for PairingRequestStatusResponse {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("PairingRequestStatusResponse")
            .field("request_id", &self.request_id)
            .field("state", &self.state)
            .field("device", &self.device)
            .field("expires_at", &self.expires_at)
            .field("confirmation_code", &self.confirmation_code)
            .field("gateway_url", &self.gateway_url)
            .field("credential", &"<redacted>")
            .finish()
    }
}
