// @generated by tools/protocol-codegen/generate.mjs from protocol/core/v1/manifest.json and protocol/core/v1/schema.json.
// DO NOT EDIT MANUALLY.

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export type ClientId = string;

export type Cursor = string;

export type DeviceId = string;

export type EventCursor = string;

export type EventSequence = number;

export type JsonObject = Record<string, JsonValue>;

export type NativeResourceId = string;

export interface PageInfo {
  nextCursor?: Cursor;
}

export interface PageRequest {
  cursor?: Cursor;
  limit?: number;
}

export interface ProtocolError {
  code: string;
  message: string;
  retryable: boolean;
  details?: JsonObject;
}

export type ProtocolVersion = number;

export type ProviderInstanceId = string;

export type ProviderPluginId = string;

export type RequestId = string;

export interface RoutedResourceId {
  deviceId: DeviceId;
  providerInstanceId: ProviderInstanceId;
  nativeResourceId: NativeResourceId;
}

export interface RpcError {
  code: number;
  message: string;
  data?: JsonObject;
}

export type TimestampMs = number;

export interface VersionRange {
  minVersion: ProtocolVersion;
  maxVersion: ProtocolVersion;
}
