// @generated by tools/protocol-codegen/generate.mjs from protocol/provider/v1/manifest.json and protocol/provider/v1/schema.json.
// DO NOT EDIT MANUALLY.

use serde::{Deserialize, Serialize};
use std::future::Future;
use std::pin::Pin;

pub use codepet_core_sdk::{ClientId, Cursor, DeviceId, JsonObject, NativeResourceId, PageInfo, ProtocolError, ProtocolVersion, ProviderInstanceId, ProviderPluginId, RequestId, RoutedResourceId, RpcError, TimestampMs, VersionRange};

pub const PROTOCOL_VERSION: ProtocolVersion = 1;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ApprovalDecision {
    #[serde(rename = "approve")]
    Approve,
    #[serde(rename = "deny")]
    Deny,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ApprovalRequestedEvent {
    pub approval: ProviderApproval,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ApprovalResolveRequest {
    pub approval: RoutedResourceId,
    pub decision: ApprovalDecision,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ApprovalResolveResponse {
    pub approval: ProviderApproval,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ApprovalResolvedEvent {
    pub approval: ProviderApproval,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ApprovalStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "denied")]
    Denied,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationCreateRequest {
    pub route: ProviderInstanceRoute,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    pub permission_level: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_effort: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workspace_root: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extension: Option<ProviderExtension>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationCreateResponse {
    pub conversation: ProviderConversation,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationGetRequest {
    pub conversation: RoutedResourceId,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationGetResponse {
    pub conversation: ProviderConversation,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationListRequest {
    pub route: ProviderInstanceRoute,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<Cursor>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<u64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationListResponse {
    pub conversations: Vec<ProviderConversation>,
    pub page_info: PageInfo,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConversationStatus {
    #[serde(rename = "idle")]
    Idle,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "waiting-approval")]
    WaitingApproval,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "archived")]
    Archived,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationUpsertedEvent {
    pub conversation: ProviderConversation,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceCapabilitiesRequest {
    pub route: ProviderInstanceRoute,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceCapabilitiesResponse {
    pub capabilities: ProviderCapabilities,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceCreateRequest {
    pub route: ProviderInstanceRoute,
    pub display_name: String,
    pub settings: JsonObject,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceCreateResponse {
    pub instance: ProviderInstance,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceDestroyRequest {
    pub route: ProviderInstanceRoute,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceDestroyResponse {
    pub destroyed: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceStartRequest {
    pub route: ProviderInstanceRoute,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceStartResponse {
    pub instance: ProviderInstance,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum InstanceStatus {
    #[serde(rename = "created")]
    Created,
    #[serde(rename = "starting")]
    Starting,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "stopping")]
    Stopping,
    #[serde(rename = "stopped")]
    Stopped,
    #[serde(rename = "error")]
    Error,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceStatusChangedEvent {
    pub instance: ProviderInstance,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub previous_status: Option<InstanceStatus>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceStopRequest {
    pub route: ProviderInstanceRoute,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceStopResponse {
    pub instance: ProviderInstance,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderApproval {
    pub resource: RoutedResourceId,
    pub conversation: RoutedResourceId,
    pub turn: RoutedResourceId,
    pub kind: String,
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub status: ApprovalStatus,
    pub decisions: Vec<ApprovalDecision>,
    pub requested_at: TimestampMs,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resolved_at: Option<TimestampMs>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<ApprovalDecision>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extension: Option<ProviderExtension>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderCapabilities {
    pub methods: Vec<String>,
    pub permission_levels: Vec<String>,
    pub models: Vec<String>,
    pub reasoning_efforts: Vec<String>,
    pub extensions: Vec<ProviderExtension>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderConversation {
    pub resource: RoutedResourceId,
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preview: Option<String>,
    pub status: ConversationStatus,
    pub permission_level: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_effort: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workspace_root: Option<String>,
    pub created_at: TimestampMs,
    pub updated_at: TimestampMs,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active_turn: Option<ProviderTurn>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extension: Option<ProviderExtension>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderDescribeRequest {

}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderDescribeResponse {
    pub plugin: ProviderPluginDescriptor,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderExtension {
    pub namespace: String,
    pub data: JsonObject,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderInitializeRequest {
    pub host_client_id: ClientId,
    pub host_device_id: DeviceId,
    pub host_version: String,
    pub supported_versions: VersionRange,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderInitializeResponse {
    pub selected_version: ProtocolVersion,
    pub plugin: ProviderPluginDescriptor,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderInstance {
    pub route: ProviderInstanceRoute,
    pub plugin_id: ProviderPluginId,
    pub display_name: String,
    pub status: InstanceStatus,
    pub capabilities: ProviderCapabilities,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderInstanceRoute {
    pub device_id: DeviceId,
    pub provider_instance_id: ProviderInstanceId,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderPluginDescriptor {
    pub plugin_id: ProviderPluginId,
    pub display_name: String,
    pub version: String,
    pub supported_versions: VersionRange,
    pub instance_kinds: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderShutdownRequest {

}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderShutdownResponse {
    pub accepted: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderTurn {
    pub resource: RoutedResourceId,
    pub conversation: RoutedResourceId,
    pub status: TurnStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub display_summary: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub started_at: Option<TimestampMs>,
    pub updated_at: TimestampMs,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<TimestampMs>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extension: Option<ProviderExtension>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnInterruptRequest {
    pub turn: RoutedResourceId,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnInterruptResponse {
    pub turn: ProviderTurn,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnOutputDeltaEvent {
    pub turn: RoutedResourceId,
    pub output_id: NativeResourceId,
    pub kind: String,
    pub delta: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extension: Option<ProviderExtension>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnStartRequest {
    pub conversation: RoutedResourceId,
    pub client_message_id: RequestId,
    pub message: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnStartResponse {
    pub turn: ProviderTurn,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum TurnStatus {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "waiting-approval")]
    WaitingApproval,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "interrupted")]
    Interrupted,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnSteerRequest {
    pub turn: RoutedResourceId,
    pub client_message_id: RequestId,
    pub message: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnSteerResponse {
    pub turn: ProviderTurn,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnUpsertedEvent {
    pub turn: ProviderTurn,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProtocolMethod {
    #[serde(rename = "provider.initialize")]
    ProviderInitialize,
    #[serde(rename = "provider.describe")]
    ProviderDescribe,
    #[serde(rename = "instance.create")]
    InstanceCreate,
    #[serde(rename = "instance.start")]
    InstanceStart,
    #[serde(rename = "instance.stop")]
    InstanceStop,
    #[serde(rename = "instance.destroy")]
    InstanceDestroy,
    #[serde(rename = "instance.capabilities")]
    InstanceCapabilities,
    #[serde(rename = "conversation.list")]
    ConversationList,
    #[serde(rename = "conversation.get")]
    ConversationGet,
    #[serde(rename = "conversation.create")]
    ConversationCreate,
    #[serde(rename = "turn.start")]
    TurnStart,
    #[serde(rename = "turn.steer")]
    TurnSteer,
    #[serde(rename = "turn.interrupt")]
    TurnInterrupt,
    #[serde(rename = "approval.resolve")]
    ApprovalResolve,
    #[serde(rename = "provider.shutdown")]
    ProviderShutdown,
}

impl ProtocolMethod {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ProviderInitialize => "provider.initialize",
            Self::ProviderDescribe => "provider.describe",
            Self::InstanceCreate => "instance.create",
            Self::InstanceStart => "instance.start",
            Self::InstanceStop => "instance.stop",
            Self::InstanceDestroy => "instance.destroy",
            Self::InstanceCapabilities => "instance.capabilities",
            Self::ConversationList => "conversation.list",
            Self::ConversationGet => "conversation.get",
            Self::ConversationCreate => "conversation.create",
            Self::TurnStart => "turn.start",
            Self::TurnSteer => "turn.steer",
            Self::TurnInterrupt => "turn.interrupt",
            Self::ApprovalResolve => "approval.resolve",
            Self::ProviderShutdown => "provider.shutdown",
        }
    }
}

impl std::str::FromStr for ProtocolMethod {
    type Err = ();

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "provider.initialize" => Ok(Self::ProviderInitialize),
            "provider.describe" => Ok(Self::ProviderDescribe),
            "instance.create" => Ok(Self::InstanceCreate),
            "instance.start" => Ok(Self::InstanceStart),
            "instance.stop" => Ok(Self::InstanceStop),
            "instance.destroy" => Ok(Self::InstanceDestroy),
            "instance.capabilities" => Ok(Self::InstanceCapabilities),
            "conversation.list" => Ok(Self::ConversationList),
            "conversation.get" => Ok(Self::ConversationGet),
            "conversation.create" => Ok(Self::ConversationCreate),
            "turn.start" => Ok(Self::TurnStart),
            "turn.steer" => Ok(Self::TurnSteer),
            "turn.interrupt" => Ok(Self::TurnInterrupt),
            "approval.resolve" => Ok(Self::ApprovalResolve),
            "provider.shutdown" => Ok(Self::ProviderShutdown),
            _ => Err(()),
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProtocolEventName {
    #[serde(rename = "event.instanceStatusChanged")]
    EventInstanceStatusChanged,
    #[serde(rename = "event.conversationUpserted")]
    EventConversationUpserted,
    #[serde(rename = "event.turnUpserted")]
    EventTurnUpserted,
    #[serde(rename = "event.turnOutputDelta")]
    EventTurnOutputDelta,
    #[serde(rename = "event.approvalRequested")]
    EventApprovalRequested,
    #[serde(rename = "event.approvalResolved")]
    EventApprovalResolved,
}

impl ProtocolEventName {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::EventInstanceStatusChanged => "event.instanceStatusChanged",
            Self::EventConversationUpserted => "event.conversationUpserted",
            Self::EventTurnUpserted => "event.turnUpserted",
            Self::EventTurnOutputDelta => "event.turnOutputDelta",
            Self::EventApprovalRequested => "event.approvalRequested",
            Self::EventApprovalResolved => "event.approvalResolved",
        }
    }
}

impl std::str::FromStr for ProtocolEventName {
    type Err = ();

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "event.instanceStatusChanged" => Ok(Self::EventInstanceStatusChanged),
            "event.conversationUpserted" => Ok(Self::EventConversationUpserted),
            "event.turnUpserted" => Ok(Self::EventTurnUpserted),
            "event.turnOutputDelta" => Ok(Self::EventTurnOutputDelta),
            "event.approvalRequested" => Ok(Self::EventApprovalRequested),
            "event.approvalResolved" => Ok(Self::EventApprovalResolved),
            _ => Err(()),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "method")]
pub enum ProtocolRequest {
    #[serde(rename = "provider.initialize")]
    ProviderInitialize {
        jsonrpc: String,
        id: RequestId,
        params: ProviderInitializeRequest,
    },
    #[serde(rename = "provider.describe")]
    ProviderDescribe {
        jsonrpc: String,
        id: RequestId,
        params: ProviderDescribeRequest,
    },
    #[serde(rename = "instance.create")]
    InstanceCreate {
        jsonrpc: String,
        id: RequestId,
        params: InstanceCreateRequest,
    },
    #[serde(rename = "instance.start")]
    InstanceStart {
        jsonrpc: String,
        id: RequestId,
        params: InstanceStartRequest,
    },
    #[serde(rename = "instance.stop")]
    InstanceStop {
        jsonrpc: String,
        id: RequestId,
        params: InstanceStopRequest,
    },
    #[serde(rename = "instance.destroy")]
    InstanceDestroy {
        jsonrpc: String,
        id: RequestId,
        params: InstanceDestroyRequest,
    },
    #[serde(rename = "instance.capabilities")]
    InstanceCapabilities {
        jsonrpc: String,
        id: RequestId,
        params: InstanceCapabilitiesRequest,
    },
    #[serde(rename = "conversation.list")]
    ConversationList {
        jsonrpc: String,
        id: RequestId,
        params: ConversationListRequest,
    },
    #[serde(rename = "conversation.get")]
    ConversationGet {
        jsonrpc: String,
        id: RequestId,
        params: ConversationGetRequest,
    },
    #[serde(rename = "conversation.create")]
    ConversationCreate {
        jsonrpc: String,
        id: RequestId,
        params: ConversationCreateRequest,
    },
    #[serde(rename = "turn.start")]
    TurnStart {
        jsonrpc: String,
        id: RequestId,
        params: TurnStartRequest,
    },
    #[serde(rename = "turn.steer")]
    TurnSteer {
        jsonrpc: String,
        id: RequestId,
        params: TurnSteerRequest,
    },
    #[serde(rename = "turn.interrupt")]
    TurnInterrupt {
        jsonrpc: String,
        id: RequestId,
        params: TurnInterruptRequest,
    },
    #[serde(rename = "approval.resolve")]
    ApprovalResolve {
        jsonrpc: String,
        id: RequestId,
        params: ApprovalResolveRequest,
    },
    #[serde(rename = "provider.shutdown")]
    ProviderShutdown {
        jsonrpc: String,
        id: RequestId,
        params: ProviderShutdownRequest,
    },
}

impl ProtocolRequest {
    pub fn jsonrpc_version(&self) -> &str {
        match self {
            Self::ProviderInitialize { jsonrpc, .. } => jsonrpc,
            Self::ProviderDescribe { jsonrpc, .. } => jsonrpc,
            Self::InstanceCreate { jsonrpc, .. } => jsonrpc,
            Self::InstanceStart { jsonrpc, .. } => jsonrpc,
            Self::InstanceStop { jsonrpc, .. } => jsonrpc,
            Self::InstanceDestroy { jsonrpc, .. } => jsonrpc,
            Self::InstanceCapabilities { jsonrpc, .. } => jsonrpc,
            Self::ConversationList { jsonrpc, .. } => jsonrpc,
            Self::ConversationGet { jsonrpc, .. } => jsonrpc,
            Self::ConversationCreate { jsonrpc, .. } => jsonrpc,
            Self::TurnStart { jsonrpc, .. } => jsonrpc,
            Self::TurnSteer { jsonrpc, .. } => jsonrpc,
            Self::TurnInterrupt { jsonrpc, .. } => jsonrpc,
            Self::ApprovalResolve { jsonrpc, .. } => jsonrpc,
            Self::ProviderShutdown { jsonrpc, .. } => jsonrpc,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "method")]
pub enum ProtocolEvent {
    #[serde(rename = "event.instanceStatusChanged")]
    EventInstanceStatusChanged {
        jsonrpc: String,
        params: InstanceStatusChangedEvent,
    },
    #[serde(rename = "event.conversationUpserted")]
    EventConversationUpserted {
        jsonrpc: String,
        params: ConversationUpsertedEvent,
    },
    #[serde(rename = "event.turnUpserted")]
    EventTurnUpserted {
        jsonrpc: String,
        params: TurnUpsertedEvent,
    },
    #[serde(rename = "event.turnOutputDelta")]
    EventTurnOutputDelta {
        jsonrpc: String,
        params: TurnOutputDeltaEvent,
    },
    #[serde(rename = "event.approvalRequested")]
    EventApprovalRequested {
        jsonrpc: String,
        params: ApprovalRequestedEvent,
    },
    #[serde(rename = "event.approvalResolved")]
    EventApprovalResolved {
        jsonrpc: String,
        params: ApprovalResolvedEvent,
    },
}

impl ProtocolEvent {
    pub fn jsonrpc_version(&self) -> &str {
        match self {
            Self::EventInstanceStatusChanged { jsonrpc, .. } => jsonrpc,
            Self::EventConversationUpserted { jsonrpc, .. } => jsonrpc,
            Self::EventTurnUpserted { jsonrpc, .. } => jsonrpc,
            Self::EventTurnOutputDelta { jsonrpc, .. } => jsonrpc,
            Self::EventApprovalRequested { jsonrpc, .. } => jsonrpc,
            Self::EventApprovalResolved { jsonrpc, .. } => jsonrpc,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JsonRpcResponsePayload {
    Ok { result: serde_json::Value },
    Error { error: RpcError },
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsonRpcResponse {
    pub jsonrpc: String,
    pub id: RequestId,
    #[serde(flatten)]
    pub response: JsonRpcResponsePayload,
}

pub type ProtocolFuture<'a, T> = Pin<Box<dyn Future<Output = Result<T, ProtocolError>> + Send + 'a>>;

pub trait ProtocolServer: Send + Sync {
    fn provider_initialize<'a>(&'a self, _request: ProviderInitializeRequest) -> ProtocolFuture<'a, ProviderInitializeResponse> {
        Box::pin(async { Err(method_not_implemented("provider.initialize")) })
    }

    fn provider_describe<'a>(&'a self, _request: ProviderDescribeRequest) -> ProtocolFuture<'a, ProviderDescribeResponse> {
        Box::pin(async { Err(method_not_implemented("provider.describe")) })
    }

    fn instance_create<'a>(&'a self, _request: InstanceCreateRequest) -> ProtocolFuture<'a, InstanceCreateResponse> {
        Box::pin(async { Err(method_not_implemented("instance.create")) })
    }

    fn instance_start<'a>(&'a self, _request: InstanceStartRequest) -> ProtocolFuture<'a, InstanceStartResponse> {
        Box::pin(async { Err(method_not_implemented("instance.start")) })
    }

    fn instance_stop<'a>(&'a self, _request: InstanceStopRequest) -> ProtocolFuture<'a, InstanceStopResponse> {
        Box::pin(async { Err(method_not_implemented("instance.stop")) })
    }

    fn instance_destroy<'a>(&'a self, _request: InstanceDestroyRequest) -> ProtocolFuture<'a, InstanceDestroyResponse> {
        Box::pin(async { Err(method_not_implemented("instance.destroy")) })
    }

    fn instance_capabilities<'a>(&'a self, _request: InstanceCapabilitiesRequest) -> ProtocolFuture<'a, InstanceCapabilitiesResponse> {
        Box::pin(async { Err(method_not_implemented("instance.capabilities")) })
    }

    fn conversation_list<'a>(&'a self, _request: ConversationListRequest) -> ProtocolFuture<'a, ConversationListResponse> {
        Box::pin(async { Err(method_not_implemented("conversation.list")) })
    }

    fn conversation_get<'a>(&'a self, _request: ConversationGetRequest) -> ProtocolFuture<'a, ConversationGetResponse> {
        Box::pin(async { Err(method_not_implemented("conversation.get")) })
    }

    fn conversation_create<'a>(&'a self, _request: ConversationCreateRequest) -> ProtocolFuture<'a, ConversationCreateResponse> {
        Box::pin(async { Err(method_not_implemented("conversation.create")) })
    }

    fn turn_start<'a>(&'a self, _request: TurnStartRequest) -> ProtocolFuture<'a, TurnStartResponse> {
        Box::pin(async { Err(method_not_implemented("turn.start")) })
    }

    fn turn_steer<'a>(&'a self, _request: TurnSteerRequest) -> ProtocolFuture<'a, TurnSteerResponse> {
        Box::pin(async { Err(method_not_implemented("turn.steer")) })
    }

    fn turn_interrupt<'a>(&'a self, _request: TurnInterruptRequest) -> ProtocolFuture<'a, TurnInterruptResponse> {
        Box::pin(async { Err(method_not_implemented("turn.interrupt")) })
    }

    fn approval_resolve<'a>(&'a self, _request: ApprovalResolveRequest) -> ProtocolFuture<'a, ApprovalResolveResponse> {
        Box::pin(async { Err(method_not_implemented("approval.resolve")) })
    }

    fn provider_shutdown<'a>(&'a self, _request: ProviderShutdownRequest) -> ProtocolFuture<'a, ProviderShutdownResponse> {
        Box::pin(async { Err(method_not_implemented("provider.shutdown")) })
    }
}

fn method_not_implemented(method: &str) -> ProtocolError {
    ProtocolError {
        code: "method_not_implemented".to_string(),
        message: format!("protocol method is not implemented: {method}"),
        retryable: false,
        details: None,
    }
}

pub async fn dispatch<S: ProtocolServer + ?Sized>(server: &S, request: ProtocolRequest) -> JsonRpcResponse {
    match request {
        ProtocolRequest::ProviderInitialize { jsonrpc, id, params } => {
            let response = match server.provider_initialize(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id, response }
        },
        ProtocolRequest::ProviderDescribe { jsonrpc, id, params } => {
            let response = match server.provider_describe(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id, response }
        },
        ProtocolRequest::InstanceCreate { jsonrpc, id, params } => {
            let response = match server.instance_create(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id, response }
        },
        ProtocolRequest::InstanceStart { jsonrpc, id, params } => {
            let response = match server.instance_start(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id, response }
        },
        ProtocolRequest::InstanceStop { jsonrpc, id, params } => {
            let response = match server.instance_stop(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id, response }
        },
        ProtocolRequest::InstanceDestroy { jsonrpc, id, params } => {
            let response = match server.instance_destroy(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id, response }
        },
        ProtocolRequest::InstanceCapabilities { jsonrpc, id, params } => {
            let response = match server.instance_capabilities(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id, response }
        },
        ProtocolRequest::ConversationList { jsonrpc, id, params } => {
            let response = match server.conversation_list(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id, response }
        },
        ProtocolRequest::ConversationGet { jsonrpc, id, params } => {
            let response = match server.conversation_get(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id, response }
        },
        ProtocolRequest::ConversationCreate { jsonrpc, id, params } => {
            let response = match server.conversation_create(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id, response }
        },
        ProtocolRequest::TurnStart { jsonrpc, id, params } => {
            let response = match server.turn_start(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id, response }
        },
        ProtocolRequest::TurnSteer { jsonrpc, id, params } => {
            let response = match server.turn_steer(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id, response }
        },
        ProtocolRequest::TurnInterrupt { jsonrpc, id, params } => {
            let response = match server.turn_interrupt(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id, response }
        },
        ProtocolRequest::ApprovalResolve { jsonrpc, id, params } => {
            let response = match server.approval_resolve(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id, response }
        },
        ProtocolRequest::ProviderShutdown { jsonrpc, id, params } => {
            let response = match server.provider_shutdown(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id, response }
        }
    }
}

pub struct ProtocolDispatcher<S> {
    server: S,
}

impl<S> ProtocolDispatcher<S> {
    pub const fn new(server: S) -> Self {
        Self { server }
    }

    pub const fn server(&self) -> &S {
        &self.server
    }
}

impl<S: ProtocolServer> ProtocolDispatcher<S> {
    pub async fn dispatch(&self, request: ProtocolRequest) -> JsonRpcResponse {
        dispatch(&self.server, request).await
    }
}

pub type ProtocolTransportFuture<'a> = Pin<Box<dyn Future<Output = Result<serde_json::Value, ProtocolError>> + Send + 'a>>;

pub trait ProtocolTransport: Send + Sync {
    fn request<'a>(&'a self, method: ProtocolMethod, params: serde_json::Value) -> ProtocolTransportFuture<'a>;
}

pub struct ProtocolClient<T> {
    transport: T,
}

impl<T> ProtocolClient<T> {
    pub const fn new(transport: T) -> Self {
        Self { transport }
    }

    pub const fn transport(&self) -> &T {
        &self.transport
    }
}

impl<T: ProtocolTransport> ProtocolClient<T> {
    pub fn provider_initialize<'a>(&'a self, request: ProviderInitializeRequest) -> ProtocolFuture<'a, ProviderInitializeResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ProviderInitialize, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn provider_describe<'a>(&'a self, request: ProviderDescribeRequest) -> ProtocolFuture<'a, ProviderDescribeResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ProviderDescribe, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn instance_create<'a>(&'a self, request: InstanceCreateRequest) -> ProtocolFuture<'a, InstanceCreateResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::InstanceCreate, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn instance_start<'a>(&'a self, request: InstanceStartRequest) -> ProtocolFuture<'a, InstanceStartResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::InstanceStart, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn instance_stop<'a>(&'a self, request: InstanceStopRequest) -> ProtocolFuture<'a, InstanceStopResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::InstanceStop, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn instance_destroy<'a>(&'a self, request: InstanceDestroyRequest) -> ProtocolFuture<'a, InstanceDestroyResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::InstanceDestroy, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn instance_capabilities<'a>(&'a self, request: InstanceCapabilitiesRequest) -> ProtocolFuture<'a, InstanceCapabilitiesResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::InstanceCapabilities, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn conversation_list<'a>(&'a self, request: ConversationListRequest) -> ProtocolFuture<'a, ConversationListResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ConversationList, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn conversation_get<'a>(&'a self, request: ConversationGetRequest) -> ProtocolFuture<'a, ConversationGetResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ConversationGet, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn conversation_create<'a>(&'a self, request: ConversationCreateRequest) -> ProtocolFuture<'a, ConversationCreateResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ConversationCreate, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn turn_start<'a>(&'a self, request: TurnStartRequest) -> ProtocolFuture<'a, TurnStartResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::TurnStart, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn turn_steer<'a>(&'a self, request: TurnSteerRequest) -> ProtocolFuture<'a, TurnSteerResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::TurnSteer, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn turn_interrupt<'a>(&'a self, request: TurnInterruptRequest) -> ProtocolFuture<'a, TurnInterruptResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::TurnInterrupt, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn approval_resolve<'a>(&'a self, request: ApprovalResolveRequest) -> ProtocolFuture<'a, ApprovalResolveResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ApprovalResolve, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn provider_shutdown<'a>(&'a self, request: ProviderShutdownRequest) -> ProtocolFuture<'a, ProviderShutdownResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ProviderShutdown, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }
}

fn codec_error(context: &str, error: serde_json::Error) -> ProtocolError {
    ProtocolError {
        code: "protocol_codec_error".to_string(),
        message: format!("{context}: {error}"),
        retryable: false,
        details: None,
    }
}

fn rpc_method_error(error: ProtocolError) -> RpcError {
    let message = error.message.clone();
    let data = serde_json::to_value(error).ok().and_then(|value| match value {
        serde_json::Value::Object(entries) => Some(entries.into_iter().collect()),
        _ => None,
    });
    RpcError { code: -32000, message, data }
}

fn rpc_codec_error(context: &str, error: serde_json::Error) -> RpcError {
    RpcError { code: -32603, message: format!("{context}: {error}"), data: None }
}

fn validate_jsonrpc(version: &str) -> Result<(), ProtocolError> {
    if version == "2.0" {
        return Ok(());
    }
    Err(ProtocolError {
        code: "unsupported_jsonrpc_version".to_string(),
        message: format!("unsupported JSON-RPC version: {version}"),
        retryable: false,
        details: None,
    })
}

pub fn encode_request(value: &ProtocolRequest) -> Result<Vec<u8>, ProtocolError> {
    validate_jsonrpc(value.jsonrpc_version())?;
    serde_json::to_vec(value).map_err(|error| codec_error("encode request", error))
}

pub fn decode_request(value: &[u8]) -> Result<ProtocolRequest, ProtocolError> {
    let request: ProtocolRequest = serde_json::from_slice(value).map_err(|error| codec_error("decode request", error))?;
    validate_jsonrpc(request.jsonrpc_version())?;
    Ok(request)
}

pub fn encode_response(value: &JsonRpcResponse) -> Result<Vec<u8>, ProtocolError> {
    validate_jsonrpc(&value.jsonrpc)?;
    serde_json::to_vec(value).map_err(|error| codec_error("encode response", error))
}

pub fn decode_response(value: &[u8]) -> Result<JsonRpcResponse, ProtocolError> {
    let response: JsonRpcResponse = serde_json::from_slice(value).map_err(|error| codec_error("decode response", error))?;
    validate_jsonrpc(&response.jsonrpc)?;
    Ok(response)
}

pub fn encode_event(value: &ProtocolEvent) -> Result<Vec<u8>, ProtocolError> {
    validate_jsonrpc(value.jsonrpc_version())?;
    serde_json::to_vec(value).map_err(|error| codec_error("encode event", error))
}

pub fn decode_event(value: &[u8]) -> Result<ProtocolEvent, ProtocolError> {
    let event: ProtocolEvent = serde_json::from_slice(value).map_err(|error| codec_error("decode event", error))?;
    validate_jsonrpc(event.jsonrpc_version())?;
    Ok(event)
}
