// @generated by tools/protocol-codegen/generate.mjs from protocol/provider/v1/manifest.json and protocol/provider/v1/schema.json.
// DO NOT EDIT MANUALLY.

use serde::{Deserialize, Serialize};
use std::io::{BufRead, Write};
use std::future::Future;
use std::pin::Pin;

pub use codepet_core_sdk::{ClientId, Cursor, DeviceId, JsonObject, NativeResourceId, PageInfo, ProtocolError, ProtocolVersion, ProviderInstanceId, ProviderPluginId, RequestId, RoutedResourceId, RpcError, TimestampMs, VersionRange};

pub const PROTOCOL_VERSION: ProtocolVersion = 1;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ApprovalDecision {
    #[serde(rename = "approve")]
    Approve,
    #[serde(rename = "deny")]
    Deny,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ApprovalRequestedEvent {
    pub approval: ProviderApproval,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ApprovalResolveRequest {
    pub approval: RoutedResourceId,
    pub decision: ApprovalDecision,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ApprovalResolveResponse {
    pub approval: ProviderApproval,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ApprovalResolvedEvent {
    pub approval: ProviderApproval,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ApprovalStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "denied")]
    Denied,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ChoiceOption {
    pub id: String,
    pub display_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disabled_reason: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ChoiceSet {
    pub options: Vec<ChoiceOption>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_id: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationAcquireInteractionRequest {
    pub conversation: RoutedResourceId,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationAcquireInteractionResponse {
    pub selection: TurnSelection,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lease_expires_at: Option<TimestampMs>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationContent {
    pub content_id: NativeResourceId,
    pub kind: ConversationContentKind,
    pub text: String,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConversationContentKind {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "reasoning-summary")]
    ReasoningSummary,
    #[serde(rename = "command")]
    Command,
    #[serde(rename = "output")]
    Output,
    #[serde(rename = "activity-summary")]
    ActivitySummary,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationCreateCapabilities {
    pub supports_title: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub selection: Option<TurnSendCapabilities>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workspace_mode: Option<ChoiceSet>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationCreateRequest {
    pub route: ProviderInstanceRoute,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    pub permission_level: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_effort: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workspace_root: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workspace_mode: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extension: Option<ProviderExtension>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationCreateResponse {
    pub conversation: ProviderConversation,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationGetRequest {
    pub conversation: RoutedResourceId,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<Cursor>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<u64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationGetResponse {
    pub conversation: ProviderConversation,
    pub items: Vec<ConversationItem>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page_info: Option<PageInfo>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationItem {
    pub resource: RoutedResourceId,
    pub turn: RoutedResourceId,
    pub conversation: RoutedResourceId,
    pub kind: ConversationItemKind,
    pub status: ConversationItemStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub role: Option<ConversationItemRole>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    pub contents: Vec<ConversationContent>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub related_item: Option<RoutedResourceId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub approval: Option<ProviderApproval>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool: Option<ToolInvocation>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConversationItemKind {
    #[serde(rename = "message")]
    Message,
    #[serde(rename = "reasoning")]
    Reasoning,
    #[serde(rename = "command")]
    Command,
    #[serde(rename = "file-change")]
    FileChange,
    #[serde(rename = "tool")]
    Tool,
    #[serde(rename = "approval")]
    Approval,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConversationItemRole {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "assistant")]
    Assistant,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConversationItemStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "interrupted")]
    Interrupted,
    #[serde(rename = "declined")]
    Declined,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "denied")]
    Denied,
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationItemUpsertedEvent {
    pub item: ConversationItem,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationListRequest {
    pub route: ProviderInstanceRoute,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<Cursor>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<u64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationListResponse {
    pub conversations: Vec<ProviderConversation>,
    pub page_info: PageInfo,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationSearchRequest {
    pub route: ProviderInstanceRoute,
    pub search_term: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<Cursor>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<u64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationSearchResponse {
    pub conversations: Vec<ProviderConversation>,
    pub page_info: PageInfo,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConversationStatus {
    #[serde(rename = "idle")]
    Idle,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "waiting-approval")]
    WaitingApproval,
    #[serde(rename = "waiting-user-input")]
    WaitingUserInput,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "archived")]
    Archived,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationUpsertedEvent {
    pub conversation: ProviderConversation,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct FlatModelCatalog {
    pub kind: FlatModelCatalogKind,
    pub models: Vec<ChoiceOption>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_selection: Option<FlatModelSelection>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum FlatModelCatalogKind {
    #[serde(rename = "flat")]
    Flat,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct FlatModelSelection {
    pub kind: FlatModelCatalogKind,
    pub model_id: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct GroupedModelCatalog {
    pub kind: GroupedModelCatalogKind,
    pub providers: Vec<GroupedModelProvider>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default_selection: Option<GroupedModelSelection>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum GroupedModelCatalogKind {
    #[serde(rename = "grouped")]
    Grouped,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct GroupedModelProvider {
    pub id: String,
    pub display_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub models: Vec<ChoiceOption>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct GroupedModelSelection {
    pub kind: GroupedModelCatalogKind,
    pub provider_id: String,
    pub model_id: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct HarnessDescriptor {
    pub id: String,
    pub display_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceCapabilitiesRequest {
    pub route: ProviderInstanceRoute,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceCapabilitiesResponse {
    pub capabilities: ProviderCapabilities,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceCreateRequest {
    pub route: ProviderInstanceRoute,
    pub instance_kind: ProviderInstanceKind,
    pub display_name: String,
    pub settings: JsonObject,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceCreateResponse {
    pub instance: ProviderInstance,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceDestroyRequest {
    pub route: ProviderInstanceRoute,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceDestroyResponse {
    pub destroyed: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceStartRequest {
    pub route: ProviderInstanceRoute,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceStartResponse {
    pub instance: ProviderInstance,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum InstanceStatus {
    #[serde(rename = "created")]
    Created,
    #[serde(rename = "starting")]
    Starting,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "stopping")]
    Stopping,
    #[serde(rename = "stopped")]
    Stopped,
    #[serde(rename = "error")]
    Error,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceStatusChangedEvent {
    pub instance: ProviderInstance,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub previous_status: Option<InstanceStatus>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceStopRequest {
    pub route: ProviderInstanceRoute,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct InstanceStopResponse {
    pub instance: ProviderInstance,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ModelCatalog {
    FlatModelCatalog(FlatModelCatalog),
    GroupedModelCatalog(GroupedModelCatalog),
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ModelSelection {
    FlatModelSelection(FlatModelSelection),
    GroupedModelSelection(GroupedModelSelection),
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderApproval {
    pub resource: RoutedResourceId,
    pub conversation: RoutedResourceId,
    pub turn: RoutedResourceId,
    pub kind: String,
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub status: ApprovalStatus,
    pub decisions: Vec<ApprovalDecision>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub requested_at: Option<TimestampMs>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resolved_at: Option<TimestampMs>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<ApprovalDecision>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extension: Option<ProviderExtension>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderCapabilities {
    pub revision: String,
    pub methods: Vec<ProviderCapability>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub turn_send: Option<TurnSendCapabilities>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub conversation_create: Option<ConversationCreateCapabilities>,
    pub extensions: Vec<ProviderExtension>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProviderCapability {
    #[serde(rename = "conversation.list")]
    ConversationList,
    #[serde(rename = "conversation.search")]
    ConversationSearch,
    #[serde(rename = "conversation.get")]
    ConversationGet,
    #[serde(rename = "conversation.create")]
    ConversationCreate,
    #[serde(rename = "turn.start")]
    TurnStart,
    #[serde(rename = "turn.steer")]
    TurnSteer,
    #[serde(rename = "turn.interrupt")]
    TurnInterrupt,
    #[serde(rename = "approval.resolve")]
    ApprovalResolve,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderConversation {
    pub resource: RoutedResourceId,
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preview: Option<String>,
    pub status: ConversationStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub permission_level: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_effort: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub selection: Option<TurnSelection>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workspace_root: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<TimestampMs>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<TimestampMs>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active_turn: Option<ProviderTurn>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extension: Option<ProviderExtension>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderDescribeRequest {

}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderDescribeResponse {
    pub plugin: ProviderPluginDescriptor,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderExtension {
    pub namespace: String,
    pub data: JsonObject,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderInitializeRequest {
    pub host_client_id: ClientId,
    pub host_device_id: DeviceId,
    pub host_version: String,
    pub supported_versions: VersionRange,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderInitializeResponse {
    pub selected_version: ProtocolVersion,
    pub plugin: ProviderPluginDescriptor,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderInstance {
    pub route: ProviderInstanceRoute,
    pub plugin_id: ProviderPluginId,
    pub instance_kind: ProviderInstanceKind,
    pub display_name: String,
    pub harness: HarnessDescriptor,
    pub status: InstanceStatus,
    pub capabilities: ProviderCapabilities,
}

pub type ProviderInstanceKind = String;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderInstanceRoute {
    pub device_id: DeviceId,
    pub provider_plugin_id: ProviderPluginId,
    pub provider_instance_id: ProviderInstanceId,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderPluginDescriptor {
    pub plugin_id: ProviderPluginId,
    pub display_name: String,
    pub version: String,
    pub supported_versions: VersionRange,
    pub instance_kinds: Vec<ProviderInstanceKind>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderShutdownRequest {

}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderShutdownResponse {
    pub accepted: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderTurn {
    pub resource: RoutedResourceId,
    pub conversation: RoutedResourceId,
    pub status: TurnStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub display_summary: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub started_at: Option<TimestampMs>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<TimestampMs>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<TimestampMs>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extension: Option<ProviderExtension>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ToolAnnotations {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub destructive: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub idempotent: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub open_world: Option<bool>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ToolCategory {
    #[serde(rename = "command")]
    Command,
    #[serde(rename = "read")]
    Read,
    #[serde(rename = "write")]
    Write,
    #[serde(rename = "search")]
    Search,
    #[serde(rename = "web")]
    Web,
    #[serde(rename = "agent")]
    Agent,
    #[serde(rename = "computer")]
    Computer,
    #[serde(rename = "media")]
    Media,
    #[serde(rename = "other")]
    Other,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ToolCommandAction {
    pub kind: ToolCommandActionKind,
    pub command: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ToolCommandActionKind {
    #[serde(rename = "execute")]
    Execute,
    #[serde(rename = "read")]
    Read,
    #[serde(rename = "list")]
    List,
    #[serde(rename = "search")]
    Search,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ToolCommandDetails {
    pub command: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cwd: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub process_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actions: Option<Vec<ToolCommandAction>>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ToolContent {
    pub content_id: NativeResourceId,
    pub kind: ToolContentKind,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub truncated: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total_bytes: Option<u64>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ToolContentKind {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "image")]
    Image,
    #[serde(rename = "audio")]
    Audio,
    #[serde(rename = "resource-link")]
    ResourceLink,
    #[serde(rename = "embedded-resource")]
    EmbeddedResource,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ToolExecutionError {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub retryable: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<JsonObject>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ToolInvocation {
    pub call_id: NativeResourceId,
    pub name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    pub category: ToolCategory,
    pub origin: ToolOrigin,
    pub input: JsonObject,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub raw_input: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub result: Option<ToolResult>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timing: Option<ToolTiming>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub command: Option<ToolCommandDetails>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub annotations: Option<ToolAnnotations>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extension: Option<ProviderExtension>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ToolOrigin {
    pub kind: ToolOriginKind,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ToolOriginKind {
    #[serde(rename = "builtin")]
    Builtin,
    #[serde(rename = "mcp")]
    Mcp,
    #[serde(rename = "plugin")]
    Plugin,
    #[serde(rename = "server")]
    Server,
    #[serde(rename = "custom")]
    Custom,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ToolResult {
    pub content: Vec<ToolContent>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub structured_content: Option<JsonObject>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<ToolExecutionError>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ToolTiming {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub started_at: Option<TimestampMs>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<TimestampMs>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<u64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnInput {
    pub kind: TurnInputKind,
    pub text: String,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum TurnInputKind {
    #[serde(rename = "text")]
    Text,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnInterruptRequest {
    pub conversation: RoutedResourceId,
    pub turn: RoutedResourceId,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnInterruptResponse {
    pub turn: ProviderTurn,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnOutputDeltaEvent {
    pub turn: RoutedResourceId,
    pub conversation: RoutedResourceId,
    pub item_id: NativeResourceId,
    pub content_id: NativeResourceId,
    pub kind: ConversationContentKind,
    pub delta: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extension: Option<ProviderExtension>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnSelection {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub access_mode_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_effort_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<ModelSelection>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnSendCapabilities {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub access_mode: Option<ChoiceSet>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_effort: Option<ChoiceSet>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model_catalog: Option<ModelCatalog>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnStartRequest {
    pub conversation: RoutedResourceId,
    pub client_request_id: RequestId,
    pub capability_revision: String,
    pub input: TurnInput,
    pub selection: TurnSelection,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnStartResponse {
    pub accepted: bool,
    pub turn: ProviderTurn,
    pub user_item: Option<ConversationItem>,
    pub effective_selection: TurnSelection,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum TurnStatus {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "waiting-approval")]
    WaitingApproval,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "interrupted")]
    Interrupted,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnSteerRequest {
    pub conversation: RoutedResourceId,
    pub turn: RoutedResourceId,
    pub client_message_id: RequestId,
    pub message: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnSteerResponse {
    pub turn: ProviderTurn,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnUpsertedEvent {
    pub turn: ProviderTurn,
}

impl ProviderPluginDescriptor {
    pub fn validate_instance_kinds(&self) -> Result<(), ProtocolError> {
        if self.instance_kinds.is_empty() {
            return Err(ProtocolError {
                code: "invalid_provider_descriptor".to_string(),
                message: "provider descriptor must declare at least one instance kind".to_string(),
                retryable: false,
                details: None,
            });
        }
        for (index, instance_kind) in self.instance_kinds.iter().enumerate() {
            if instance_kind.is_empty() {
                return Err(ProtocolError {
                    code: "invalid_provider_descriptor".to_string(),
                    message: "provider descriptor instance kinds must be non-empty".to_string(),
                    retryable: false,
                    details: None,
                });
            }
            if self.instance_kinds[..index].contains(instance_kind) {
                return Err(ProtocolError {
                    code: "invalid_provider_descriptor".to_string(),
                    message: format!("provider descriptor contains duplicate instance kind: {instance_kind}"),
                    retryable: false,
                    details: None,
                });
            }
        }
        Ok(())
    }

    pub fn supports_instance_kind(&self, instance_kind: &str) -> bool {
        self.instance_kinds.iter().any(|supported| supported == instance_kind)
    }

    pub fn validate_instance_kind(&self, instance_kind: &str) -> Result<(), ProtocolError> {
        self.validate_instance_kinds()?;
        if self.supports_instance_kind(instance_kind) {
            return Ok(());
        }
        Err(ProtocolError {
            code: "unsupported_instance_kind".to_string(),
            message: format!("provider does not support instance kind: {instance_kind}"),
            retryable: false,
            details: None,
        })
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProtocolDispatchLane {
    Normal,
    Control,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProtocolMethod {
    #[serde(rename = "provider.initialize")]
    ProviderInitialize,
    #[serde(rename = "provider.describe")]
    ProviderDescribe,
    #[serde(rename = "instance.create")]
    InstanceCreate,
    #[serde(rename = "instance.start")]
    InstanceStart,
    #[serde(rename = "instance.stop")]
    InstanceStop,
    #[serde(rename = "instance.destroy")]
    InstanceDestroy,
    #[serde(rename = "instance.capabilities")]
    InstanceCapabilities,
    #[serde(rename = "conversation.list")]
    ConversationList,
    #[serde(rename = "conversation.search")]
    ConversationSearch,
    #[serde(rename = "conversation.get")]
    ConversationGet,
    #[serde(rename = "conversation.acquireInteraction")]
    ConversationAcquireInteraction,
    #[serde(rename = "conversation.create")]
    ConversationCreate,
    #[serde(rename = "turn.start")]
    TurnStart,
    #[serde(rename = "turn.steer")]
    TurnSteer,
    #[serde(rename = "turn.interrupt")]
    TurnInterrupt,
    #[serde(rename = "approval.resolve")]
    ApprovalResolve,
    #[serde(rename = "provider.shutdown")]
    ProviderShutdown,
}

impl ProtocolMethod {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ProviderInitialize => "provider.initialize",
            Self::ProviderDescribe => "provider.describe",
            Self::InstanceCreate => "instance.create",
            Self::InstanceStart => "instance.start",
            Self::InstanceStop => "instance.stop",
            Self::InstanceDestroy => "instance.destroy",
            Self::InstanceCapabilities => "instance.capabilities",
            Self::ConversationList => "conversation.list",
            Self::ConversationSearch => "conversation.search",
            Self::ConversationGet => "conversation.get",
            Self::ConversationAcquireInteraction => "conversation.acquireInteraction",
            Self::ConversationCreate => "conversation.create",
            Self::TurnStart => "turn.start",
            Self::TurnSteer => "turn.steer",
            Self::TurnInterrupt => "turn.interrupt",
            Self::ApprovalResolve => "approval.resolve",
            Self::ProviderShutdown => "provider.shutdown",
        }
    }

    pub const fn dispatch_lane(self) -> ProtocolDispatchLane {
        match self {
            Self::ProviderInitialize => ProtocolDispatchLane::Normal,
            Self::ProviderDescribe => ProtocolDispatchLane::Normal,
            Self::InstanceCreate => ProtocolDispatchLane::Normal,
            Self::InstanceStart => ProtocolDispatchLane::Normal,
            Self::InstanceStop => ProtocolDispatchLane::Control,
            Self::InstanceDestroy => ProtocolDispatchLane::Control,
            Self::InstanceCapabilities => ProtocolDispatchLane::Normal,
            Self::ConversationList => ProtocolDispatchLane::Normal,
            Self::ConversationSearch => ProtocolDispatchLane::Normal,
            Self::ConversationGet => ProtocolDispatchLane::Normal,
            Self::ConversationAcquireInteraction => ProtocolDispatchLane::Normal,
            Self::ConversationCreate => ProtocolDispatchLane::Normal,
            Self::TurnStart => ProtocolDispatchLane::Normal,
            Self::TurnSteer => ProtocolDispatchLane::Normal,
            Self::TurnInterrupt => ProtocolDispatchLane::Normal,
            Self::ApprovalResolve => ProtocolDispatchLane::Normal,
            Self::ProviderShutdown => ProtocolDispatchLane::Control,
        }
    }

    pub const fn capability(self) -> Option<ProviderCapability> {
        match self {
            Self::ProviderInitialize => None,
            Self::ProviderDescribe => None,
            Self::InstanceCreate => None,
            Self::InstanceStart => None,
            Self::InstanceStop => None,
            Self::InstanceDestroy => None,
            Self::InstanceCapabilities => None,
            Self::ConversationList => Some(ProviderCapability::ConversationList),
            Self::ConversationSearch => Some(ProviderCapability::ConversationSearch),
            Self::ConversationGet => Some(ProviderCapability::ConversationGet),
            Self::ConversationAcquireInteraction => None,
            Self::ConversationCreate => Some(ProviderCapability::ConversationCreate),
            Self::TurnStart => Some(ProviderCapability::TurnStart),
            Self::TurnSteer => Some(ProviderCapability::TurnSteer),
            Self::TurnInterrupt => Some(ProviderCapability::TurnInterrupt),
            Self::ApprovalResolve => Some(ProviderCapability::ApprovalResolve),
            Self::ProviderShutdown => None,
        }
    }
}

impl std::str::FromStr for ProtocolMethod {
    type Err = ();

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "provider.initialize" => Ok(Self::ProviderInitialize),
            "provider.describe" => Ok(Self::ProviderDescribe),
            "instance.create" => Ok(Self::InstanceCreate),
            "instance.start" => Ok(Self::InstanceStart),
            "instance.stop" => Ok(Self::InstanceStop),
            "instance.destroy" => Ok(Self::InstanceDestroy),
            "instance.capabilities" => Ok(Self::InstanceCapabilities),
            "conversation.list" => Ok(Self::ConversationList),
            "conversation.search" => Ok(Self::ConversationSearch),
            "conversation.get" => Ok(Self::ConversationGet),
            "conversation.acquireInteraction" => Ok(Self::ConversationAcquireInteraction),
            "conversation.create" => Ok(Self::ConversationCreate),
            "turn.start" => Ok(Self::TurnStart),
            "turn.steer" => Ok(Self::TurnSteer),
            "turn.interrupt" => Ok(Self::TurnInterrupt),
            "approval.resolve" => Ok(Self::ApprovalResolve),
            "provider.shutdown" => Ok(Self::ProviderShutdown),
            _ => Err(()),
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProtocolEventName {
    #[serde(rename = "event.instanceStatusChanged")]
    EventInstanceStatusChanged,
    #[serde(rename = "event.conversationUpserted")]
    EventConversationUpserted,
    #[serde(rename = "event.conversationItemUpserted")]
    EventConversationItemUpserted,
    #[serde(rename = "event.turnUpserted")]
    EventTurnUpserted,
    #[serde(rename = "event.turnOutputDelta")]
    EventTurnOutputDelta,
    #[serde(rename = "event.approvalRequested")]
    EventApprovalRequested,
    #[serde(rename = "event.approvalResolved")]
    EventApprovalResolved,
}

impl ProtocolEventName {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::EventInstanceStatusChanged => "event.instanceStatusChanged",
            Self::EventConversationUpserted => "event.conversationUpserted",
            Self::EventConversationItemUpserted => "event.conversationItemUpserted",
            Self::EventTurnUpserted => "event.turnUpserted",
            Self::EventTurnOutputDelta => "event.turnOutputDelta",
            Self::EventApprovalRequested => "event.approvalRequested",
            Self::EventApprovalResolved => "event.approvalResolved",
        }
    }
}

impl std::str::FromStr for ProtocolEventName {
    type Err = ();

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "event.instanceStatusChanged" => Ok(Self::EventInstanceStatusChanged),
            "event.conversationUpserted" => Ok(Self::EventConversationUpserted),
            "event.conversationItemUpserted" => Ok(Self::EventConversationItemUpserted),
            "event.turnUpserted" => Ok(Self::EventTurnUpserted),
            "event.turnOutputDelta" => Ok(Self::EventTurnOutputDelta),
            "event.approvalRequested" => Ok(Self::EventApprovalRequested),
            "event.approvalResolved" => Ok(Self::EventApprovalResolved),
            _ => Err(()),
        }
    }
}

pub const JSON_RPC_PARSE_ERROR: i64 = -32700;
pub const JSON_RPC_INVALID_REQUEST: i64 = -32600;
pub const JSON_RPC_METHOD_NOT_FOUND: i64 = -32601;
pub const JSON_RPC_INVALID_PARAMS: i64 = -32602;
pub const JSON_RPC_INTERNAL_ERROR: i64 = -32603;
pub const DEFAULT_MAX_JSON_LINE_BYTES: usize = 1024 * 1024;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "method")]
pub enum ProtocolRequest {
    #[serde(rename = "provider.initialize")]
    ProviderInitialize {
        jsonrpc: String,
        id: RequestId,
        params: ProviderInitializeRequest,
    },
    #[serde(rename = "provider.describe")]
    ProviderDescribe {
        jsonrpc: String,
        id: RequestId,
        params: ProviderDescribeRequest,
    },
    #[serde(rename = "instance.create")]
    InstanceCreate {
        jsonrpc: String,
        id: RequestId,
        params: InstanceCreateRequest,
    },
    #[serde(rename = "instance.start")]
    InstanceStart {
        jsonrpc: String,
        id: RequestId,
        params: InstanceStartRequest,
    },
    #[serde(rename = "instance.stop")]
    InstanceStop {
        jsonrpc: String,
        id: RequestId,
        params: InstanceStopRequest,
    },
    #[serde(rename = "instance.destroy")]
    InstanceDestroy {
        jsonrpc: String,
        id: RequestId,
        params: InstanceDestroyRequest,
    },
    #[serde(rename = "instance.capabilities")]
    InstanceCapabilities {
        jsonrpc: String,
        id: RequestId,
        params: InstanceCapabilitiesRequest,
    },
    #[serde(rename = "conversation.list")]
    ConversationList {
        jsonrpc: String,
        id: RequestId,
        params: ConversationListRequest,
    },
    #[serde(rename = "conversation.search")]
    ConversationSearch {
        jsonrpc: String,
        id: RequestId,
        params: ConversationSearchRequest,
    },
    #[serde(rename = "conversation.get")]
    ConversationGet {
        jsonrpc: String,
        id: RequestId,
        params: ConversationGetRequest,
    },
    #[serde(rename = "conversation.acquireInteraction")]
    ConversationAcquireInteraction {
        jsonrpc: String,
        id: RequestId,
        params: ConversationAcquireInteractionRequest,
    },
    #[serde(rename = "conversation.create")]
    ConversationCreate {
        jsonrpc: String,
        id: RequestId,
        params: ConversationCreateRequest,
    },
    #[serde(rename = "turn.start")]
    TurnStart {
        jsonrpc: String,
        id: RequestId,
        params: TurnStartRequest,
    },
    #[serde(rename = "turn.steer")]
    TurnSteer {
        jsonrpc: String,
        id: RequestId,
        params: TurnSteerRequest,
    },
    #[serde(rename = "turn.interrupt")]
    TurnInterrupt {
        jsonrpc: String,
        id: RequestId,
        params: TurnInterruptRequest,
    },
    #[serde(rename = "approval.resolve")]
    ApprovalResolve {
        jsonrpc: String,
        id: RequestId,
        params: ApprovalResolveRequest,
    },
    #[serde(rename = "provider.shutdown")]
    ProviderShutdown {
        jsonrpc: String,
        id: RequestId,
        params: ProviderShutdownRequest,
    },
}

impl ProtocolRequest {
    pub fn from_method_params(
        method: ProtocolMethod,
        id: RequestId,
        params: serde_json::Value,
    ) -> Result<Self, ProtocolError> {
        let jsonrpc = "2.0".to_string();
        match method {
            ProtocolMethod::ProviderInitialize => Ok(Self::ProviderInitialize {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode provider.initialize request params", error))?,
            }),
            ProtocolMethod::ProviderDescribe => Ok(Self::ProviderDescribe {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode provider.describe request params", error))?,
            }),
            ProtocolMethod::InstanceCreate => Ok(Self::InstanceCreate {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode instance.create request params", error))?,
            }),
            ProtocolMethod::InstanceStart => Ok(Self::InstanceStart {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode instance.start request params", error))?,
            }),
            ProtocolMethod::InstanceStop => Ok(Self::InstanceStop {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode instance.stop request params", error))?,
            }),
            ProtocolMethod::InstanceDestroy => Ok(Self::InstanceDestroy {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode instance.destroy request params", error))?,
            }),
            ProtocolMethod::InstanceCapabilities => Ok(Self::InstanceCapabilities {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode instance.capabilities request params", error))?,
            }),
            ProtocolMethod::ConversationList => Ok(Self::ConversationList {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode conversation.list request params", error))?,
            }),
            ProtocolMethod::ConversationSearch => Ok(Self::ConversationSearch {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode conversation.search request params", error))?,
            }),
            ProtocolMethod::ConversationGet => Ok(Self::ConversationGet {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode conversation.get request params", error))?,
            }),
            ProtocolMethod::ConversationAcquireInteraction => Ok(Self::ConversationAcquireInteraction {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode conversation.acquireInteraction request params", error))?,
            }),
            ProtocolMethod::ConversationCreate => Ok(Self::ConversationCreate {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode conversation.create request params", error))?,
            }),
            ProtocolMethod::TurnStart => Ok(Self::TurnStart {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode turn.start request params", error))?,
            }),
            ProtocolMethod::TurnSteer => Ok(Self::TurnSteer {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode turn.steer request params", error))?,
            }),
            ProtocolMethod::TurnInterrupt => Ok(Self::TurnInterrupt {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode turn.interrupt request params", error))?,
            }),
            ProtocolMethod::ApprovalResolve => Ok(Self::ApprovalResolve {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode approval.resolve request params", error))?,
            }),
            ProtocolMethod::ProviderShutdown => Ok(Self::ProviderShutdown {
                jsonrpc,
                id,
                params: serde_json::from_value(params).map_err(|error| codec_error("decode provider.shutdown request params", error))?,
            }),
        }
    }

    pub fn jsonrpc_version(&self) -> &str {
        match self {
            Self::ProviderInitialize { jsonrpc, .. } => jsonrpc,
            Self::ProviderDescribe { jsonrpc, .. } => jsonrpc,
            Self::InstanceCreate { jsonrpc, .. } => jsonrpc,
            Self::InstanceStart { jsonrpc, .. } => jsonrpc,
            Self::InstanceStop { jsonrpc, .. } => jsonrpc,
            Self::InstanceDestroy { jsonrpc, .. } => jsonrpc,
            Self::InstanceCapabilities { jsonrpc, .. } => jsonrpc,
            Self::ConversationList { jsonrpc, .. } => jsonrpc,
            Self::ConversationSearch { jsonrpc, .. } => jsonrpc,
            Self::ConversationGet { jsonrpc, .. } => jsonrpc,
            Self::ConversationAcquireInteraction { jsonrpc, .. } => jsonrpc,
            Self::ConversationCreate { jsonrpc, .. } => jsonrpc,
            Self::TurnStart { jsonrpc, .. } => jsonrpc,
            Self::TurnSteer { jsonrpc, .. } => jsonrpc,
            Self::TurnInterrupt { jsonrpc, .. } => jsonrpc,
            Self::ApprovalResolve { jsonrpc, .. } => jsonrpc,
            Self::ProviderShutdown { jsonrpc, .. } => jsonrpc,
        }
    }

    pub fn id(&self) -> &RequestId {
        match self {
            Self::ProviderInitialize { id, .. } => id,
            Self::ProviderDescribe { id, .. } => id,
            Self::InstanceCreate { id, .. } => id,
            Self::InstanceStart { id, .. } => id,
            Self::InstanceStop { id, .. } => id,
            Self::InstanceDestroy { id, .. } => id,
            Self::InstanceCapabilities { id, .. } => id,
            Self::ConversationList { id, .. } => id,
            Self::ConversationSearch { id, .. } => id,
            Self::ConversationGet { id, .. } => id,
            Self::ConversationAcquireInteraction { id, .. } => id,
            Self::ConversationCreate { id, .. } => id,
            Self::TurnStart { id, .. } => id,
            Self::TurnSteer { id, .. } => id,
            Self::TurnInterrupt { id, .. } => id,
            Self::ApprovalResolve { id, .. } => id,
            Self::ProviderShutdown { id, .. } => id,
        }
    }

    pub const fn method(&self) -> ProtocolMethod {
        match self {
            Self::ProviderInitialize { .. } => ProtocolMethod::ProviderInitialize,
            Self::ProviderDescribe { .. } => ProtocolMethod::ProviderDescribe,
            Self::InstanceCreate { .. } => ProtocolMethod::InstanceCreate,
            Self::InstanceStart { .. } => ProtocolMethod::InstanceStart,
            Self::InstanceStop { .. } => ProtocolMethod::InstanceStop,
            Self::InstanceDestroy { .. } => ProtocolMethod::InstanceDestroy,
            Self::InstanceCapabilities { .. } => ProtocolMethod::InstanceCapabilities,
            Self::ConversationList { .. } => ProtocolMethod::ConversationList,
            Self::ConversationSearch { .. } => ProtocolMethod::ConversationSearch,
            Self::ConversationGet { .. } => ProtocolMethod::ConversationGet,
            Self::ConversationAcquireInteraction { .. } => ProtocolMethod::ConversationAcquireInteraction,
            Self::ConversationCreate { .. } => ProtocolMethod::ConversationCreate,
            Self::TurnStart { .. } => ProtocolMethod::TurnStart,
            Self::TurnSteer { .. } => ProtocolMethod::TurnSteer,
            Self::TurnInterrupt { .. } => ProtocolMethod::TurnInterrupt,
            Self::ApprovalResolve { .. } => ProtocolMethod::ApprovalResolve,
            Self::ProviderShutdown { .. } => ProtocolMethod::ProviderShutdown,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "method")]
pub enum ProtocolEvent {
    #[serde(rename = "event.instanceStatusChanged")]
    EventInstanceStatusChanged {
        jsonrpc: String,
        params: InstanceStatusChangedEvent,
    },
    #[serde(rename = "event.conversationUpserted")]
    EventConversationUpserted {
        jsonrpc: String,
        params: ConversationUpsertedEvent,
    },
    #[serde(rename = "event.conversationItemUpserted")]
    EventConversationItemUpserted {
        jsonrpc: String,
        params: ConversationItemUpsertedEvent,
    },
    #[serde(rename = "event.turnUpserted")]
    EventTurnUpserted {
        jsonrpc: String,
        params: TurnUpsertedEvent,
    },
    #[serde(rename = "event.turnOutputDelta")]
    EventTurnOutputDelta {
        jsonrpc: String,
        params: TurnOutputDeltaEvent,
    },
    #[serde(rename = "event.approvalRequested")]
    EventApprovalRequested {
        jsonrpc: String,
        params: ApprovalRequestedEvent,
    },
    #[serde(rename = "event.approvalResolved")]
    EventApprovalResolved {
        jsonrpc: String,
        params: ApprovalResolvedEvent,
    },
}

impl ProtocolEvent {
    pub fn jsonrpc_version(&self) -> &str {
        match self {
            Self::EventInstanceStatusChanged { jsonrpc, .. } => jsonrpc,
            Self::EventConversationUpserted { jsonrpc, .. } => jsonrpc,
            Self::EventConversationItemUpserted { jsonrpc, .. } => jsonrpc,
            Self::EventTurnUpserted { jsonrpc, .. } => jsonrpc,
            Self::EventTurnOutputDelta { jsonrpc, .. } => jsonrpc,
            Self::EventApprovalRequested { jsonrpc, .. } => jsonrpc,
            Self::EventApprovalResolved { jsonrpc, .. } => jsonrpc,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JsonRpcResponsePayload {
    Ok { result: serde_json::Value },
    Error { error: RpcError },
}

#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct JsonRpcResponse {
    pub jsonrpc: String,
    pub id: Option<RequestId>,
    #[serde(flatten)]
    pub response: JsonRpcResponsePayload,
}

impl<'de> Deserialize<'de> for JsonRpcResponse {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = serde_json::Value::deserialize(deserializer)?;
        parse_jsonrpc_response(value).map_err(|error| serde::de::Error::custom(error.to_string()))
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JsonRpcNotification {
    pub jsonrpc: String,
    pub method: String,
    #[serde(default, skip_serializing_if = "serde_json::Value::is_null")]
    pub params: serde_json::Value,
}

#[derive(Clone, Debug, PartialEq)]
pub struct JsonRpcRequestRejection {
    pub id: RequestId,
    pub method: String,
    pub error: RpcError,
}

impl JsonRpcRequestRejection {
    pub fn into_response(self) -> JsonRpcResponse {
        JsonRpcResponse {
            jsonrpc: "2.0".to_string(),
            id: Some(self.id),
            response: JsonRpcResponsePayload::Error { error: self.error },
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum JsonRpcInboundRequest {
    Typed(ProtocolRequest),
    Rejected(JsonRpcRequestRejection),
}

#[derive(Clone, Debug, PartialEq)]
pub enum ProviderWireMessage {
    Request(JsonRpcInboundRequest),
    Response(JsonRpcResponse),
    Notification(JsonRpcNotification),
    Event(ProtocolEvent),
}

#[derive(Clone, Debug, PartialEq)]
pub struct JsonRpcInboundError {
    pub id: Option<RequestId>,
    pub error: RpcError,
}

impl JsonRpcInboundError {
    pub fn into_response(self) -> JsonRpcResponse {
        JsonRpcResponse {
            jsonrpc: "2.0".to_string(),
            id: self.id,
            response: JsonRpcResponsePayload::Error { error: self.error },
        }
    }
}

impl std::fmt::Display for JsonRpcInboundError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(formatter, "JSON-RPC error {}: {}", self.error.code, self.error.message)
    }
}

impl std::error::Error for JsonRpcInboundError {}

pub type ProtocolFuture<'a, T> = Pin<Box<dyn Future<Output = Result<T, ProtocolError>> + Send + 'a>>;

pub trait ProtocolServer: Send + Sync {
    fn provider_initialize<'a>(&'a self, _request: ProviderInitializeRequest) -> ProtocolFuture<'a, ProviderInitializeResponse> {
        Box::pin(async { Err(method_not_implemented("provider.initialize")) })
    }

    fn provider_describe<'a>(&'a self, _request: ProviderDescribeRequest) -> ProtocolFuture<'a, ProviderDescribeResponse> {
        Box::pin(async { Err(method_not_implemented("provider.describe")) })
    }

    fn instance_create<'a>(&'a self, _request: InstanceCreateRequest) -> ProtocolFuture<'a, InstanceCreateResponse> {
        Box::pin(async { Err(method_not_implemented("instance.create")) })
    }

    fn instance_start<'a>(&'a self, _request: InstanceStartRequest) -> ProtocolFuture<'a, InstanceStartResponse> {
        Box::pin(async { Err(method_not_implemented("instance.start")) })
    }

    fn instance_stop<'a>(&'a self, _request: InstanceStopRequest) -> ProtocolFuture<'a, InstanceStopResponse> {
        Box::pin(async { Err(method_not_implemented("instance.stop")) })
    }

    fn instance_destroy<'a>(&'a self, _request: InstanceDestroyRequest) -> ProtocolFuture<'a, InstanceDestroyResponse> {
        Box::pin(async { Err(method_not_implemented("instance.destroy")) })
    }

    fn instance_capabilities<'a>(&'a self, _request: InstanceCapabilitiesRequest) -> ProtocolFuture<'a, InstanceCapabilitiesResponse> {
        Box::pin(async { Err(method_not_implemented("instance.capabilities")) })
    }

    fn conversation_list<'a>(&'a self, _request: ConversationListRequest) -> ProtocolFuture<'a, ConversationListResponse> {
        Box::pin(async { Err(method_not_implemented("conversation.list")) })
    }

    fn conversation_search<'a>(&'a self, _request: ConversationSearchRequest) -> ProtocolFuture<'a, ConversationSearchResponse> {
        Box::pin(async { Err(method_not_implemented("conversation.search")) })
    }

    fn conversation_get<'a>(&'a self, _request: ConversationGetRequest) -> ProtocolFuture<'a, ConversationGetResponse> {
        Box::pin(async { Err(method_not_implemented("conversation.get")) })
    }

    fn conversation_acquire_interaction<'a>(&'a self, _request: ConversationAcquireInteractionRequest) -> ProtocolFuture<'a, ConversationAcquireInteractionResponse> {
        Box::pin(async { Err(method_not_implemented("conversation.acquireInteraction")) })
    }

    fn conversation_create<'a>(&'a self, _request: ConversationCreateRequest) -> ProtocolFuture<'a, ConversationCreateResponse> {
        Box::pin(async { Err(method_not_implemented("conversation.create")) })
    }

    fn turn_start<'a>(&'a self, _request: TurnStartRequest) -> ProtocolFuture<'a, TurnStartResponse> {
        Box::pin(async { Err(method_not_implemented("turn.start")) })
    }

    fn turn_steer<'a>(&'a self, _request: TurnSteerRequest) -> ProtocolFuture<'a, TurnSteerResponse> {
        Box::pin(async { Err(method_not_implemented("turn.steer")) })
    }

    fn turn_interrupt<'a>(&'a self, _request: TurnInterruptRequest) -> ProtocolFuture<'a, TurnInterruptResponse> {
        Box::pin(async { Err(method_not_implemented("turn.interrupt")) })
    }

    fn approval_resolve<'a>(&'a self, _request: ApprovalResolveRequest) -> ProtocolFuture<'a, ApprovalResolveResponse> {
        Box::pin(async { Err(method_not_implemented("approval.resolve")) })
    }

    fn provider_shutdown<'a>(&'a self, _request: ProviderShutdownRequest) -> ProtocolFuture<'a, ProviderShutdownResponse> {
        Box::pin(async { Err(method_not_implemented("provider.shutdown")) })
    }
}

fn method_not_implemented(method: &str) -> ProtocolError {
    ProtocolError {
        code: "method_not_implemented".to_string(),
        message: format!("protocol method is not implemented: {method}"),
        retryable: false,
        details: None,
    }
}

pub async fn dispatch<S: ProtocolServer + ?Sized>(server: &S, request: ProtocolRequest) -> JsonRpcResponse {
    match request {
        ProtocolRequest::ProviderInitialize { jsonrpc, id, params } => {
            let response = match server.provider_initialize(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::ProviderDescribe { jsonrpc, id, params } => {
            let response = match server.provider_describe(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::InstanceCreate { jsonrpc, id, params } => {
            let response = match server.instance_create(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::InstanceStart { jsonrpc, id, params } => {
            let response = match server.instance_start(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::InstanceStop { jsonrpc, id, params } => {
            let response = match server.instance_stop(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::InstanceDestroy { jsonrpc, id, params } => {
            let response = match server.instance_destroy(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::InstanceCapabilities { jsonrpc, id, params } => {
            let response = match server.instance_capabilities(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::ConversationList { jsonrpc, id, params } => {
            let response = match server.conversation_list(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::ConversationSearch { jsonrpc, id, params } => {
            let response = match server.conversation_search(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::ConversationGet { jsonrpc, id, params } => {
            let response = match server.conversation_get(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::ConversationAcquireInteraction { jsonrpc, id, params } => {
            let response = match server.conversation_acquire_interaction(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::ConversationCreate { jsonrpc, id, params } => {
            let response = match server.conversation_create(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::TurnStart { jsonrpc, id, params } => {
            let response = match server.turn_start(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::TurnSteer { jsonrpc, id, params } => {
            let response = match server.turn_steer(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::TurnInterrupt { jsonrpc, id, params } => {
            let response = match server.turn_interrupt(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::ApprovalResolve { jsonrpc, id, params } => {
            let response = match server.approval_resolve(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        },
        ProtocolRequest::ProviderShutdown { jsonrpc, id, params } => {
            let response = match server.provider_shutdown(params).await {
                Ok(result) => match serde_json::to_value(result) {
                    Ok(result) => JsonRpcResponsePayload::Ok { result },
                    Err(error) => JsonRpcResponsePayload::Error { error: rpc_codec_error("encode response result", error) },
                },
                Err(error) => JsonRpcResponsePayload::Error { error: rpc_method_error(error) },
            };
            JsonRpcResponse { jsonrpc, id: Some(id), response }
        }
    }
}

pub struct ProtocolDispatcher<S> {
    server: S,
}

impl<S> ProtocolDispatcher<S> {
    pub const fn new(server: S) -> Self {
        Self { server }
    }

    pub const fn server(&self) -> &S {
        &self.server
    }
}

impl<S: ProtocolServer> ProtocolDispatcher<S> {
    pub async fn dispatch(&self, request: ProtocolRequest) -> JsonRpcResponse {
        dispatch(&self.server, request).await
    }
}

pub type ProtocolTransportFuture<'a> = Pin<Box<dyn Future<Output = Result<serde_json::Value, ProtocolError>> + Send + 'a>>;

pub type ProtocolInboundFuture<'a> = Pin<Box<dyn Future<Output = Result<ProviderWireMessage, JsonRpcInboundError>> + Send + 'a>>;

pub trait ProtocolTransport: Send + Sync {
    fn request<'a>(&'a self, method: ProtocolMethod, params: serde_json::Value) -> ProtocolTransportFuture<'a>;
    fn next_message<'a>(&'a self) -> ProtocolInboundFuture<'a>;
}

pub struct ProtocolClient<T> {
    transport: T,
}

impl<T> ProtocolClient<T> {
    pub const fn new(transport: T) -> Self {
        Self { transport }
    }

    pub const fn transport(&self) -> &T {
        &self.transport
    }
}

impl<T: ProtocolTransport> ProtocolClient<T> {
    pub fn provider_initialize<'a>(&'a self, request: ProviderInitializeRequest) -> ProtocolFuture<'a, ProviderInitializeResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ProviderInitialize, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn provider_describe<'a>(&'a self, request: ProviderDescribeRequest) -> ProtocolFuture<'a, ProviderDescribeResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ProviderDescribe, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn instance_create<'a>(&'a self, request: InstanceCreateRequest) -> ProtocolFuture<'a, InstanceCreateResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::InstanceCreate, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn instance_start<'a>(&'a self, request: InstanceStartRequest) -> ProtocolFuture<'a, InstanceStartResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::InstanceStart, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn instance_stop<'a>(&'a self, request: InstanceStopRequest) -> ProtocolFuture<'a, InstanceStopResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::InstanceStop, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn instance_destroy<'a>(&'a self, request: InstanceDestroyRequest) -> ProtocolFuture<'a, InstanceDestroyResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::InstanceDestroy, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn instance_capabilities<'a>(&'a self, request: InstanceCapabilitiesRequest) -> ProtocolFuture<'a, InstanceCapabilitiesResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::InstanceCapabilities, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn conversation_list<'a>(&'a self, request: ConversationListRequest) -> ProtocolFuture<'a, ConversationListResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ConversationList, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn conversation_search<'a>(&'a self, request: ConversationSearchRequest) -> ProtocolFuture<'a, ConversationSearchResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ConversationSearch, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn conversation_get<'a>(&'a self, request: ConversationGetRequest) -> ProtocolFuture<'a, ConversationGetResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ConversationGet, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn conversation_acquire_interaction<'a>(&'a self, request: ConversationAcquireInteractionRequest) -> ProtocolFuture<'a, ConversationAcquireInteractionResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ConversationAcquireInteraction, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn conversation_create<'a>(&'a self, request: ConversationCreateRequest) -> ProtocolFuture<'a, ConversationCreateResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ConversationCreate, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn turn_start<'a>(&'a self, request: TurnStartRequest) -> ProtocolFuture<'a, TurnStartResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::TurnStart, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn turn_steer<'a>(&'a self, request: TurnSteerRequest) -> ProtocolFuture<'a, TurnSteerResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::TurnSteer, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn turn_interrupt<'a>(&'a self, request: TurnInterruptRequest) -> ProtocolFuture<'a, TurnInterruptResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::TurnInterrupt, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn approval_resolve<'a>(&'a self, request: ApprovalResolveRequest) -> ProtocolFuture<'a, ApprovalResolveResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ApprovalResolve, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn provider_shutdown<'a>(&'a self, request: ProviderShutdownRequest) -> ProtocolFuture<'a, ProviderShutdownResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ProviderShutdown, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn next_message<'a>(&'a self) -> ProtocolInboundFuture<'a> {
        self.transport.next_message()
    }
}

fn rpc_method_error(error: ProtocolError) -> RpcError {
    let message = error.message.clone();
    let data = serde_json::to_value(error).ok().and_then(|value| match value {
        serde_json::Value::Object(entries) => Some(entries.into_iter().collect()),
        _ => None,
    });
    RpcError { code: -32000, message, data }
}

fn rpc_codec_error(context: &str, error: serde_json::Error) -> RpcError {
    RpcError { code: JSON_RPC_INTERNAL_ERROR, message: format!("{context}: {error}"), data: None }
}

fn codec_error(context: &str, error: serde_json::Error) -> ProtocolError {
    ProtocolError {
        code: "protocol_codec_error".to_string(),
        message: format!("{context}: {error}"),
        retryable: false,
        details: None,
    }
}

fn inbound_error(id: Option<RequestId>, code: i64, message: impl Into<String>) -> JsonRpcInboundError {
    JsonRpcInboundError {
        id,
        error: RpcError { code, message: message.into(), data: None },
    }
}

fn inbound_protocol_error(error: JsonRpcInboundError) -> ProtocolError {
    ProtocolError {
        code: format!("json_rpc_{}", error.error.code),
        message: error.error.message,
        retryable: false,
        details: error.error.data,
    }
}

fn object_has_only(object: &serde_json::Map<String, serde_json::Value>, allowed: &[&str]) -> bool {
    object.keys().all(|key| allowed.contains(&key.as_str()))
}

fn object_request_id(object: &serde_json::Map<String, serde_json::Value>) -> Option<RequestId> {
    object.get("id").and_then(serde_json::Value::as_str).map(str::to_string)
}

fn validate_jsonrpc(version: &str) -> Result<(), ProtocolError> {
    if version == "2.0" {
        return Ok(());
    }
    Err(ProtocolError {
        code: "unsupported_jsonrpc_version".to_string(),
        message: format!("unsupported JSON-RPC version: {version}"),
        retryable: false,
        details: None,
    })
}

fn validate_inbound_jsonrpc(object: &serde_json::Map<String, serde_json::Value>, id: Option<RequestId>) -> Result<(), JsonRpcInboundError> {
    match object.get("jsonrpc").and_then(serde_json::Value::as_str) {
        Some("2.0") => Ok(()),
        _ => Err(inbound_error(id, JSON_RPC_INVALID_REQUEST, "jsonrpc must be exactly 2.0")),
    }
}

fn parse_jsonrpc_response(value: serde_json::Value) -> Result<JsonRpcResponse, JsonRpcInboundError> {
    let object = value.as_object().ok_or_else(|| inbound_error(None, JSON_RPC_INVALID_REQUEST, "JSON-RPC response must be an object"))?;
    let id = match object.get("id") {
        Some(serde_json::Value::String(value)) => Some(value.clone()),
        Some(serde_json::Value::Null) => None,
        _ => return Err(inbound_error(None, JSON_RPC_INVALID_REQUEST, "JSON-RPC response id must be a string or null")),
    };
    validate_inbound_jsonrpc(object, id.clone())?;
    let has_result = object.contains_key("result");
    let has_error = object.contains_key("error");
    if has_result == has_error {
        return Err(inbound_error(id, JSON_RPC_INVALID_REQUEST, "JSON-RPC response must contain exactly one of result or error"));
    }
    if !object_has_only(object, &["jsonrpc", "id", if has_result { "result" } else { "error" }]) {
        return Err(inbound_error(id, JSON_RPC_INVALID_REQUEST, "JSON-RPC response contains unknown fields"));
    }
    let response = if has_result {
        JsonRpcResponsePayload::Ok { result: object["result"].clone() }
    } else {
        let error = serde_json::from_value(object["error"].clone())
            .map_err(|error| inbound_error(id.clone(), JSON_RPC_INVALID_REQUEST, format!("invalid JSON-RPC error object: {error}")))?;
        JsonRpcResponsePayload::Error { error }
    };
    Ok(JsonRpcResponse { jsonrpc: "2.0".to_string(), id, response })
}

pub fn decode_wire_message(value: &[u8]) -> Result<ProviderWireMessage, JsonRpcInboundError> {
    let value: serde_json::Value = serde_json::from_slice(value)
        .map_err(|error| inbound_error(None, JSON_RPC_PARSE_ERROR, format!("parse error: {error}")))?;
    let object = value.as_object().ok_or_else(|| inbound_error(None, JSON_RPC_INVALID_REQUEST, "JSON-RPC message must be an object"))?;
    let id = object_request_id(object);
    validate_inbound_jsonrpc(object, id.clone())?;

    if let Some(method_value) = object.get("method") {
        let method = method_value.as_str().ok_or_else(|| inbound_error(id.clone(), JSON_RPC_INVALID_REQUEST, "JSON-RPC method must be a string"))?.to_string();
        if object.contains_key("id") {
            let id = id.ok_or_else(|| inbound_error(None, JSON_RPC_INVALID_REQUEST, "JSON-RPC request id must be a string"))?;
            if !object_has_only(object, &["jsonrpc", "id", "method", "params"]) {
                return Err(inbound_error(Some(id), JSON_RPC_INVALID_REQUEST, "JSON-RPC request contains unknown fields"));
            }
            if method.parse::<ProtocolMethod>().is_err() {
                return Ok(ProviderWireMessage::Request(JsonRpcInboundRequest::Rejected(JsonRpcRequestRejection {
                    id,
                    method: method.clone(),
                    error: RpcError { code: JSON_RPC_METHOD_NOT_FOUND, message: format!("method not found: {method}"), data: None },
                })));
            }
            return match serde_json::from_value(value) {
                Ok(request) => Ok(ProviderWireMessage::Request(JsonRpcInboundRequest::Typed(request))),
                Err(error) => Ok(ProviderWireMessage::Request(JsonRpcInboundRequest::Rejected(JsonRpcRequestRejection {
                    id,
                    method: method.clone(),
                    error: RpcError { code: JSON_RPC_INVALID_PARAMS, message: format!("invalid params for {method}: {error}"), data: None },
                }))),
            };
        }

        if !object_has_only(object, &["jsonrpc", "method", "params"]) {
            return Err(inbound_error(None, JSON_RPC_INVALID_REQUEST, "JSON-RPC notification contains unknown fields"));
        }
        if method.parse::<ProtocolEventName>().is_ok() {
            let event = serde_json::from_value(value)
                .map_err(|error| inbound_error(None, JSON_RPC_INVALID_PARAMS, format!("invalid event params for {method}: {error}")))?;
            return Ok(ProviderWireMessage::Event(event));
        }
        return Ok(ProviderWireMessage::Notification(JsonRpcNotification {
            jsonrpc: "2.0".to_string(),
            method,
            params: object.get("params").cloned().unwrap_or(serde_json::Value::Null),
        }));
    }

    parse_jsonrpc_response(value).map(ProviderWireMessage::Response)
}

pub fn encode_request(value: &ProtocolRequest) -> Result<Vec<u8>, ProtocolError> {
    validate_jsonrpc(value.jsonrpc_version())?;
    serde_json::to_vec(value).map_err(|error| codec_error("encode request", error))
}

pub fn decode_request(value: &[u8]) -> Result<ProtocolRequest, ProtocolError> {
    match decode_wire_message(value).map_err(inbound_protocol_error)? {
        ProviderWireMessage::Request(JsonRpcInboundRequest::Typed(request)) => Ok(request),
        ProviderWireMessage::Request(JsonRpcInboundRequest::Rejected(rejection)) => Err(inbound_protocol_error(JsonRpcInboundError {
            id: Some(rejection.id),
            error: rejection.error,
        })),
        _ => Err(ProtocolError {
            code: "unexpected_json_rpc_message".to_string(),
            message: "expected JSON-RPC request".to_string(),
            retryable: false,
            details: None,
        }),
    }
}

pub fn encode_response(value: &JsonRpcResponse) -> Result<Vec<u8>, ProtocolError> {
    validate_jsonrpc(&value.jsonrpc)?;
    serde_json::to_vec(value).map_err(|error| codec_error("encode response", error))
}

pub fn decode_response(value: &[u8]) -> Result<JsonRpcResponse, ProtocolError> {
    match decode_wire_message(value).map_err(inbound_protocol_error)? {
        ProviderWireMessage::Response(response) => Ok(response),
        _ => Err(ProtocolError {
            code: "unexpected_json_rpc_message".to_string(),
            message: "expected JSON-RPC response".to_string(),
            retryable: false,
            details: None,
        }),
    }
}

pub fn encode_event(value: &ProtocolEvent) -> Result<Vec<u8>, ProtocolError> {
    validate_jsonrpc(value.jsonrpc_version())?;
    serde_json::to_vec(value).map_err(|error| codec_error("encode event", error))
}

pub fn decode_event(value: &[u8]) -> Result<ProtocolEvent, ProtocolError> {
    match decode_wire_message(value).map_err(inbound_protocol_error)? {
        ProviderWireMessage::Event(event) => Ok(event),
        _ => Err(ProtocolError {
            code: "unexpected_json_rpc_message".to_string(),
            message: "expected JSON-RPC event".to_string(),
            retryable: false,
            details: None,
        }),
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct JsonLineCodec {
    max_frame_bytes: usize,
}

impl JsonLineCodec {
    pub fn new(max_frame_bytes: usize) -> Result<Self, ProtocolError> {
        if max_frame_bytes == 0 {
            return Err(ProtocolError {
                code: "invalid_frame_limit".to_string(),
                message: "JSON line frame limit must be greater than zero".to_string(),
                retryable: false,
                details: None,
            });
        }
        Ok(Self { max_frame_bytes })
    }

    pub const fn max_frame_bytes(&self) -> usize {
        self.max_frame_bytes
    }

    fn frame_payload(&self, mut payload: Vec<u8>) -> Result<Vec<u8>, ProtocolError> {
        if payload.len() > self.max_frame_bytes {
            return Err(ProtocolError {
                code: "json_line_frame_too_large".to_string(),
                message: format!("JSON line frame exceeds {} bytes", self.max_frame_bytes),
                retryable: false,
                details: None,
            });
        }
        if payload.contains(&b'\n') || payload.contains(&b'\r') {
            return Err(ProtocolError {
                code: "invalid_json_line_frame".to_string(),
                message: "JSON line payload contains a physical line break".to_string(),
                retryable: false,
                details: None,
            });
        }
        payload.push(b'\n');
        Ok(payload)
    }

    pub fn encode_message(&self, message: &ProviderWireMessage) -> Result<Vec<u8>, ProtocolError> {
        let payload = match message {
            ProviderWireMessage::Request(JsonRpcInboundRequest::Typed(request)) => encode_request(request)?,
            ProviderWireMessage::Request(JsonRpcInboundRequest::Rejected(_)) => {
                return Err(ProtocolError {
                    code: "cannot_encode_rejected_request".to_string(),
                    message: "a rejected inbound request is not a wire request".to_string(),
                    retryable: false,
                    details: None,
                });
            }
            ProviderWireMessage::Response(response) => encode_response(response)?,
            ProviderWireMessage::Notification(notification) => {
                validate_jsonrpc(&notification.jsonrpc)?;
                serde_json::to_vec(notification).map_err(|error| codec_error("encode notification", error))?
            }
            ProviderWireMessage::Event(event) => encode_event(event)?,
        };
        self.frame_payload(payload)
    }

    pub fn decode_line(&self, line: &[u8]) -> Result<ProviderWireMessage, JsonRpcInboundError> {
        let mut payload = line;
        if payload.ends_with(b"\n") {
            payload = &payload[..payload.len() - 1];
            if payload.ends_with(b"\r") {
                payload = &payload[..payload.len() - 1];
            }
        }
        if payload.len() > self.max_frame_bytes {
            return Err(inbound_error(None, JSON_RPC_INVALID_REQUEST, format!("JSON line frame exceeds {} bytes", self.max_frame_bytes)));
        }
        if payload.contains(&b'\n') || payload.contains(&b'\r') {
            return Err(inbound_error(None, JSON_RPC_INVALID_REQUEST, "JSON line frame contains multiple physical lines"));
        }
        decode_wire_message(payload)
    }

    pub fn read_message<R: BufRead>(&self, reader: &mut R) -> Result<Option<ProviderWireMessage>, JsonRpcInboundError> {
        let mut frame = Vec::with_capacity(self.max_frame_bytes.min(8192));
        let mut oversized = false;
        loop {
            let (consumed, complete) = {
                let available = reader.fill_buf()
                    .map_err(|error| inbound_error(None, JSON_RPC_INTERNAL_ERROR, format!("read JSON line frame: {error}")))?;
                if available.is_empty() {
                    if oversized {
                        return Err(inbound_error(None, JSON_RPC_INVALID_REQUEST, format!("JSON line frame exceeds {} bytes", self.max_frame_bytes)));
                    }
                    if frame.is_empty() {
                        return Ok(None);
                    }
                    return self.decode_line(&frame).map(Some);
                }
                let newline = available.iter().position(|byte| *byte == b'\n');
                let payload_bytes = newline.unwrap_or(available.len());
                if !oversized && frame.len().saturating_add(payload_bytes) > self.max_frame_bytes {
                    oversized = true;
                }
                if !oversized {
                    frame.extend_from_slice(&available[..payload_bytes]);
                }
                (newline.map_or(payload_bytes, |index| index + 1), newline.is_some())
            };
            reader.consume(consumed);
            if complete {
                if oversized {
                    return Err(inbound_error(None, JSON_RPC_INVALID_REQUEST, format!("JSON line frame exceeds {} bytes", self.max_frame_bytes)));
                }
                if frame.ends_with(b"\r") {
                    frame.pop();
                }
                return self.decode_line(&frame).map(Some);
            }
        }
    }

    pub fn write_message<W: Write>(&self, writer: &mut W, message: &ProviderWireMessage) -> Result<(), ProtocolError> {
        let frame = self.encode_message(message)?;
        writer.write_all(&frame).map_err(|error| ProtocolError {
            code: "json_line_write_failed".to_string(),
            message: format!("write JSON line frame: {error}"),
            retryable: true,
            details: None,
        })
    }
}

impl Default for JsonLineCodec {
    fn default() -> Self {
        Self { max_frame_bytes: DEFAULT_MAX_JSON_LINE_BYTES }
    }
}
