// @generated by tools/protocol-codegen/generate.mjs from protocol/provider/v1/manifest.json and protocol/provider/v1/schema.json.
// DO NOT EDIT MANUALLY.

import type { ClientId, Cursor, DeviceId, JsonObject, NativeResourceId, PageInfo, ProtocolError, ProtocolVersion, ProviderInstanceId, ProviderPluginId, RequestId, RpcError, TimestampMs, VersionRange } from "../../codepet-core-sdk/src/generated";
export type { ClientId, Cursor, DeviceId, JsonObject, NativeResourceId, PageInfo, ProtocolError, ProtocolVersion, ProviderInstanceId, ProviderPluginId, RequestId, RpcError, TimestampMs, VersionRange } from "../../codepet-core-sdk/src/generated";

export const PROTOCOL_VERSION = 1 as const;
export const PROTOCOL_METHODS = ["provider.initialize", "provider.describe", "runtime.getInstalled", "runtime.select", "instance.create", "instance.start", "instance.stop", "instance.destroy", "instance.capabilities", "conversation.list", "project.list", "project.get", "project.create", "project.update", "project.delete", "conversation.search", "conversation.get", "conversation.acquireInteraction", "conversation.create", "turn.start", "turn.steer", "turn.interrupt", "approval.resolve", "provider.shutdown"] as const;
export const PROTOCOL_EVENTS = ["event.projectChanged", "event.instanceStatusChanged", "event.conversationUpserted", "event.conversationItemUpserted", "event.turnUpserted", "event.turnOutputDelta", "event.approvalRequested", "event.approvalResolved"] as const;

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export interface ActivitySummaryContentBlock {
  contentId: NativeResourceId;
  kind: ActivitySummaryContentBlockKind;
  text: string;
  truncation?: ContentTruncation;
}

export type ActivitySummaryContentBlockKind = "activity-summary";

export interface ApprovalConversationItem {
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: ApprovalConversationItemKind;
  status: ConversationItemStatus;
  title?: string;
  relatedItem?: RoutedResourceId;
  approval: ProviderApproval;
}

export type ApprovalConversationItemKind = "approval";

export type ApprovalDecision = "approve" | "deny";

export interface ApprovalRequestedEvent {
  approval: ProviderApproval;
}

export interface ApprovalResolveRequest {
  approval: RoutedResourceId;
  decision: ApprovalDecision;
}

export interface ApprovalResolveResponse {
  approval: ProviderApproval;
}

export interface ApprovalResolvedEvent {
  approval: ProviderApproval;
}

export type ApprovalStatus = "pending" | "approved" | "denied" | "expired";

export interface AudioContentBlock {
  contentId: NativeResourceId;
  kind: AudioContentBlockKind;
  uri: string;
  mimeType?: string;
  name?: string;
  truncation?: ContentTruncation;
}

export type AudioContentBlockKind = "audio";

export interface ChoiceOption {
  id: string;
  displayName: string;
  description?: string;
  enabled?: boolean;
  disabledReason?: string;
}

export interface ChoiceSet {
  options: Array<ChoiceOption>;
  defaultId?: string;
}

export interface CommandConversationItem {
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: CommandConversationItemKind;
  status: ConversationItemStatus;
  title?: string;
  tool: ToolInvocation;
}

export type CommandConversationItemKind = "command";

export interface CommandToolInput {
  kind: CommandToolInputKind;
  command: string;
  cwd?: string;
  shell?: string;
  actions?: Array<ToolCommandAction>;
}

export type CommandToolInputKind = "command";

export type ContentBlock = TextContentBlock | ReasoningSummaryContentBlock | OutputContentBlock | ActivitySummaryContentBlock | StructuredJsonContentBlock | ImageContentBlock | AudioContentBlock | ResourceLinkContentBlock | EmbeddedResourceContentBlock;

export interface ContentTruncation {
  originalBytes: number;
  retainedBytes: number;
  strategy: ContentTruncationStrategy;
}

export type ContentTruncationStrategy = "head" | "tail" | "head-tail" | "structural-preview";

export interface ConversationAcquireInteractionRequest {
  conversation: RoutedResourceId;
}

export interface ConversationAcquireInteractionResponse {
  selection: TurnSelection;
  leaseExpiresAt?: TimestampMs;
}

export type ConversationContentKind = "text" | "reasoning-summary" | "output" | "activity-summary" | "structured-json" | "image" | "audio" | "resource-link" | "embedded-resource";

export interface ConversationCreateCapabilities {
  supportsTitle: boolean;
  selection?: TurnSendCapabilities;
  workspaceMode?: ChoiceSet;
}

export interface ConversationCreateRequest {
  route: ProviderInstanceRoute;
  title?: string;
  permissionLevel: string;
  model?: string;
  reasoningEffort?: string;
  workspaceRoot?: string;
  workspaceMode?: string;
  project?: RoutedResourceId;
  extension?: ProviderExtension;
}

export interface ConversationCreateResponse {
  conversation: ProviderConversation;
}

export interface ConversationGetRequest {
  conversation: RoutedResourceId;
  cursor?: Cursor;
  limit?: number;
}

export interface ConversationGetResponse {
  conversation: ProviderConversation;
  items: Array<ConversationItem>;
  pageInfo?: PageInfo;
}

export type ConversationItem = MessageConversationItem | ReasoningConversationItem | CommandConversationItem | FileChangeConversationItem | ToolConversationItem | ApprovalConversationItem | UnknownConversationItem;

export type ConversationItemRole = "user" | "assistant";

export type ConversationItemStatus = "pending" | "running" | "completed" | "failed" | "interrupted" | "declined" | "approved" | "denied" | "expired" | "unknown";

export interface ConversationItemUpsertedEvent {
  item: ConversationItem;
}

export interface ConversationListRequest {
  route: ProviderInstanceRoute;
  projectFilter: ConversationProjectFilter;
  cursor?: Cursor;
  limit?: number;
}

export interface ConversationListResponse {
  conversations: Array<ProviderConversation>;
  pageInfo: PageInfo;
}

export type ConversationProjectFilter = ConversationProjectFilterAll | ConversationProjectFilterStandalone | ConversationProjectFilterProject;

export interface ConversationProjectFilterAll {
  kind: ConversationProjectFilterAllKind;
}

export type ConversationProjectFilterAllKind = "all";

export interface ConversationProjectFilterProject {
  kind: ConversationProjectFilterProjectKind;
  project: RoutedResourceId;
}

export type ConversationProjectFilterProjectKind = "project";

export interface ConversationProjectFilterStandalone {
  kind: ConversationProjectFilterStandaloneKind;
}

export type ConversationProjectFilterStandaloneKind = "standalone";

export interface ConversationSearchRequest {
  route: ProviderInstanceRoute;
  searchTerm: string;
  cursor?: Cursor;
  limit?: number;
}

export interface ConversationSearchResponse {
  conversations: Array<ProviderConversation>;
  pageInfo: PageInfo;
}

export type ConversationStatus = "idle" | "running" | "waiting-approval" | "waiting-user-input" | "error" | "archived";

export interface ConversationUpsertedEvent {
  conversation: ProviderConversation;
}

export interface EmbeddedResourceContentBlock {
  contentId: NativeResourceId;
  kind: EmbeddedResourceContentBlockKind;
  text: string;
  mimeType?: string;
  name?: string;
  truncation?: ContentTruncation;
}

export type EmbeddedResourceContentBlockKind = "embedded-resource";

export interface FileChangeConversationItem {
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: FileChangeConversationItemKind;
  status: ConversationItemStatus;
  title?: string;
  contents: Array<ContentBlock>;
}

export type FileChangeConversationItemKind = "file-change";

export interface FlatModelCatalog {
  kind: FlatModelCatalogKind;
  models: Array<ChoiceOption>;
  defaultSelection?: FlatModelSelection;
}

export type FlatModelCatalogKind = "flat";

export interface FlatModelSelection {
  kind: FlatModelCatalogKind;
  modelId: string;
}

export interface GroupedModelCatalog {
  kind: GroupedModelCatalogKind;
  providers: Array<GroupedModelProvider>;
  defaultSelection?: GroupedModelSelection;
}

export type GroupedModelCatalogKind = "grouped";

export interface GroupedModelProvider {
  id: string;
  displayName: string;
  description?: string;
  models: Array<ChoiceOption>;
}

export interface GroupedModelSelection {
  kind: GroupedModelCatalogKind;
  providerId: string;
  modelId: string;
}

export interface HarnessDescriptor {
  id: string;
  displayName: string;
  version?: string;
  executablePath?: string;
}

export interface ImageContentBlock {
  contentId: NativeResourceId;
  kind: ImageContentBlockKind;
  uri: string;
  mimeType?: string;
  name?: string;
  truncation?: ContentTruncation;
}

export type ImageContentBlockKind = "image";

export interface InstanceCapabilitiesRequest {
  route: ProviderInstanceRoute;
}

export interface InstanceCapabilitiesResponse {
  capabilities: ProviderCapabilities;
}

export interface InstanceCreateRequest {
  route: ProviderInstanceRoute;
  instanceKind: ProviderInstanceKind;
  displayName: string;
  settings: JsonObject;
}

export interface InstanceCreateResponse {
  instance: ProviderInstance;
}

export interface InstanceDestroyRequest {
  route: ProviderInstanceRoute;
}

export interface InstanceDestroyResponse {
  destroyed: boolean;
}

export interface InstanceStartRequest {
  route: ProviderInstanceRoute;
}

export interface InstanceStartResponse {
  instance: ProviderInstance;
}

export type InstanceStatus = "created" | "starting" | "ready" | "stopping" | "stopped" | "error";

export interface InstanceStatusChangedEvent {
  instance: ProviderInstance;
  previousStatus?: InstanceStatus;
}

export interface InstanceStopRequest {
  route: ProviderInstanceRoute;
}

export interface InstanceStopResponse {
  instance: ProviderInstance;
}

export interface MessageConversationItem {
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: MessageConversationItemKind;
  status: ConversationItemStatus;
  role: ConversationItemRole;
  contents: Array<ContentBlock>;
}

export type MessageConversationItemKind = "message";

export type ModelCatalog = FlatModelCatalog | GroupedModelCatalog;

export type ModelSelection = FlatModelSelection | GroupedModelSelection;

export interface OpaqueToolInput {
  kind: OpaqueToolInputKind;
  value: string;
  mimeType?: string;
  truncation?: ContentTruncation;
}

export type OpaqueToolInputKind = "opaque";

export interface OutputContentBlock {
  contentId: NativeResourceId;
  kind: OutputContentBlockKind;
  text: string;
  truncation?: ContentTruncation;
}

export type OutputContentBlockKind = "output";

export interface Project {
  resource: RoutedResourceId;
  name: string;
  roots: Array<ProjectRoot>;
  metadata: Record<string, string>;
  position: number;
  createdAt: TimestampMs;
  updatedAt: TimestampMs;
}

export type ProjectChangeType = "created" | "updated" | "deleted";

export interface ProjectChangedEvent {
  project: RoutedResourceId;
  changeType: ProjectChangeType;
}

export interface ProjectCreateRequest {
  route: ProviderInstanceRoute;
  idempotencyKey: RequestId;
  name: string;
  roots: Array<ProjectRoot>;
  metadata: Record<string, string>;
}

export interface ProjectCreateResponse {
  project: Project;
}

export interface ProjectDeleteRequest {
  project: RoutedResourceId;
}

export interface ProjectDeleteResponse {

}

export interface ProjectGetRequest {
  project: RoutedResourceId;
}

export interface ProjectGetResponse {
  project: Project;
}

export interface ProjectListRequest {
  route: ProviderInstanceRoute;
  cursor?: Cursor;
  limit?: number;
}

export interface ProjectListResponse {
  projects: Array<Project>;
  pageInfo: PageInfo;
}

export interface ProjectRoot {
  path: string;
}

export interface ProjectUpdateRequest {
  project: RoutedResourceId;
  name?: string;
  roots?: Array<ProjectRoot>;
  metadata?: Record<string, string>;
}

export interface ProjectUpdateResponse {
  project: Project;
}

export interface ProviderApproval {
  resource: RoutedResourceId;
  conversation: RoutedResourceId;
  turn: RoutedResourceId;
  kind: string;
  title: string;
  description?: string;
  status: ApprovalStatus;
  decisions: Array<ApprovalDecision>;
  requestedAt?: TimestampMs;
  resolvedAt?: TimestampMs;
  decision?: ApprovalDecision;
  extension?: ProviderExtension;
}

export interface ProviderAuthentication {
  status: ProviderAuthenticationStatus;
  displayText?: string;
}

export type ProviderAuthenticationStatus = "unknown" | "signed-in" | "signed-out" | "expired" | "error" | "unsupported";

export interface ProviderCapabilities {
  revision: string;
  methods: Array<ProviderCapability>;
  turnSend?: TurnSendCapabilities;
  conversationCreate?: ConversationCreateCapabilities;
  extensions: Array<ProviderExtension>;
}

export type ProviderCapability = "project.list" | "project.get" | "project.create" | "project.update" | "project.delete" | "conversation.list" | "conversation.search" | "conversation.get" | "conversation.create" | "turn.start" | "turn.steer" | "turn.interrupt" | "approval.resolve";

export interface ProviderConversation {
  resource: RoutedResourceId;
  project: RoutedResourceId | null;
  title: string;
  preview?: string;
  status: ConversationStatus;
  permissionLevel?: string;
  model?: string;
  reasoningEffort?: string;
  selection?: TurnSelection;
  workspaceRoot?: string;
  createdAt?: TimestampMs;
  updatedAt?: TimestampMs;
  activeTurn?: ProviderTurn;
  extension?: ProviderExtension;
}

export interface ProviderDescribeRequest {

}

export interface ProviderDescribeResponse {
  plugin: ProviderPluginDescriptor;
}

export interface ProviderExtension {
  namespace: string;
  data: JsonObject;
}

export interface ProviderInitializeRequest {
  hostClientId: ClientId;
  hostDeviceId: DeviceId;
  hostVersion: string;
  supportedVersions: VersionRange;
}

export interface ProviderInitializeResponse {
  selectedVersion: ProtocolVersion;
  plugin: ProviderPluginDescriptor;
}

export interface ProviderInstance {
  route: ProviderInstanceRoute;
  pluginId: ProviderPluginId;
  instanceKind: ProviderInstanceKind;
  displayName: string;
  harness: HarnessDescriptor;
  status: InstanceStatus;
  authentication?: ProviderAuthentication;
  usage?: ProviderUsage;
  capabilities: ProviderCapabilities;
}

export type ProviderInstanceKind = string;

export interface ProviderInstanceRoute {
  deviceId: DeviceId;
  providerPluginId: ProviderPluginId;
  providerInstanceId: ProviderInstanceId;
}

export interface ProviderPluginDescriptor {
  pluginId: ProviderPluginId;
  displayName: string;
  version: string;
  defaultWorkspaceRoot?: string;
  supportedVersions: VersionRange;
  instanceKinds: Array<ProviderInstanceKind>;
}

export interface ProviderShutdownRequest {

}

export interface ProviderShutdownResponse {
  accepted: boolean;
}

export interface ProviderTurn {
  resource: RoutedResourceId;
  conversation: RoutedResourceId;
  status: TurnStatus;
  displaySummary?: string;
  startedAt?: TimestampMs;
  updatedAt?: TimestampMs;
  completedAt?: TimestampMs;
  extension?: ProviderExtension;
}

export interface ProviderUsage {
  displayText: string;
  observedAt?: TimestampMs;
  details?: Array<ProviderUsageDetail>;
}

export interface ProviderUsageDetail {
  namespace: string;
  schemaVersion: string;
  data: JsonObject;
}

export interface ReasoningConversationItem {
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: ReasoningConversationItemKind;
  status: ConversationItemStatus;
  contents: Array<ContentBlock>;
}

export type ReasoningConversationItemKind = "reasoning";

export interface ReasoningSummaryContentBlock {
  contentId: NativeResourceId;
  kind: ReasoningSummaryContentBlockKind;
  text: string;
  truncation?: ContentTruncation;
}

export type ReasoningSummaryContentBlockKind = "reasoning-summary";

export interface ResourceLinkContentBlock {
  contentId: NativeResourceId;
  kind: ResourceLinkContentBlockKind;
  uri: string;
  name?: string;
  mimeType?: string;
  truncation?: ContentTruncation;
}

export type ResourceLinkContentBlockKind = "resource-link";

export interface RoutedResourceId {
  deviceId: DeviceId;
  providerPluginId: ProviderPluginId;
  providerInstanceId: ProviderInstanceId;
  nativeResourceId: NativeResourceId;
}

export interface RuntimeCandidate {
  executablePath: string;
  source: RuntimeCandidateSource;
}

export type RuntimeCandidateSource = "configured" | "environment" | "current-path" | "login-shell" | "macos-application" | "windows-application";

export interface RuntimeGetInstalledRequest {

}

export interface RuntimeGetInstalledResponse {
  installed: Array<RuntimeInstallation>;
  selected?: RuntimeInstallation;
}

export interface RuntimeInstallation {
  executablePath: string;
  version: string;
  source: RuntimeCandidateSource;
}

export interface RuntimeSelectRequest {
  candidate: RuntimeCandidate;
}

export interface RuntimeSelectResponse {
  selected: RuntimeInstallation;
}

export interface StructuredJsonContentBlock {
  contentId: NativeResourceId;
  kind: StructuredJsonContentBlockKind;
  value: JsonObject;
  truncation?: ContentTruncation;
}

export type StructuredJsonContentBlockKind = "structured-json";

export interface StructuredToolInput {
  kind: StructuredToolInputKind;
  value: JsonObject;
  truncation?: ContentTruncation;
}

export type StructuredToolInputKind = "structured";

export interface TextContentBlock {
  contentId: NativeResourceId;
  kind: TextContentBlockKind;
  text: string;
  truncation?: ContentTruncation;
}

export type TextContentBlockKind = "text";

export interface ToolAnnotations {
  readOnly?: boolean;
  destructive?: boolean;
  idempotent?: boolean;
  openWorld?: boolean;
}

export type ToolCategory = "command" | "read" | "write" | "search" | "web" | "agent" | "computer" | "media" | "other";

export interface ToolCommandAction {
  kind: ToolCommandActionKind;
  command: string;
  name?: string;
  path?: string;
  query?: string;
}

export type ToolCommandActionKind = "execute" | "read" | "list" | "search" | "unknown";

export interface ToolConversationItem {
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: ToolConversationItemKind;
  status: ConversationItemStatus;
  title?: string;
  tool: ToolInvocation;
}

export type ToolConversationItemKind = "tool";

export interface ToolExecutionError {
  code?: string;
  message: string;
  retryable?: boolean;
}

export interface ToolFailureOutcome {
  kind: ToolFailureOutcomeKind;
  content: Array<ContentBlock>;
  error: ToolExecutionError;
  exitCode?: number;
  processId?: string;
}

export type ToolFailureOutcomeKind = "failure";

export type ToolInput = CommandToolInput | StructuredToolInput | OpaqueToolInput;

export interface ToolInvocation {
  callId: NativeResourceId;
  name: string;
  namespace?: string;
  category: ToolCategory;
  origin: ToolOrigin;
  input: ToolInput;
  outcome?: ToolOutcome;
  timing?: ToolTiming;
  annotations?: ToolAnnotations;
  extension?: ProviderExtension;
}

export interface ToolOrigin {
  kind: ToolOriginKind;
  name?: string;
}

export type ToolOriginKind = "builtin" | "mcp" | "plugin" | "server" | "custom" | "unknown";

export type ToolOutcome = ToolSuccessOutcome | ToolFailureOutcome;

export interface ToolSuccessOutcome {
  kind: ToolSuccessOutcomeKind;
  content: Array<ContentBlock>;
  exitCode?: number;
  processId?: string;
}

export type ToolSuccessOutcomeKind = "success";

export interface ToolTiming {
  startedAt?: TimestampMs;
  completedAt?: TimestampMs;
  durationMs?: number;
}

export interface TurnInput {
  kind: TurnInputKind;
  text: string;
}

export type TurnInputKind = "text";

export interface TurnInterruptRequest {
  conversation: RoutedResourceId;
  turn: RoutedResourceId;
}

export interface TurnInterruptResponse {
  turn: ProviderTurn;
}

export interface TurnOutputDeltaEvent {
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  itemId: NativeResourceId;
  contentId: NativeResourceId;
  kind: ConversationContentKind;
  delta: string;
  extension?: ProviderExtension;
}

export interface TurnSelection {
  accessModeId?: string;
  reasoningEffortId?: string;
  model?: ModelSelection;
}

export interface TurnSendCapabilities {
  accessMode?: ChoiceSet;
  reasoningEffort?: ChoiceSet;
  modelCatalog?: ModelCatalog;
}

export interface TurnStartRequest {
  conversation: RoutedResourceId;
  clientRequestId: RequestId;
  capabilityRevision: string;
  input: TurnInput;
  selection: TurnSelection;
}

export interface TurnStartResponse {
  accepted: boolean;
  turn: ProviderTurn;
  userItem: ConversationItem | null;
  effectiveSelection: TurnSelection;
}

export type TurnStatus = "queued" | "running" | "waiting-approval" | "completed" | "failed" | "interrupted";

export interface TurnSteerRequest {
  conversation: RoutedResourceId;
  turn: RoutedResourceId;
  clientMessageId: RequestId;
  message: string;
}

export interface TurnSteerResponse {
  turn: ProviderTurn;
}

export interface TurnUpsertedEvent {
  turn: ProviderTurn;
}

export interface UnknownConversationItem {
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: UnknownConversationItemKind;
  status: ConversationItemStatus;
  title?: string;
}

export type UnknownConversationItemKind = "unknown";

export interface ProtocolRequestMap {
  "provider.initialize": ProviderInitializeRequest;
  "provider.describe": ProviderDescribeRequest;
  "runtime.getInstalled": RuntimeGetInstalledRequest;
  "runtime.select": RuntimeSelectRequest;
  "instance.create": InstanceCreateRequest;
  "instance.start": InstanceStartRequest;
  "instance.stop": InstanceStopRequest;
  "instance.destroy": InstanceDestroyRequest;
  "instance.capabilities": InstanceCapabilitiesRequest;
  "conversation.list": ConversationListRequest;
  "project.list": ProjectListRequest;
  "project.get": ProjectGetRequest;
  "project.create": ProjectCreateRequest;
  "project.update": ProjectUpdateRequest;
  "project.delete": ProjectDeleteRequest;
  "conversation.search": ConversationSearchRequest;
  "conversation.get": ConversationGetRequest;
  "conversation.acquireInteraction": ConversationAcquireInteractionRequest;
  "conversation.create": ConversationCreateRequest;
  "turn.start": TurnStartRequest;
  "turn.steer": TurnSteerRequest;
  "turn.interrupt": TurnInterruptRequest;
  "approval.resolve": ApprovalResolveRequest;
  "provider.shutdown": ProviderShutdownRequest;
}

export interface ProtocolResponseMap {
  "provider.initialize": ProviderInitializeResponse;
  "provider.describe": ProviderDescribeResponse;
  "runtime.getInstalled": RuntimeGetInstalledResponse;
  "runtime.select": RuntimeSelectResponse;
  "instance.create": InstanceCreateResponse;
  "instance.start": InstanceStartResponse;
  "instance.stop": InstanceStopResponse;
  "instance.destroy": InstanceDestroyResponse;
  "instance.capabilities": InstanceCapabilitiesResponse;
  "conversation.list": ConversationListResponse;
  "project.list": ProjectListResponse;
  "project.get": ProjectGetResponse;
  "project.create": ProjectCreateResponse;
  "project.update": ProjectUpdateResponse;
  "project.delete": ProjectDeleteResponse;
  "conversation.search": ConversationSearchResponse;
  "conversation.get": ConversationGetResponse;
  "conversation.acquireInteraction": ConversationAcquireInteractionResponse;
  "conversation.create": ConversationCreateResponse;
  "turn.start": TurnStartResponse;
  "turn.steer": TurnSteerResponse;
  "turn.interrupt": TurnInterruptResponse;
  "approval.resolve": ApprovalResolveResponse;
  "provider.shutdown": ProviderShutdownResponse;
}

export interface ProtocolEventMap {
  "event.projectChanged": ProjectChangedEvent;
  "event.instanceStatusChanged": InstanceStatusChangedEvent;
  "event.conversationUpserted": ConversationUpsertedEvent;
  "event.conversationItemUpserted": ConversationItemUpsertedEvent;
  "event.turnUpserted": TurnUpsertedEvent;
  "event.turnOutputDelta": TurnOutputDeltaEvent;
  "event.approvalRequested": ApprovalRequestedEvent;
  "event.approvalResolved": ApprovalResolvedEvent;
}

export type ProtocolMethod = keyof ProtocolRequestMap;
export type ProtocolEventName = keyof ProtocolEventMap;
export type ProtocolRequest = {
  [M in ProtocolMethod]: { jsonrpc: "2.0"; id: RequestId; method: M; params: ProtocolRequestMap[M] }
}[ProtocolMethod];
export type ProtocolSuccessResponse<M extends ProtocolMethod = ProtocolMethod> = { jsonrpc: "2.0"; id: RequestId; result: ProtocolResponseMap[M] };
export type ProtocolErrorResponse = { jsonrpc: "2.0"; id: RequestId | null; error: RpcError };
export type ProtocolResponse<M extends ProtocolMethod = ProtocolMethod> = ProtocolSuccessResponse<M> | ProtocolErrorResponse;
export type ProtocolEvent = {
  [E in ProtocolEventName]: { jsonrpc: "2.0"; method: E; params: ProtocolEventMap[E] }
}[ProtocolEventName];

export interface ProtocolTransport {
  request<M extends ProtocolMethod>(method: M, params: ProtocolRequestMap[M]): Promise<ProtocolResponseMap[M]>;
}
