// @generated by tools/protocol-codegen/generate.mjs from protocol/gateway/v1/manifest.json and protocol/gateway/v1/schema.json.
// DO NOT EDIT MANUALLY.

import type { ClientId, Cursor, DeviceDescriptor, EventCursor, JsonObject, NativeResourceId, PageInfo, ProtocolError, ProtocolVersion, RequestId, RoutedResourceId, RpcError, TimestampMs, TraceContext, VersionRange } from "../../codepet-core-sdk/src/generated";
export type { ClientId, Cursor, DeviceDescriptor, EventCursor, JsonObject, NativeResourceId, PageInfo, ProtocolError, ProtocolVersion, RequestId, RoutedResourceId, RpcError, TimestampMs, TraceContext, VersionRange } from "../../codepet-core-sdk/src/generated";

export const PROTOCOL_VERSION = 1 as const;
export const PROTOCOL_METHODS = ["protocol.handshake", "protocol.describe", "event.subscribe", "provider.list", "provider.describe", "project.list", "project.get", "project.create", "project.update", "project.delete", "conversation.list", "conversation.search", "conversation.get", "conversation.markRead", "conversation.acquireInteraction", "conversation.create", "turn.send", "turn.interrupt", "approval.resolve"] as const;
export const PROTOCOL_EVENTS = ["project.changed", "provider.changed", "conversation.upserted", "conversation.itemUpserted", "conversation.activityChanged", "turn.upserted", "turn.outputDelta", "approval.requested", "approval.resolved"] as const;

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export interface ActivitySummaryContentBlock {
  contentId: NativeResourceId;
  kind: ActivitySummaryContentBlockKind;
  text: string;
  truncation?: ContentTruncation;
}

export type ActivitySummaryContentBlockKind = "activity-summary";

export interface Approval {
  resource: RoutedResourceId;
  conversation: RoutedResourceId;
  turn: RoutedResourceId;
  kind: string;
  title: string;
  description?: string;
  status: ApprovalStatus;
  decisions: Array<ApprovalDecision>;
  requestedAt?: TimestampMs;
  resolvedAt?: TimestampMs;
  decision?: ApprovalDecision;
}

export interface ApprovalConversationItem {
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: ApprovalConversationItemKind;
  status: ConversationItemStatus;
  title?: string;
  relatedItem?: RoutedResourceId;
  approval: Approval;
}

export type ApprovalConversationItemKind = "approval";

export type ApprovalDecision = "approve" | "deny";

export interface ApprovalRequestedEvent {
  approval: Approval;
}

export interface ApprovalResolveRequest {
  approval: RoutedResourceId;
  decision: ApprovalDecision;
}

export interface ApprovalResolveResponse {
  approval: Approval;
}

export interface ApprovalResolvedEvent {
  approval: Approval;
}

export type ApprovalStatus = "pending" | "approved" | "denied" | "expired";

export interface AudioContentBlock {
  contentId: NativeResourceId;
  kind: AudioContentBlockKind;
  uri: string;
  mimeType?: string;
  name?: string;
  truncation?: ContentTruncation;
}

export type AudioContentBlockKind = "audio";

export interface ChoiceOption {
  id: ProviderId;
  displayName: string;
  description?: string;
  enabled?: boolean;
  disabledReason?: string;
}

export interface ChoiceSet {
  options: Array<ChoiceOption>;
  defaultId?: string;
}

export interface CommandConversationItem {
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: CommandConversationItemKind;
  status: ConversationItemStatus;
  title?: string;
  tool: ToolInvocation;
}

export type CommandConversationItemKind = "command";

export interface CommandToolInput {
  kind: CommandToolInputKind;
  command: string;
  cwd?: string;
  shell?: string;
  truncation?: ContentTruncation;
  actions?: Array<ToolCommandAction>;
}

export type CommandToolInputKind = "command";

export type ContentBlock = TextContentBlock | ReasoningSummaryContentBlock | OutputContentBlock | ActivitySummaryContentBlock | StructuredJsonContentBlock | ImageContentBlock | AudioContentBlock | ResourceLinkContentBlock | EmbeddedResourceContentBlock;

export interface ContentTruncation {
  originalBytes: number;
  retainedBytes: number;
  strategy: ContentTruncationStrategy;
}

export type ContentTruncationStrategy = "head" | "tail" | "head-tail" | "structural-preview";

export interface Conversation {
  resource: RoutedResourceId;
  project: RoutedResourceId | null;
  title: string;
  preview?: string;
  status: ConversationStatus;
  permissionLevel?: string;
  model?: string;
  reasoningEffort?: string;
  selection?: TurnSelection;
  workspaceRoot?: string;
  createdAt?: TimestampMs;
  updatedAt?: TimestampMs;
  activeTurn?: TurnTask;
  readState?: ConversationReadState;
}

export interface ConversationAcquireInteractionRequest {
  conversation: RoutedResourceId;
}

export interface ConversationAcquireInteractionResponse {
  selection: TurnSelection;
  leaseExpiresAt?: TimestampMs;
}

export interface ConversationActivityChangedEvent {
  conversation: RoutedResourceId;
  activityVersion: string;
}

export type ConversationContentKind = "text" | "reasoning-summary" | "output" | "activity-summary" | "structured-json" | "image" | "audio" | "resource-link" | "embedded-resource";

export interface ConversationCreateCapabilities {
  supportsTitle: boolean;
  selection?: TurnSendCapabilities;
  workspaceMode?: ChoiceSet;
}

export interface ConversationCreateRequest {
  providerId: ProviderId;
  title?: string;
  permissionLevel: string;
  model?: string;
  reasoningEffort?: string;
  workspaceRoot?: string;
  workspaceMode?: string;
  project?: RoutedResourceId;
}

export interface ConversationCreateResponse {
  conversation: Conversation;
}

export interface ConversationGetRequest {
  conversation: RoutedResourceId;
  cursor?: Cursor;
  limit?: number;
}

export interface ConversationGetResponse {
  conversation: Conversation;
  items: Array<ConversationItem>;
  pageInfo?: PageInfo;
  snapshotCursor: EventCursor;
}

export type ConversationItem = MessageConversationItem | ReasoningConversationItem | CommandConversationItem | FileChangeConversationItem | ToolConversationItem | ApprovalConversationItem | UnknownConversationItem;

export type ConversationItemRole = "user" | "assistant";

export type ConversationItemStatus = "pending" | "running" | "completed" | "failed" | "interrupted" | "declined" | "approved" | "denied" | "expired" | "unknown";

export interface ConversationItemUpsertedEvent {
  item: ConversationItem;
}

export interface ConversationListRequest {
  providerId: ProviderId;
  projectFilter: ConversationProjectFilter;
  cursor?: Cursor;
  limit?: number;
}

export interface ConversationListResponse {
  conversations: Array<Conversation>;
  pageInfo: PageInfo;
  snapshotCursor: EventCursor;
}

export interface ConversationMarkReadRequest {
  conversation: RoutedResourceId;
  observedActivityVersion: string;
}

export interface ConversationMarkReadResponse {
  readState: ConversationReadState;
}

export type ConversationProjectFilter = ConversationProjectFilterAll | ConversationProjectFilterStandalone | ConversationProjectFilterProject;

export interface ConversationProjectFilterAll {
  kind: ConversationProjectFilterAllKind;
}

export type ConversationProjectFilterAllKind = "all";

export interface ConversationProjectFilterProject {
  kind: ConversationProjectFilterProjectKind;
  project: RoutedResourceId;
}

export type ConversationProjectFilterProjectKind = "project";

export interface ConversationProjectFilterStandalone {
  kind: ConversationProjectFilterStandaloneKind;
}

export type ConversationProjectFilterStandaloneKind = "standalone";

export interface ConversationReadState {
  unread: boolean;
  activityVersion: string;
}

export interface ConversationSearchRequest {
  providerId: ProviderId;
  searchTerm: string;
  cursor?: Cursor;
  limit?: number;
}

export interface ConversationSearchResponse {
  conversations: Array<Conversation>;
  pageInfo: PageInfo;
  snapshotCursor: EventCursor;
}

export type ConversationStatus = "idle" | "running" | "waiting-approval" | "waiting-user-input" | "error" | "archived";

export interface ConversationUpsertedEvent {
  conversation: Conversation;
}

export interface EmbeddedResourceContentBlock {
  contentId: NativeResourceId;
  kind: EmbeddedResourceContentBlockKind;
  text: string;
  mimeType?: string;
  name?: string;
  truncation?: ContentTruncation;
}

export type EmbeddedResourceContentBlockKind = "embedded-resource";

export interface EventSubscribeRequest {
  afterCursor: EventCursor;
}

export interface EventSubscribeResponse {
  subscribedAfterCursor: EventCursor;
}

export interface FileChangeConversationItem {
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: FileChangeConversationItemKind;
  status: ConversationItemStatus;
  title?: string;
  contents: Array<ContentBlock>;
}

export type FileChangeConversationItemKind = "file-change";

export interface FlatModelCatalog {
  kind: FlatModelCatalogKind;
  models: Array<ChoiceOption>;
  defaultSelection?: FlatModelSelection;
}

export type FlatModelCatalogKind = "flat";

export interface FlatModelSelection {
  kind: FlatModelCatalogKind;
  modelId: string;
}

export interface GatewayCapabilities {
  revision: string;
  methods: Array<GatewayCapability>;
  turnSend?: TurnSendCapabilities;
  conversationCreate?: ConversationCreateCapabilities;
}

export type GatewayCapability = "project.list" | "project.get" | "project.create" | "project.update" | "project.delete" | "conversation.list" | "conversation.search" | "conversation.get" | "conversation.create" | "turn.send" | "turn.interrupt" | "approval.resolve";

export interface GatewayDevice {
  name: string;
  operatingSystem: string;
  systemVersion: string;
}

export interface GatewayProtocol {
  version: ProtocolVersion;
}

export interface GroupedModelCatalog {
  kind: GroupedModelCatalogKind;
  providers: Array<GroupedModelProvider>;
  defaultSelection?: GroupedModelSelection;
}

export type GroupedModelCatalogKind = "grouped";

export interface GroupedModelProvider {
  id: string;
  displayName: string;
  description?: string;
  models: Array<ChoiceOption>;
}

export interface GroupedModelSelection {
  kind: GroupedModelCatalogKind;
  providerId: string;
  modelId: string;
}

export interface HandshakeRequest {
  clientId: ClientId;
  device: DeviceDescriptor;
  clientVersion: string;
  supportedVersions: VersionRange;
  lastEventCursor?: EventCursor;
}

export interface HandshakeResponse {
  protocol: GatewayProtocol;
  device: GatewayDevice;
  providers: Array<ProviderSummary>;
  eventCursor: EventCursor;
}

export interface ImageContentBlock {
  contentId: NativeResourceId;
  kind: ImageContentBlockKind;
  uri: string;
  mimeType?: string;
  name?: string;
  truncation?: ContentTruncation;
}

export type ImageContentBlockKind = "image";

export interface MessageConversationItem {
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: MessageConversationItemKind;
  status: ConversationItemStatus;
  role: ConversationItemRole;
  contents: Array<ContentBlock>;
}

export type MessageConversationItemKind = "message";

export type ModelCatalog = FlatModelCatalog | GroupedModelCatalog;

export type ModelSelection = FlatModelSelection | GroupedModelSelection;

export interface OpaqueToolInput {
  kind: OpaqueToolInputKind;
  value: string;
  mimeType?: string;
  truncation?: ContentTruncation;
}

export type OpaqueToolInputKind = "opaque";

export interface OutputContentBlock {
  contentId: NativeResourceId;
  kind: OutputContentBlockKind;
  text: string;
  truncation?: ContentTruncation;
}

export type OutputContentBlockKind = "output";

export interface Project {
  resource: RoutedResourceId;
  name: string;
  roots: Array<ProjectRoot>;
  metadata: Record<string, string>;
  position: number;
  createdAt: TimestampMs;
  updatedAt: TimestampMs;
}

export type ProjectChangeType = "created" | "updated" | "deleted";

export interface ProjectChangedEvent {
  project: RoutedResourceId;
  changeType: ProjectChangeType;
}

export interface ProjectCreateRequest {
  providerId: ProviderId;
  idempotencyKey: RequestId;
  name: string;
  roots: Array<ProjectRoot>;
  metadata: Record<string, string>;
}

export interface ProjectCreateResponse {
  project: Project;
}

export interface ProjectDeleteRequest {
  project: RoutedResourceId;
}

export interface ProjectDeleteResponse {

}

export interface ProjectGetRequest {
  project: RoutedResourceId;
}

export interface ProjectGetResponse {
  project: Project;
}

export interface ProjectListRequest {
  providerId: ProviderId;
  cursor?: Cursor;
  limit?: number;
}

export interface ProjectListResponse {
  projects: Array<Project>;
  pageInfo: PageInfo;
  snapshotCursor: EventCursor;
}

export interface ProjectRoot {
  path: string;
}

export interface ProjectUpdateRequest {
  project: RoutedResourceId;
  name?: string;
  roots?: Array<ProjectRoot>;
  metadata?: Record<string, string>;
}

export interface ProjectUpdateResponse {
  project: Project;
}

export interface ProtocolDescribeRequest {

}

export interface ProtocolDescribeResponse {
  features: Array<ProtocolFeature>;
}

export type ProtocolFeature = "trace-context-v1";

export interface ProviderAuthentication {
  status: ProviderAuthenticationStatus;
  displayText?: string;
}

export type ProviderAuthenticationStatus = "unknown" | "signed-in" | "signed-out" | "expired" | "error" | "unsupported";

export interface ProviderCapabilitiesSummary {
  revision: string;
}

export interface ProviderChangedEvent {
  provider: ProviderSummary;
}

export interface ProviderDescribeRequest {
  providerId: ProviderId;
}

export interface ProviderDescribeResponse {
  provider: ProviderSummary;
  capabilities: GatewayCapabilities;
}

export type ProviderId = string;

export interface ProviderIdentity {
  displayName: string;
  icon?: string;
  defaultWorkspaceRoot?: string;
}

export interface ProviderListRequest {

}

export interface ProviderListResponse {
  providers: Array<ProviderSummary>;
}

export interface ProviderRuntime {
  status: ProviderStatus;
  version?: string;
  executablePath?: string;
  authentication?: ProviderAuthentication;
  usage?: ProviderUsage;
}

export type ProviderStatus = "connecting" | "ready" | "stopped" | "unavailable" | "error";

export interface ProviderSummary {
  id: string;
  identity: ProviderIdentity;
  runtime: ProviderRuntime;
  capabilities: ProviderCapabilitiesSummary;
}

export interface ProviderUsage {
  displayText: string;
  observedAt?: TimestampMs;
  details?: Array<ProviderUsageDetail>;
}

export interface ProviderUsageDetail {
  namespace: string;
  schemaVersion: string;
  data: JsonObject;
}

export interface ReasoningConversationItem {
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: ReasoningConversationItemKind;
  status: ConversationItemStatus;
  contents: Array<ContentBlock>;
}

export type ReasoningConversationItemKind = "reasoning";

export interface ReasoningSummaryContentBlock {
  contentId: NativeResourceId;
  kind: ReasoningSummaryContentBlockKind;
  text: string;
  truncation?: ContentTruncation;
}

export type ReasoningSummaryContentBlockKind = "reasoning-summary";

export interface ResourceLinkContentBlock {
  contentId: NativeResourceId;
  kind: ResourceLinkContentBlockKind;
  uri: string;
  name?: string;
  mimeType?: string;
  truncation?: ContentTruncation;
}

export type ResourceLinkContentBlockKind = "resource-link";

export interface StructuredJsonContentBlock {
  contentId: NativeResourceId;
  kind: StructuredJsonContentBlockKind;
  value: JsonObject;
  truncation?: ContentTruncation;
}

export type StructuredJsonContentBlockKind = "structured-json";

export interface StructuredToolInput {
  kind: StructuredToolInputKind;
  value: JsonObject;
  truncation?: ContentTruncation;
}

export type StructuredToolInputKind = "structured";

export interface TextContentBlock {
  contentId: NativeResourceId;
  kind: TextContentBlockKind;
  text: string;
  truncation?: ContentTruncation;
}

export type TextContentBlockKind = "text";

export interface ToolAnnotations {
  readOnly?: boolean;
  destructive?: boolean;
  idempotent?: boolean;
  openWorld?: boolean;
}

export type ToolCategory = "command" | "read" | "write" | "search" | "web" | "agent" | "computer" | "media" | "other";

export interface ToolCommandAction {
  kind: ToolCommandActionKind;
  command: string;
  name?: string;
  path?: string;
  query?: string;
}

export type ToolCommandActionKind = "execute" | "read" | "list" | "search" | "unknown";

export interface ToolConversationItem {
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: ToolConversationItemKind;
  status: ConversationItemStatus;
  title?: string;
  tool: ToolInvocation;
}

export type ToolConversationItemKind = "tool";

export interface ToolExecutionError {
  code?: string;
  message: string;
  retryable?: boolean;
}

export interface ToolFailureOutcome {
  kind: ToolFailureOutcomeKind;
  content: Array<ContentBlock>;
  error: ToolExecutionError;
  exitCode?: number;
  processId?: string;
}

export type ToolFailureOutcomeKind = "failure";

export type ToolInput = CommandToolInput | StructuredToolInput | OpaqueToolInput;

export interface ToolInvocation {
  callId: NativeResourceId;
  name: string;
  namespace?: string;
  category: ToolCategory;
  origin: ToolOrigin;
  input: ToolInput;
  outcome?: ToolOutcome;
  timing?: ToolTiming;
  annotations?: ToolAnnotations;
}

export interface ToolOrigin {
  kind: ToolOriginKind;
  name?: string;
}

export type ToolOriginKind = "builtin" | "mcp" | "plugin" | "server" | "custom" | "unknown";

export type ToolOutcome = ToolSuccessOutcome | ToolFailureOutcome;

export interface ToolSuccessOutcome {
  kind: ToolSuccessOutcomeKind;
  content: Array<ContentBlock>;
  exitCode?: number;
  processId?: string;
}

export type ToolSuccessOutcomeKind = "success";

export interface ToolTiming {
  startedAt?: TimestampMs;
  completedAt?: TimestampMs;
  durationMs?: number;
}

export interface TurnInput {
  kind: TurnInputKind;
  text: string;
}

export type TurnInputKind = "text";

export interface TurnInterruptRequest {
  conversation: RoutedResourceId;
  turn: RoutedResourceId;
}

export interface TurnInterruptResponse {
  turn: TurnTask;
}

export interface TurnOutputDeltaEvent {
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  itemId: NativeResourceId;
  contentId: NativeResourceId;
  kind: ConversationContentKind;
  delta: string;
}

export interface TurnSelection {
  accessModeId?: string;
  reasoningEffortId?: string;
  model?: ModelSelection;
}

export interface TurnSendCapabilities {
  accessMode?: ChoiceSet;
  reasoningEffort?: ChoiceSet;
  modelCatalog?: ModelCatalog;
}

export interface TurnSendRequest {
  conversation: RoutedResourceId;
  clientRequestId: RequestId;
  capabilityRevision: string;
  input: TurnInput;
  selection: TurnSelection;
}

export interface TurnSendResponse {
  accepted: boolean;
  turn: TurnTask;
  userItem: ConversationItem | null;
  effectiveSelection: TurnSelection;
}

export type TurnStatus = "queued" | "running" | "waiting-approval" | "completed" | "failed" | "interrupted";

export interface TurnTask {
  resource: RoutedResourceId;
  conversation: RoutedResourceId;
  status: TurnStatus;
  displaySummary?: string;
  startedAt?: TimestampMs;
  updatedAt?: TimestampMs;
  completedAt?: TimestampMs;
}

export interface TurnUpsertedEvent {
  turn: TurnTask;
}

export interface UnknownConversationItem {
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: UnknownConversationItemKind;
  status: ConversationItemStatus;
  title?: string;
}

export type UnknownConversationItemKind = "unknown";

export interface ProtocolRequestMap {
  "protocol.handshake": HandshakeRequest;
  "protocol.describe": ProtocolDescribeRequest;
  "event.subscribe": EventSubscribeRequest;
  "provider.list": ProviderListRequest;
  "provider.describe": ProviderDescribeRequest;
  "project.list": ProjectListRequest;
  "project.get": ProjectGetRequest;
  "project.create": ProjectCreateRequest;
  "project.update": ProjectUpdateRequest;
  "project.delete": ProjectDeleteRequest;
  "conversation.list": ConversationListRequest;
  "conversation.search": ConversationSearchRequest;
  "conversation.get": ConversationGetRequest;
  "conversation.markRead": ConversationMarkReadRequest;
  "conversation.acquireInteraction": ConversationAcquireInteractionRequest;
  "conversation.create": ConversationCreateRequest;
  "turn.send": TurnSendRequest;
  "turn.interrupt": TurnInterruptRequest;
  "approval.resolve": ApprovalResolveRequest;
}

export interface ProtocolResponseMap {
  "protocol.handshake": HandshakeResponse;
  "protocol.describe": ProtocolDescribeResponse;
  "event.subscribe": EventSubscribeResponse;
  "provider.list": ProviderListResponse;
  "provider.describe": ProviderDescribeResponse;
  "project.list": ProjectListResponse;
  "project.get": ProjectGetResponse;
  "project.create": ProjectCreateResponse;
  "project.update": ProjectUpdateResponse;
  "project.delete": ProjectDeleteResponse;
  "conversation.list": ConversationListResponse;
  "conversation.search": ConversationSearchResponse;
  "conversation.get": ConversationGetResponse;
  "conversation.markRead": ConversationMarkReadResponse;
  "conversation.acquireInteraction": ConversationAcquireInteractionResponse;
  "conversation.create": ConversationCreateResponse;
  "turn.send": TurnSendResponse;
  "turn.interrupt": TurnInterruptResponse;
  "approval.resolve": ApprovalResolveResponse;
}

export interface ProtocolEventMap {
  "project.changed": ProjectChangedEvent;
  "provider.changed": ProviderChangedEvent;
  "conversation.upserted": ConversationUpsertedEvent;
  "conversation.itemUpserted": ConversationItemUpsertedEvent;
  "conversation.activityChanged": ConversationActivityChangedEvent;
  "turn.upserted": TurnUpsertedEvent;
  "turn.outputDelta": TurnOutputDeltaEvent;
  "approval.requested": ApprovalRequestedEvent;
  "approval.resolved": ApprovalResolvedEvent;
}

export type ProtocolMethod = keyof ProtocolRequestMap;
export type ProtocolEventName = keyof ProtocolEventMap;
export type ProtocolRequest = {
  [M in ProtocolMethod]: { jsonrpc: "2.0"; id: RequestId; method: M; params: ProtocolRequestMap[M]; meta?: TraceContext }
}[ProtocolMethod];
export type ProtocolSuccessResponse<M extends ProtocolMethod = ProtocolMethod> = { jsonrpc: "2.0"; id: RequestId; result: ProtocolResponseMap[M] };
export type ProtocolErrorResponse = { jsonrpc: "2.0"; id: RequestId | null; error: RpcError };
export type ProtocolResponse<M extends ProtocolMethod = ProtocolMethod> = ProtocolSuccessResponse<M> | ProtocolErrorResponse;
export type ProtocolEvent = {
  [E in ProtocolEventName]: { jsonrpc: "2.0"; method: E; params: { eventCursor: EventCursor; payload: ProtocolEventMap[E] }; meta?: TraceContext }
}[ProtocolEventName];

export interface ProtocolTransport {
  request<M extends ProtocolMethod>(method: M, params: ProtocolRequestMap[M]): Promise<ProtocolResponseMap[M]>;
}
