// @generated by tools/protocol-codegen/generate.mjs from protocol/gateway/v1/manifest.json and protocol/gateway/v1/schema.json.
// DO NOT EDIT MANUALLY.

import type { ClientId, Cursor, DeviceId, EventCursor, NativeResourceId, PageInfo, ProtocolError, ProtocolVersion, ProviderInstanceId, ProviderPluginId, RequestId, RoutedResourceId, TimestampMs, VersionRange } from "../../codepet-core-sdk/src/generated";
export type { ClientId, Cursor, DeviceId, EventCursor, NativeResourceId, PageInfo, ProtocolError, ProtocolVersion, ProviderInstanceId, ProviderPluginId, RequestId, RoutedResourceId, TimestampMs, VersionRange } from "../../codepet-core-sdk/src/generated";

export const PROTOCOL_VERSION = 1 as const;
export const PROTOCOL_METHODS = ["protocol.handshake", "event.subscribe", "device.list", "provider.list", "conversation.list", "conversation.search", "conversation.get", "conversation.create", "turn.send", "turn.interrupt", "approval.resolve"] as const;
export const PROTOCOL_EVENTS = ["device.statusChanged", "provider.statusChanged", "conversation.upserted", "turn.upserted", "turn.outputDelta", "approval.requested", "approval.resolved"] as const;

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export interface Approval {
  resource: RoutedResourceId;
  conversation: RoutedResourceId;
  turn: RoutedResourceId;
  kind: string;
  title: string;
  description?: string;
  status: ApprovalStatus;
  decisions: Array<ApprovalDecision>;
  requestedAt?: TimestampMs;
  resolvedAt?: TimestampMs;
  decision?: ApprovalDecision;
}

export type ApprovalDecision = "approve" | "deny";

export interface ApprovalRequestedEvent {
  approval: Approval;
}

export interface ApprovalResolveRequest {
  approval: RoutedResourceId;
  decision: ApprovalDecision;
}

export interface ApprovalResolveResponse {
  approval: Approval;
}

export interface ApprovalResolvedEvent {
  approval: Approval;
}

export type ApprovalStatus = "pending" | "approved" | "denied" | "expired";

export interface ChoiceOption {
  id: string;
  displayName: string;
  description?: string;
  enabled?: boolean;
  disabledReason?: string;
}

export interface ChoiceSet {
  options: Array<ChoiceOption>;
  defaultId?: string;
}

export interface Conversation {
  resource: RoutedResourceId;
  title: string;
  preview?: string;
  status: ConversationStatus;
  permissionLevel?: string;
  model?: string;
  reasoningEffort?: string;
  selection?: TurnSelection;
  workspaceRoot?: string;
  createdAt?: TimestampMs;
  updatedAt?: TimestampMs;
  activeTurn?: TurnTask;
}

export interface ConversationContent {
  contentId: NativeResourceId;
  kind: ConversationContentKind;
  text: string;
}

export type ConversationContentKind = "text" | "reasoning-summary" | "command" | "output" | "activity-summary";

export interface ConversationCreateRequest {
  route: GatewayProviderRoute;
  title?: string;
  permissionLevel: string;
  model?: string;
  reasoningEffort?: string;
  workspaceRoot?: string;
}

export interface ConversationCreateResponse {
  conversation: Conversation;
}

export interface ConversationGetRequest {
  conversation: RoutedResourceId;
}

export interface ConversationGetResponse {
  conversation: Conversation;
  items: Array<ConversationItem>;
  snapshotCursor: EventCursor;
}

export interface ConversationItem {
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: ConversationItemKind;
  status: ConversationItemStatus;
  role?: ConversationItemRole;
  title?: string;
  contents: Array<ConversationContent>;
  relatedItem?: RoutedResourceId;
  approval?: Approval;
}

export type ConversationItemKind = "message" | "reasoning" | "command" | "file-change" | "tool" | "approval" | "unknown";

export type ConversationItemRole = "user" | "assistant";

export type ConversationItemStatus = "pending" | "running" | "completed" | "failed" | "interrupted" | "declined" | "approved" | "denied" | "expired" | "unknown";

export interface ConversationListRequest {
  route?: GatewayProviderRoute;
  cursor?: Cursor;
  limit?: number;
}

export interface ConversationListResponse {
  conversations: Array<Conversation>;
  pageInfo: PageInfo;
  snapshotCursor: EventCursor;
}

export interface ConversationSearchRequest {
  route: GatewayProviderRoute;
  searchTerm: string;
  cursor?: Cursor;
  limit?: number;
}

export interface ConversationSearchResponse {
  conversations: Array<Conversation>;
  pageInfo: PageInfo;
  snapshotCursor: EventCursor;
}

export type ConversationStatus = "idle" | "running" | "waiting-approval" | "waiting-user-input" | "error" | "archived";

export interface ConversationUpsertedEvent {
  conversation: Conversation;
}

export interface CurrentCredentialDeleteResponse {
  revoked: boolean;
}

export interface Device {
  deviceId: DeviceId;
  displayName: string;
  status: DeviceStatus;
  lastSeenAt?: TimestampMs;
}

export interface DeviceDescriptor {
  deviceName: string;
  operatingSystem: string;
  systemVersion: string;
}

export interface DeviceListRequest {

}

export interface DeviceListResponse {
  devices: Array<Device>;
}

export type DeviceStatus = "online" | "offline";

export interface DeviceStatusChangedEvent {
  device: Device;
  previousStatus?: DeviceStatus;
}

export interface EventSubscribeRequest {
  afterCursor: EventCursor;
}

export interface EventSubscribeResponse {
  subscribedAfterCursor: EventCursor;
}

export interface FlatModelCatalog {
  kind: FlatModelCatalogKind;
  models: Array<ChoiceOption>;
  defaultSelection?: FlatModelSelection;
}

export type FlatModelCatalogKind = "flat";

export interface FlatModelSelection {
  kind: FlatModelCatalogKind;
  modelId: string;
}

export interface GatewayCapabilities {
  revision: string;
  methods: Array<GatewayCapability>;
  turnSend?: TurnSendCapabilities;
}

export type GatewayCapability = "conversation.list" | "conversation.search" | "conversation.get" | "conversation.create" | "turn.send" | "turn.interrupt" | "approval.resolve";

export interface GatewayProviderRoute {
  deviceId: DeviceId;
  providerPluginId: ProviderPluginId;
  providerInstanceId: ProviderInstanceId;
}

export interface GroupedModelCatalog {
  kind: GroupedModelCatalogKind;
  providers: Array<GroupedModelProvider>;
  defaultSelection?: GroupedModelSelection;
}

export type GroupedModelCatalogKind = "grouped";

export interface GroupedModelProvider {
  id: string;
  displayName: string;
  description?: string;
  models: Array<ChoiceOption>;
}

export interface GroupedModelSelection {
  kind: GroupedModelCatalogKind;
  providerId: string;
  modelId: string;
}

export interface HandshakeRequest {
  clientId: ClientId;
  device: DeviceDescriptor;
  clientVersion: string;
  supportedVersions: VersionRange;
  lastEventCursor?: EventCursor;
}

export interface HandshakeResponse {
  selectedVersion: ProtocolVersion;
  serverName: string;
  serverVersion: string;
  device: RemoteHostIdentity;
  devices: Array<Device>;
  providers: Array<ProviderInstance>;
  eventCursor: EventCursor;
}

export interface HarnessDescriptor {
  id: string;
  displayName: string;
  version?: string;
}

export type ModelCatalog = FlatModelCatalog | GroupedModelCatalog;

export type ModelSelection = FlatModelSelection | GroupedModelSelection;

export interface PairingExchangeRequest {
  pairingSecret: string;
  clientId: ClientId;
  device: DeviceDescriptor;
}

export interface PairingExchangeResponse {
  device: RemoteHostIdentity;
  gatewayUrl: string;
  credential: string;
}

export interface PairingQrPayload {
  version: number;
  hostDeviceId: DeviceId;
  displayName: string;
  httpsBaseUrl: string;
  certSha256: string;
  pairingId: string;
  pairingSecret: string;
  expiresAt: TimestampMs;
}

export interface ProviderInstance {
  route: GatewayProviderRoute;
  pluginId: ProviderPluginId;
  displayName: string;
  version?: string;
  harness: HarnessDescriptor;
  status: ProviderStatus;
  capabilities: GatewayCapabilities;
}

export interface ProviderListRequest {
  deviceId?: DeviceId;
}

export interface ProviderListResponse {
  providers: Array<ProviderInstance>;
}

export type ProviderStatus = "disconnected" | "connecting" | "ready" | "unavailable" | "error";

export interface ProviderStatusChangedEvent {
  provider: ProviderInstance;
  previousStatus?: ProviderStatus;
}

export interface RemoteHostIdentity {
  deviceId: DeviceId;
  descriptor: DeviceDescriptor;
  identityFingerprint: string;
}

export interface TurnInput {
  kind: TurnInputKind;
  text: string;
}

export type TurnInputKind = "text";

export interface TurnInterruptRequest {
  conversation: RoutedResourceId;
  turn: RoutedResourceId;
}

export interface TurnInterruptResponse {
  turn: TurnTask;
}

export interface TurnOutputDeltaEvent {
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  itemId: NativeResourceId;
  contentId: NativeResourceId;
  kind: ConversationContentKind;
  delta: string;
}

export interface TurnSelection {
  accessModeId?: string;
  reasoningEffortId?: string;
  model?: ModelSelection;
}

export interface TurnSendCapabilities {
  accessMode?: ChoiceSet;
  reasoningEffort?: ChoiceSet;
  modelCatalog?: ModelCatalog;
}

export interface TurnSendRequest {
  route: GatewayProviderRoute;
  conversation: RoutedResourceId;
  clientRequestId: RequestId;
  capabilityRevision: string;
  input: TurnInput;
  selection: TurnSelection;
}

export interface TurnSendResponse {
  accepted: boolean;
  turn: TurnTask;
  userItem: ConversationItem | null;
  effectiveSelection: TurnSelection;
}

export type TurnStatus = "queued" | "running" | "waiting-approval" | "completed" | "failed" | "interrupted";

export interface TurnTask {
  resource: RoutedResourceId;
  conversation: RoutedResourceId;
  status: TurnStatus;
  displaySummary?: string;
  startedAt?: TimestampMs;
  updatedAt?: TimestampMs;
  completedAt?: TimestampMs;
}

export interface TurnUpsertedEvent {
  turn: TurnTask;
}

export interface ProtocolRequestMap {
  "protocol.handshake": HandshakeRequest;
  "event.subscribe": EventSubscribeRequest;
  "device.list": DeviceListRequest;
  "provider.list": ProviderListRequest;
  "conversation.list": ConversationListRequest;
  "conversation.search": ConversationSearchRequest;
  "conversation.get": ConversationGetRequest;
  "conversation.create": ConversationCreateRequest;
  "turn.send": TurnSendRequest;
  "turn.interrupt": TurnInterruptRequest;
  "approval.resolve": ApprovalResolveRequest;
}

export interface ProtocolResponseMap {
  "protocol.handshake": HandshakeResponse;
  "event.subscribe": EventSubscribeResponse;
  "device.list": DeviceListResponse;
  "provider.list": ProviderListResponse;
  "conversation.list": ConversationListResponse;
  "conversation.search": ConversationSearchResponse;
  "conversation.get": ConversationGetResponse;
  "conversation.create": ConversationCreateResponse;
  "turn.send": TurnSendResponse;
  "turn.interrupt": TurnInterruptResponse;
  "approval.resolve": ApprovalResolveResponse;
}

export interface ProtocolEventMap {
  "device.statusChanged": DeviceStatusChangedEvent;
  "provider.statusChanged": ProviderStatusChangedEvent;
  "conversation.upserted": ConversationUpsertedEvent;
  "turn.upserted": TurnUpsertedEvent;
  "turn.outputDelta": TurnOutputDeltaEvent;
  "approval.requested": ApprovalRequestedEvent;
  "approval.resolved": ApprovalResolvedEvent;
}

export type ProtocolMethod = keyof ProtocolRequestMap;
export type ProtocolEventName = keyof ProtocolEventMap;
export type ResponsePayload<T> = { status: "ok"; result: T } | { status: "error"; error: ProtocolError };

export type ProtocolRequest =
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "protocol.handshake"; params: HandshakeRequest }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "event.subscribe"; params: EventSubscribeRequest }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "device.list"; params: DeviceListRequest }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "provider.list"; params: ProviderListRequest }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "conversation.list"; params: ConversationListRequest }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "conversation.search"; params: ConversationSearchRequest }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "conversation.get"; params: ConversationGetRequest }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "conversation.create"; params: ConversationCreateRequest }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "turn.send"; params: TurnSendRequest }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "turn.interrupt"; params: TurnInterruptRequest }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "approval.resolve"; params: ApprovalResolveRequest };

export type ProtocolResponse =
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "protocol.handshake"; response: ResponsePayload<HandshakeResponse> }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "event.subscribe"; response: ResponsePayload<EventSubscribeResponse> }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "device.list"; response: ResponsePayload<DeviceListResponse> }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "provider.list"; response: ResponsePayload<ProviderListResponse> }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "conversation.list"; response: ResponsePayload<ConversationListResponse> }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "conversation.search"; response: ResponsePayload<ConversationSearchResponse> }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "conversation.get"; response: ResponsePayload<ConversationGetResponse> }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "conversation.create"; response: ResponsePayload<ConversationCreateResponse> }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "turn.send"; response: ResponsePayload<TurnSendResponse> }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "turn.interrupt"; response: ResponsePayload<TurnInterruptResponse> }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "approval.resolve"; response: ResponsePayload<ApprovalResolveResponse> };

export type ProtocolEvent =
  | { protocolVersion: ProtocolVersion; eventCursor: EventCursor; event: "device.statusChanged"; payload: DeviceStatusChangedEvent }
  | { protocolVersion: ProtocolVersion; eventCursor: EventCursor; event: "provider.statusChanged"; payload: ProviderStatusChangedEvent }
  | { protocolVersion: ProtocolVersion; eventCursor: EventCursor; event: "conversation.upserted"; payload: ConversationUpsertedEvent }
  | { protocolVersion: ProtocolVersion; eventCursor: EventCursor; event: "turn.upserted"; payload: TurnUpsertedEvent }
  | { protocolVersion: ProtocolVersion; eventCursor: EventCursor; event: "turn.outputDelta"; payload: TurnOutputDeltaEvent }
  | { protocolVersion: ProtocolVersion; eventCursor: EventCursor; event: "approval.requested"; payload: ApprovalRequestedEvent }
  | { protocolVersion: ProtocolVersion; eventCursor: EventCursor; event: "approval.resolved"; payload: ApprovalResolvedEvent };

export interface ProtocolClient {
  protocolHandshake(request: HandshakeRequest): Promise<HandshakeResponse>;
  eventSubscribe(request: EventSubscribeRequest): Promise<EventSubscribeResponse>;
  deviceList(request: DeviceListRequest): Promise<DeviceListResponse>;
  providerList(request: ProviderListRequest): Promise<ProviderListResponse>;
  conversationList(request: ConversationListRequest): Promise<ConversationListResponse>;
  conversationSearch(request: ConversationSearchRequest): Promise<ConversationSearchResponse>;
  conversationGet(request: ConversationGetRequest): Promise<ConversationGetResponse>;
  conversationCreate(request: ConversationCreateRequest): Promise<ConversationCreateResponse>;
  turnSend(request: TurnSendRequest): Promise<TurnSendResponse>;
  turnInterrupt(request: TurnInterruptRequest): Promise<TurnInterruptResponse>;
  approvalResolve(request: ApprovalResolveRequest): Promise<ApprovalResolveResponse>;
}

export interface ProtocolTransport {
  request<M extends ProtocolMethod>(method: M, params: ProtocolRequestMap[M]): Promise<ProtocolResponseMap[M]>;
}
