// @generated by tools/protocol-codegen/generate.mjs from protocol/gateway/v1/manifest.json and protocol/gateway/v1/schema.json.
// DO NOT EDIT MANUALLY.

import type { Approval, ApprovalDecision, Conversation, ConversationContentKind, ConversationCreateCapabilities, ConversationItem, ConversationReadState, Project, ProjectChangeType, ProjectRoot, ProviderAuthentication, ProviderId, ProviderUsage, TurnInput, TurnSelection, TurnSendCapabilities, TurnTask } from "../../codepet-agent-sdk/src/generated";
export type * from "../../codepet-agent-sdk/src/generated";
import type { ClientId, ConnectionStatus, Cursor, DeviceDescriptor, EventCursor, NativeResourceId, PageInfo, ProtocolError, ProtocolVersion, RequestId, RoutedResourceId, RpcError, TimestampMs, TraceContext, VersionRange } from "../../codepet-core-sdk/src/generated";
export type { ClientId, ConnectionStatus, Cursor, DeviceDescriptor, EventCursor, NativeResourceId, PageInfo, ProtocolError, ProtocolVersion, RequestId, RoutedResourceId, RpcError, TimestampMs, TraceContext, VersionRange } from "../../codepet-core-sdk/src/generated";

export const PROTOCOL_VERSION = 1 as const;
export const PROTOCOL_METHODS = ["conversation.recent", "protocol.ping", "protocol.handshake", "protocol.describe", "event.subscribe", "provider.list", "provider.describe", "project.list", "project.get", "project.create", "project.update", "project.delete", "conversation.list", "conversation.search", "conversation.get", "conversation.markRead", "conversation.acquireInteraction", "conversation.resume", "conversation.create", "turn.send", "turn.interrupt", "approval.resolve"] as const;
export const PROTOCOL_EVENTS = ["conversation.recentChanged", "project.changed", "provider.changed", "conversation.upserted", "conversation.itemUpserted", "conversation.activityChanged", "turn.upserted", "turn.outputDelta", "approval.requested", "approval.resolved"] as const;

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export interface ApprovalRequestedEvent {
  approval: Approval;
}

export interface ApprovalResolveRequest {
  approval: RoutedResourceId;
  decision: ApprovalDecision;
}

export interface ApprovalResolveResponse {
  approval: Approval;
}

export interface ApprovalResolvedEvent {
  approval: Approval;
}

export interface ConversationAcquireInteractionRequest {
  conversation: RoutedResourceId;
}

export interface ConversationAcquireInteractionResponse {
  selection: TurnSelection;
  leaseExpiresAt?: TimestampMs;
}

export interface ConversationActivityChangedEvent {
  conversation: RoutedResourceId;
  activityVersion: string;
}

export interface ConversationCreateRequest {
  providerId: ProviderId;
  title?: string;
  permissionLevel: string;
  model?: string;
  reasoningEffort?: string;
  workspaceRoot?: string;
  workspaceMode?: string;
  project?: RoutedResourceId;
}

export interface ConversationCreateResponse {
  conversation: Conversation;
}

export interface ConversationGetRequest {
  conversation: RoutedResourceId;
  cursor?: Cursor;
  limit?: number;
}

export interface ConversationGetResponse {
  conversation: Conversation;
  items: Array<ConversationItem>;
  pageInfo?: PageInfo;
  snapshotCursor: EventCursor;
}

export interface ConversationItemUpsertedEvent {
  item: ConversationItem;
}

export interface ConversationListRequest {
  providerId: ProviderId;
  projectFilter: ConversationProjectFilter;
  cursor?: Cursor;
  limit?: number;
}

export interface ConversationListResponse {
  conversations: Array<Conversation>;
  pageInfo: PageInfo;
  snapshotCursor: EventCursor;
}

export interface ConversationMarkReadRequest {
  conversation: RoutedResourceId;
  observedActivityVersion: string;
}

export interface ConversationMarkReadResponse {
  readState: ConversationReadState;
}

export type ConversationProjectFilter = ConversationProjectFilterAll | ConversationProjectFilterStandalone | ConversationProjectFilterProject;

export interface ConversationProjectFilterAll {
  kind: ConversationProjectFilterAllKind;
}

export type ConversationProjectFilterAllKind = "all";

export interface ConversationProjectFilterProject {
  kind: ConversationProjectFilterProjectKind;
  project: RoutedResourceId;
}

export type ConversationProjectFilterProjectKind = "project";

export interface ConversationProjectFilterStandalone {
  kind: ConversationProjectFilterStandaloneKind;
}

export type ConversationProjectFilterStandaloneKind = "standalone";

export interface ConversationRecentChangedEvent {
  providerId: ProviderId;
  revision: ConversationRecentRevision;
}

export interface ConversationRecentRequest {
  providerId: ProviderId;
  cursor?: Cursor;
  limit?: number;
}

export interface ConversationRecentResponse {
  conversations: Array<Conversation>;
  pageInfo: PageInfo;
  revision: ConversationRecentRevision;
  snapshotCursor: EventCursor;
}

export type ConversationRecentRevision = string;

export interface ConversationResumeRequest {
  conversation: RoutedResourceId;
  limit?: number;
}

export interface ConversationResumeResponse {
  interactionAcquired: boolean;
  interaction?: ConversationAcquireInteractionResponse;
  interactionError?: ProtocolError;
  history?: ConversationGetResponse;
  historyError?: ProtocolError;
}

export interface ConversationSearchRequest {
  providerId: ProviderId;
  searchTerm: string;
  cursor?: Cursor;
  limit?: number;
}

export interface ConversationSearchResponse {
  conversations: Array<Conversation>;
  pageInfo: PageInfo;
  snapshotCursor: EventCursor;
}

export interface ConversationUpsertedEvent {
  conversation: Conversation;
}

export interface EventSubscribeRequest {
  afterCursor: EventCursor;
}

export interface EventSubscribeResponse {
  subscribedAfterCursor: EventCursor;
}

export interface GatewayCapabilities {
  revision: string;
  methods: Array<GatewayCapability>;
  turnSend?: TurnSendCapabilities;
  conversationCreate?: ConversationCreateCapabilities;
}

export type GatewayCapability = "project.list" | "project.get" | "project.create" | "project.update" | "project.delete" | "conversation.list" | "conversation.search" | "conversation.get" | "conversation.create" | "turn.send" | "turn.interrupt" | "approval.resolve" | "conversation.recent";

export interface GatewayDevice {
  name: string;
  operatingSystem: string;
  systemVersion: string;
}

export interface GatewayProtocol {
  version: ProtocolVersion;
}

export interface HandshakeRequest {
  clientId: ClientId;
  device: DeviceDescriptor;
  clientVersion: string;
  supportedVersions: VersionRange;
  lastEventCursor?: EventCursor;
}

export interface HandshakeResponse {
  protocol: GatewayProtocol;
  device: GatewayDevice;
  providers: Array<ProviderSummary>;
  eventCursor: EventCursor;
}

export interface PingRequest {
  sequence: number;
}

export interface PingResponse {
  sequence: number;
  providers: Array<ProviderSummary>;
}

export interface ProjectChangedEvent {
  project: RoutedResourceId;
  changeType: ProjectChangeType;
}

export interface ProjectCreateRequest {
  providerId: ProviderId;
  idempotencyKey: RequestId;
  name: string;
  roots: Array<ProjectRoot>;
  metadata: Record<string, string>;
}

export interface ProjectCreateResponse {
  project: Project;
}

export interface ProjectDeleteRequest {
  project: RoutedResourceId;
}

export interface ProjectDeleteResponse {

}

export interface ProjectGetRequest {
  project: RoutedResourceId;
}

export interface ProjectGetResponse {
  project: Project;
}

export interface ProjectListRequest {
  providerId: ProviderId;
  cursor?: Cursor;
  limit?: number;
}

export interface ProjectListResponse {
  projects: Array<Project>;
  pageInfo: PageInfo;
  snapshotCursor: EventCursor;
}

export interface ProjectUpdateRequest {
  project: RoutedResourceId;
  name?: string;
  roots?: Array<ProjectRoot>;
  metadata?: Record<string, string>;
}

export interface ProjectUpdateResponse {
  project: Project;
}

export interface ProtocolDescribeRequest {

}

export interface ProtocolDescribeResponse {
  features: Array<ProtocolFeature>;
}

export type ProtocolFeature = "trace-context-v1";

export interface ProviderCapabilitiesSummary {
  revision: string;
}

export interface ProviderChangedEvent {
  provider: ProviderSummary;
}

export interface ProviderDescribeRequest {
  providerId: ProviderId;
}

export interface ProviderDescribeResponse {
  provider: ProviderSummary;
  capabilities: GatewayCapabilities;
}

export interface ProviderIdentity {
  displayName: string;
  icon?: string;
  defaultWorkspaceRoot?: string;
}

export interface ProviderListRequest {

}

export interface ProviderListResponse {
  providers: Array<ProviderSummary>;
}

export interface ProviderRuntime {
  connectionStatus?: ConnectionStatus;
  generation?: number;
  status: ProviderStatus;
  version?: string;
  executablePath?: string;
  authentication?: ProviderAuthentication;
  usage?: ProviderUsage;
}

export type ProviderStatus = "connecting" | "ready" | "stopped" | "unavailable" | "error";

export interface ProviderSummary {
  id: string;
  identity: ProviderIdentity;
  runtime: ProviderRuntime;
  capabilities: ProviderCapabilitiesSummary;
}

export interface TurnInterruptRequest {
  conversation: RoutedResourceId;
  turn: RoutedResourceId;
}

export interface TurnInterruptResponse {
  turn: TurnTask;
}

export interface TurnOutputDeltaEvent {
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  itemId: NativeResourceId;
  contentId: NativeResourceId;
  kind: ConversationContentKind;
  delta: string;
}

export interface TurnSendRequest {
  conversation: RoutedResourceId;
  clientRequestId: RequestId;
  capabilityRevision: string;
  input: TurnInput;
  selection: TurnSelection;
}

export interface TurnSendResponse {
  accepted: boolean;
  turn: TurnTask;
  userItem: ConversationItem | null;
  effectiveSelection: TurnSelection;
}

export interface TurnUpsertedEvent {
  turn: TurnTask;
}

export interface ProtocolRequestMap {
  "conversation.recent": ConversationRecentRequest;
  "protocol.ping": PingRequest;
  "protocol.handshake": HandshakeRequest;
  "protocol.describe": ProtocolDescribeRequest;
  "event.subscribe": EventSubscribeRequest;
  "provider.list": ProviderListRequest;
  "provider.describe": ProviderDescribeRequest;
  "project.list": ProjectListRequest;
  "project.get": ProjectGetRequest;
  "project.create": ProjectCreateRequest;
  "project.update": ProjectUpdateRequest;
  "project.delete": ProjectDeleteRequest;
  "conversation.list": ConversationListRequest;
  "conversation.search": ConversationSearchRequest;
  "conversation.get": ConversationGetRequest;
  "conversation.markRead": ConversationMarkReadRequest;
  "conversation.acquireInteraction": ConversationAcquireInteractionRequest;
  "conversation.resume": ConversationResumeRequest;
  "conversation.create": ConversationCreateRequest;
  "turn.send": TurnSendRequest;
  "turn.interrupt": TurnInterruptRequest;
  "approval.resolve": ApprovalResolveRequest;
}

export interface ProtocolResponseMap {
  "conversation.recent": ConversationRecentResponse;
  "protocol.ping": PingResponse;
  "protocol.handshake": HandshakeResponse;
  "protocol.describe": ProtocolDescribeResponse;
  "event.subscribe": EventSubscribeResponse;
  "provider.list": ProviderListResponse;
  "provider.describe": ProviderDescribeResponse;
  "project.list": ProjectListResponse;
  "project.get": ProjectGetResponse;
  "project.create": ProjectCreateResponse;
  "project.update": ProjectUpdateResponse;
  "project.delete": ProjectDeleteResponse;
  "conversation.list": ConversationListResponse;
  "conversation.search": ConversationSearchResponse;
  "conversation.get": ConversationGetResponse;
  "conversation.markRead": ConversationMarkReadResponse;
  "conversation.acquireInteraction": ConversationAcquireInteractionResponse;
  "conversation.resume": ConversationResumeResponse;
  "conversation.create": ConversationCreateResponse;
  "turn.send": TurnSendResponse;
  "turn.interrupt": TurnInterruptResponse;
  "approval.resolve": ApprovalResolveResponse;
}

export interface ProtocolEventMap {
  "conversation.recentChanged": ConversationRecentChangedEvent;
  "project.changed": ProjectChangedEvent;
  "provider.changed": ProviderChangedEvent;
  "conversation.upserted": ConversationUpsertedEvent;
  "conversation.itemUpserted": ConversationItemUpsertedEvent;
  "conversation.activityChanged": ConversationActivityChangedEvent;
  "turn.upserted": TurnUpsertedEvent;
  "turn.outputDelta": TurnOutputDeltaEvent;
  "approval.requested": ApprovalRequestedEvent;
  "approval.resolved": ApprovalResolvedEvent;
}

export type ProtocolMethod = keyof ProtocolRequestMap;
export type ProtocolEventName = keyof ProtocolEventMap;
export type ProtocolRequest = {
  [M in ProtocolMethod]: { jsonrpc: "2.0"; id: RequestId; method: M; params: ProtocolRequestMap[M]; meta?: TraceContext }
}[ProtocolMethod];
export type ProtocolSuccessResponse<M extends ProtocolMethod = ProtocolMethod> = { jsonrpc: "2.0"; id: RequestId; result: ProtocolResponseMap[M] };
export type ProtocolErrorResponse = { jsonrpc: "2.0"; id: RequestId | null; error: RpcError };
export type ProtocolResponse<M extends ProtocolMethod = ProtocolMethod> = ProtocolSuccessResponse<M> | ProtocolErrorResponse;
export type ProtocolEvent = {
  [E in ProtocolEventName]: { jsonrpc: "2.0"; method: E; params: { eventCursor: EventCursor; payload: ProtocolEventMap[E] }; meta?: TraceContext }
}[ProtocolEventName];

export interface ProtocolTransport {
  request<M extends ProtocolMethod>(method: M, params: ProtocolRequestMap[M]): Promise<ProtocolResponseMap[M]>;
}
