// @generated by tools/protocol-codegen/generate.mjs from protocol/pet/v1/manifest.json and protocol/pet/v1/schema.json.
// DO NOT EDIT MANUALLY.

use serde::{Deserialize, Serialize};
use std::future::Future;
use std::pin::Pin;

pub use codepet_core_sdk::{ClientId, JsonObject, ProtocolError, ProtocolVersion, RequestId, TimestampMs, VersionRange};

pub const PROTOCOL_VERSION: ProtocolVersion = 1;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum PetActionDecision {
    #[serde(rename = "approve")]
    Approve,
    #[serde(rename = "deny")]
    Deny,
}

pub type PetActionId = String;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum PetActionKind {
    #[serde(rename = "activate")]
    Activate,
    #[serde(rename = "reply")]
    Reply,
    #[serde(rename = "interrupt")]
    Interrupt,
    #[serde(rename = "resolve-approval")]
    ResolveApproval,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PetActionRequest {
    pub action_id: PetActionId,
    pub kind: PetActionKind,
    pub task_id: PetTaskId,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub approval_id: Option<PetApprovalId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<PetActionDecision>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PetActionResponse {
    pub accepted: bool,
    pub revision: PetRevision,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PetApproval {
    pub id: PetApprovalId,
    pub task_id: PetTaskId,
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub requested_at: TimestampMs,
}

pub type PetApprovalId = String;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PetInitializeRequest {
    pub client_id: ClientId,
    pub client_name: String,
    pub client_version: String,
    pub supported_versions: VersionRange,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PetInitializeResponse {
    pub selected_version: ProtocolVersion,
    pub snapshot: PetSnapshot,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PetPatch {
    pub base_revision: PetRevision,
    pub revision: PetRevision,
    pub operations: Vec<PetPatchOperation>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PetPatchEvent {
    pub patch: PetPatch,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PetPatchOperation {
    pub op: PetPatchOperationKind,
    pub path: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<JsonObject>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum PetPatchOperationKind {
    #[serde(rename = "add")]
    Add,
    #[serde(rename = "replace")]
    Replace,
    #[serde(rename = "remove")]
    Remove,
}

pub type PetRevision = u64;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PetSnapshot {
    pub revision: PetRevision,
    pub generated_at: TimestampMs,
    pub tasks: Vec<PetTask>,
    pub approvals: Vec<PetApproval>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PetSnapshotEvent {
    pub snapshot: PetSnapshot,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PetSnapshotRequest {

}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PetSnapshotResponse {
    pub snapshot: PetSnapshot,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PetTask {
    pub id: PetTaskId,
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    pub status: PetTaskStatus,
    pub updated_at: TimestampMs,
}

pub type PetTaskId = String;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum PetTaskStatus {
    #[serde(rename = "idle")]
    Idle,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "waiting-approval")]
    WaitingApproval,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "interrupted")]
    Interrupted,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProtocolMethod {
    #[serde(rename = "protocol.initialize")]
    ProtocolInitialize,
    #[serde(rename = "pet.snapshot")]
    PetSnapshot,
    #[serde(rename = "pet.action")]
    PetAction,
}

impl ProtocolMethod {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ProtocolInitialize => "protocol.initialize",
            Self::PetSnapshot => "pet.snapshot",
            Self::PetAction => "pet.action",
        }
    }
}

impl std::str::FromStr for ProtocolMethod {
    type Err = ();

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "protocol.initialize" => Ok(Self::ProtocolInitialize),
            "pet.snapshot" => Ok(Self::PetSnapshot),
            "pet.action" => Ok(Self::PetAction),
            _ => Err(()),
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProtocolEventName {
    #[serde(rename = "pet.snapshot")]
    PetSnapshot,
    #[serde(rename = "pet.patch")]
    PetPatch,
}

impl ProtocolEventName {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::PetSnapshot => "pet.snapshot",
            Self::PetPatch => "pet.patch",
        }
    }
}

impl std::str::FromStr for ProtocolEventName {
    type Err = ();

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "pet.snapshot" => Ok(Self::PetSnapshot),
            "pet.patch" => Ok(Self::PetPatch),
            _ => Err(()),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "status", rename_all = "camelCase")]
pub enum ResponsePayload<T> {
    Ok { result: T },
    Error { error: ProtocolError },
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "method")]
pub enum ProtocolRequest {
    #[serde(rename = "protocol.initialize")]
    ProtocolInitialize {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        params: PetInitializeRequest,
    },
    #[serde(rename = "pet.snapshot")]
    PetSnapshot {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        params: PetSnapshotRequest,
    },
    #[serde(rename = "pet.action")]
    PetAction {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        params: PetActionRequest,
    },
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "method")]
pub enum ProtocolResponse {
    #[serde(rename = "protocol.initialize")]
    ProtocolInitialize {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        response: ResponsePayload<PetInitializeResponse>,
    },
    #[serde(rename = "pet.snapshot")]
    PetSnapshot {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        response: ResponsePayload<PetSnapshotResponse>,
    },
    #[serde(rename = "pet.action")]
    PetAction {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        response: ResponsePayload<PetActionResponse>,
    },
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "event")]
pub enum ProtocolEvent {
    #[serde(rename = "pet.snapshot")]
    PetSnapshot {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        payload: PetSnapshotEvent,
    },
    #[serde(rename = "pet.patch")]
    PetPatch {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        payload: PetPatchEvent,
    },
}

pub type ProtocolFuture<'a, T> = Pin<Box<dyn Future<Output = Result<T, ProtocolError>> + Send + 'a>>;

pub trait ProtocolServer: Send + Sync {
    fn protocol_initialize<'a>(&'a self, _request: PetInitializeRequest) -> ProtocolFuture<'a, PetInitializeResponse> {
        Box::pin(async { Err(method_not_implemented("protocol.initialize")) })
    }

    fn pet_snapshot<'a>(&'a self, _request: PetSnapshotRequest) -> ProtocolFuture<'a, PetSnapshotResponse> {
        Box::pin(async { Err(method_not_implemented("pet.snapshot")) })
    }

    fn pet_action<'a>(&'a self, _request: PetActionRequest) -> ProtocolFuture<'a, PetActionResponse> {
        Box::pin(async { Err(method_not_implemented("pet.action")) })
    }
}

fn method_not_implemented(method: &str) -> ProtocolError {
    ProtocolError {
        code: "method_not_implemented".to_string(),
        message: format!("protocol method is not implemented: {method}"),
        retryable: false,
        details: None,
    }
}

pub async fn dispatch<S: ProtocolServer + ?Sized>(server: &S, request: ProtocolRequest) -> ProtocolResponse {
    match request {
        ProtocolRequest::ProtocolInitialize { protocol_version, id, params } => {
            let response = match server.protocol_initialize(params).await {
                Ok(result) => ResponsePayload::Ok { result },
                Err(error) => ResponsePayload::Error { error },
            };
            ProtocolResponse::ProtocolInitialize { protocol_version, id, response }
        },
        ProtocolRequest::PetSnapshot { protocol_version, id, params } => {
            let response = match server.pet_snapshot(params).await {
                Ok(result) => ResponsePayload::Ok { result },
                Err(error) => ResponsePayload::Error { error },
            };
            ProtocolResponse::PetSnapshot { protocol_version, id, response }
        },
        ProtocolRequest::PetAction { protocol_version, id, params } => {
            let response = match server.pet_action(params).await {
                Ok(result) => ResponsePayload::Ok { result },
                Err(error) => ResponsePayload::Error { error },
            };
            ProtocolResponse::PetAction { protocol_version, id, response }
        }
    }
}

pub struct ProtocolDispatcher<S> {
    server: S,
}

impl<S> ProtocolDispatcher<S> {
    pub const fn new(server: S) -> Self {
        Self { server }
    }

    pub const fn server(&self) -> &S {
        &self.server
    }
}

impl<S: ProtocolServer> ProtocolDispatcher<S> {
    pub async fn dispatch(&self, request: ProtocolRequest) -> ProtocolResponse {
        dispatch(&self.server, request).await
    }
}

pub type ProtocolTransportFuture<'a> = Pin<Box<dyn Future<Output = Result<serde_json::Value, ProtocolError>> + Send + 'a>>;

pub trait ProtocolTransport: Send + Sync {
    fn request<'a>(&'a self, method: ProtocolMethod, params: serde_json::Value) -> ProtocolTransportFuture<'a>;
}

pub struct ProtocolClient<T> {
    transport: T,
}

impl<T> ProtocolClient<T> {
    pub const fn new(transport: T) -> Self {
        Self { transport }
    }

    pub const fn transport(&self) -> &T {
        &self.transport
    }
}

impl<T: ProtocolTransport> ProtocolClient<T> {
    pub fn protocol_initialize<'a>(&'a self, request: PetInitializeRequest) -> ProtocolFuture<'a, PetInitializeResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ProtocolInitialize, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn pet_snapshot<'a>(&'a self, request: PetSnapshotRequest) -> ProtocolFuture<'a, PetSnapshotResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::PetSnapshot, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn pet_action<'a>(&'a self, request: PetActionRequest) -> ProtocolFuture<'a, PetActionResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::PetAction, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }
}

pub fn encode_request(value: &ProtocolRequest) -> Result<Vec<u8>, ProtocolError> {
    serde_json::to_vec(value).map_err(|error| codec_error("encode request", error))
}

pub fn decode_request(value: &[u8]) -> Result<ProtocolRequest, ProtocolError> {
    serde_json::from_slice(value).map_err(|error| codec_error("decode request", error))
}

pub fn encode_response(value: &ProtocolResponse) -> Result<Vec<u8>, ProtocolError> {
    serde_json::to_vec(value).map_err(|error| codec_error("encode response", error))
}

pub fn decode_response(value: &[u8]) -> Result<ProtocolResponse, ProtocolError> {
    serde_json::from_slice(value).map_err(|error| codec_error("decode response", error))
}

pub fn encode_event(value: &ProtocolEvent) -> Result<Vec<u8>, ProtocolError> {
    serde_json::to_vec(value).map_err(|error| codec_error("encode event", error))
}

pub fn decode_event(value: &[u8]) -> Result<ProtocolEvent, ProtocolError> {
    serde_json::from_slice(value).map_err(|error| codec_error("decode event", error))
}

fn codec_error(context: &str, error: serde_json::Error) -> ProtocolError {
    ProtocolError {
        code: "protocol_codec_error".to_string(),
        message: format!("{context}: {error}"),
        retryable: false,
        details: None,
    }
}
