// @generated by tools/protocol-codegen/generate.mjs from protocol/pet/v1/manifest.json and protocol/pet/v1/schema.json.
// DO NOT EDIT MANUALLY.

import type { ClientId, JsonObject, ProtocolError, ProtocolVersion, RequestId, TimestampMs, VersionRange } from "../../codepet-core-sdk/src/generated";
export type { ClientId, JsonObject, ProtocolError, ProtocolVersion, RequestId, TimestampMs, VersionRange } from "../../codepet-core-sdk/src/generated";

export const PROTOCOL_VERSION = 1 as const;
export const PROTOCOL_METHODS = ["protocol.initialize", "pet.snapshot", "pet.action", "source.setEnabled"] as const;
export const PROTOCOL_EVENTS = ["pet.snapshot", "pet.patch"] as const;

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export type PetActionDecision = "approve" | "deny";

export type PetActionId = string;

export type PetActionKind = "activate" | "reply" | "interrupt" | "resolve-approval";

export interface PetActionRequest {
  actionId: PetActionId;
  kind: PetActionKind;
  taskId: PetTaskId;
  message?: string;
  approvalId?: PetApprovalId;
  decision?: PetActionDecision;
}

export interface PetActionResponse {
  accepted: boolean;
  revision: PetRevision;
}

export interface PetApproval {
  id: PetApprovalId;
  taskId: PetTaskId;
  title: string;
  description?: string;
  requestedAt: TimestampMs;
}

export type PetApprovalId = string;

export interface PetInitializeRequest {
  clientId: ClientId;
  clientName: string;
  clientVersion: string;
  supportedVersions: VersionRange;
}

export interface PetInitializeResponse {
  selectedVersion: ProtocolVersion;
  snapshot: PetSnapshot;
}

export interface PetPatch {
  baseRevision: PetRevision;
  revision: PetRevision;
  operations: Array<PetPatchOperation>;
}

export interface PetPatchEvent {
  patch: PetPatch;
}

export interface PetPatchOperation {
  op: PetPatchOperationKind;
  path: string;
  value?: JsonObject;
}

export type PetPatchOperationKind = "add" | "replace" | "remove";

export type PetRevision = number;

export interface PetSnapshot {
  revision: PetRevision;
  generatedAt: TimestampMs;
  tasks: Array<PetTask>;
  approvals: Array<PetApproval>;
  sources?: Array<PetSource>;
}

export interface PetSnapshotEvent {
  snapshot: PetSnapshot;
}

export interface PetSnapshotRequest {

}

export interface PetSnapshotResponse {
  snapshot: PetSnapshot;
}

export interface PetSource {
  id: string;
  displayName: string;
  enabled: boolean;
  status: string;
  message: string;
}

export interface PetSourceSetEnabledRequest {
  sourceId: string;
  enabled: boolean;
}

export interface PetSourceSetEnabledResponse {
  source: PetSource;
}

export interface PetTask {
  id: PetTaskId;
  title: string;
  summary?: string;
  status: PetTaskStatus;
  updatedAt: TimestampMs;
  providerId?: string;
  cwd?: string;
  toolName?: string;
}

export type PetTaskId = string;

export type PetTaskStatus = "idle" | "running" | "waiting-approval" | "completed" | "failed" | "interrupted" | "waiting-input" | "unknown";

export interface ProtocolRequestMap {
  "protocol.initialize": PetInitializeRequest;
  "pet.snapshot": PetSnapshotRequest;
  "pet.action": PetActionRequest;
  "source.setEnabled": PetSourceSetEnabledRequest;
}

export interface ProtocolResponseMap {
  "protocol.initialize": PetInitializeResponse;
  "pet.snapshot": PetSnapshotResponse;
  "pet.action": PetActionResponse;
  "source.setEnabled": PetSourceSetEnabledResponse;
}

export interface ProtocolEventMap {
  "pet.snapshot": PetSnapshotEvent;
  "pet.patch": PetPatchEvent;
}

export type ProtocolMethod = keyof ProtocolRequestMap;
export type ProtocolEventName = keyof ProtocolEventMap;
export type ResponsePayload<T> = { status: "ok"; result: T } | { status: "error"; error: ProtocolError };

export type ProtocolRequest =
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "protocol.initialize"; params: PetInitializeRequest }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "pet.snapshot"; params: PetSnapshotRequest }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "pet.action"; params: PetActionRequest }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "source.setEnabled"; params: PetSourceSetEnabledRequest };

export type ProtocolResponse =
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "protocol.initialize"; response: ResponsePayload<PetInitializeResponse> }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "pet.snapshot"; response: ResponsePayload<PetSnapshotResponse> }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "pet.action"; response: ResponsePayload<PetActionResponse> }
  | { protocolVersion: ProtocolVersion; id: RequestId; method: "source.setEnabled"; response: ResponsePayload<PetSourceSetEnabledResponse> };

export type ProtocolEvent =
  | { protocolVersion: ProtocolVersion; event: "pet.snapshot"; payload: PetSnapshotEvent }
  | { protocolVersion: ProtocolVersion; event: "pet.patch"; payload: PetPatchEvent };

export interface ProtocolClient {
  protocolInitialize(request: PetInitializeRequest): Promise<PetInitializeResponse>;
  petSnapshot(request: PetSnapshotRequest): Promise<PetSnapshotResponse>;
  petAction(request: PetActionRequest): Promise<PetActionResponse>;
  sourceSetEnabled(request: PetSourceSetEnabledRequest): Promise<PetSourceSetEnabledResponse>;
}

export interface ProtocolTransport {
  request<M extends ProtocolMethod>(method: M, params: ProtocolRequestMap[M]): Promise<ProtocolResponseMap[M]>;
}
