// Run with CODEPET_QA_NODE_MODULES pointing at a Playwright installation and Vite on port 1427.
import { createRequire } from 'node:module';
import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
const require = createRequire(import.meta.url);
const { chromium } = require(resolve(process.env.CODEPET_QA_NODE_MODULES, 'playwright'));
const output = resolve('artifacts/task-lineage-qa');
await mkdir(output, { recursive: true });
const url = 'http://127.0.0.1:1427/frontend/qa/task-lineage.html';
let server;
if (!await fetch(url).then(response => response.ok).catch(() => false)) {
  server = spawn(process.execPath, [resolve('node_modules/vite/bin/vite.js'), '--host', '127.0.0.1', '--port', '1427'], { stdio: 'ignore', windowsHide: true });
  for (let attempt = 0; attempt < 100; attempt++) {
    if (await fetch(url).then(response => response.ok).catch(() => false)) break;
    await new Promise(resolve => setTimeout(resolve, 100));
  }
}
const browser = await chromium.launch({ channel: process.env.CODEPET_QA_BROWSER || (process.platform === 'win32' ? 'msedge' : undefined), headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 });
  await page.getByText('任务抽取只把用户消息和 AI 正文作为对象，工具执行不要。', { exact: true }).waitFor();
  assert.equal(await page.locator('.node').count(), 3, 'Task tab opens the visualization by default');
  await page.screenshot({ path: resolve(output, 'conversation.png'), fullPage: true });
  assert.equal(await page.getByLabel('模型', { exact: true }).count(), 0);
  assert.equal(await page.getByRole('navigation', { name: '主导航' }).getByRole('button').count(), 6);
  assert.ok(await page.getByRole('button', { name: '后退', exact: true }).isDisabled());
  await page.getByRole('button', { name: '设置', exact: true }).click();
  await page.getByRole('navigation', { name: '设置分区' }).getByRole('button', { name: '任务抽取', exact: true }).waitFor();
  await page.getByLabel('模型', { exact: true }).fill('haiku');
  await page.getByLabel('提取任务的提示词').fill('将实现与验证归入同一任务');
  await page.getByLabel('抽取 Skill', { exact: true }).selectOption('reconcile-tasks');
  await page.getByRole('button', { name: '保存 Agent 设置', exact: true }).click();
  await page.getByText('已保存', { exact: true }).waitFor();
  await page.screenshot({ path: resolve(output, 'extraction-settings.png'), fullPage: true });
  await page.setViewportSize({ width: 480, height: 700 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.getByLabel('提取任务的提示词').focus();
  assert.equal(await page.getByLabel('提取任务的提示词').evaluate(e => e === document.activeElement), true);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByLabel('自动提取', { exact: true }).check();
  await page.getByLabel('自动提取间隔（秒）', { exact: true }).fill('120');
  await page.getByLabel('推理强度', { exact: true }).selectOption('medium');
  await page.getByRole('button', { name: '保存 Agent 设置', exact: true }).click();
  await page.getByText('已保存', { exact: true }).waitFor();
  await page.getByRole('button', { name: '后退', exact: true }).click();
  await page.getByRole('navigation', { name: '主导航' }).waitFor();
  await page.getByRole('button', { name: '前进', exact: true }).click();
  await page.getByLabel('推理强度', { exact: true }).waitFor();
  assert.equal(await page.getByLabel('推理强度', { exact: true }).inputValue(), 'medium');
  assert.equal(await page.getByLabel('自动提取间隔（秒）', { exact: true }).inputValue(), '120');
  assert.ok(await page.getByLabel('自动提取', { exact: true }).isChecked());
  await page.getByLabel('提取任务的提示词').waitFor();
  assert.equal(await page.getByLabel('提取任务的提示词').inputValue(), '将实现与验证归入同一任务');
  await page.getByRole('button', { name: '后退', exact: true }).click();
  await page.getByText('任务抽取只把用户消息和 AI 正文作为对象，工具执行不要。', { exact: true }).waitFor();
  await page.getByRole('button', { name: '收起导航栏', exact: true }).click();
  const widths = await page.evaluate(async () => {
    const values = []; for (let i = 0; i < 20; i++) { await new Promise(requestAnimationFrame); values.push(parseFloat(getComputedStyle(document.querySelector('.app-shell')).gridTemplateColumns)); } return values;
  });
  assert.ok(widths.some(width => width > 0 && width < 192), 'Sidebar width should animate through intermediate values');
  assert.ok(await page.locator('#main-sidebar').evaluate(e => e.inert));
  await page.getByRole('button', { name: '展开导航栏', exact: true }).click();
  await page.locator('#main-sidebar').waitFor({ state: 'visible' });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  assert.equal(await page.locator('.app-shell').evaluate(e => getComputedStyle(e).transitionDuration), '0s');
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.getByRole('button', { name: '手动整理历史', exact: true }).click();
  await page.getByRole('button', { name: '整理中…', exact: true }).waitFor();
  await page.getByRole('button', { name: '手动整理历史', exact: true }).waitFor();
  await page.getByText(/整理历史 · 1 次运行/).click();
  await page.getByText(/手动 · 已完成 · 全部近期历史/).waitFor();
  await page.getByRole('complementary', { name: '对话与任务导航' }).getByRole('button', { name: '任务', exact: true }).click();
  await page.getByRole('complementary', { name: '对话与任务导航' }).getByRole('button', { name: /任务谱系第一版/ }).click();
  await page.locator('.node').first().waitFor();
  assert.equal(await page.locator('.node').count(), 3);
  await page.getByRole('button', { name: '申请任务工作区', exact: true }).click();
  await page.getByText('任务工作区：/fixture/.codepair/workspaces/tasks/task', { exact: true }).waitFor();
  await page.locator('.node').nth(1).click();
  await page.getByText('三项来源回归测试已通过，证据位置保持稳定。', { exact: true }).waitFor();
  await page.screenshot({ path: resolve(output, 'graph.png'), fullPage: true });
  const selected = await page.locator('.node.selected strong').textContent();
  await page.getByRole('button', { name: '时间泳道', exact: true }).click();
  assert.equal(await page.locator('.node.selected strong').textContent(), selected);
  await page.locator('.node').first().focus();
  assert.equal(await page.locator('.node.same-thread').count(), 2);
  await page.screenshot({ path: resolve(output, 'swimlane.png'), fullPage: true });
  await page.getByRole('button', { name: '标记已完成', exact: true }).click();
  await page.getByRole('button', { name: '重新打开', exact: true }).waitFor();
  for (const width of [980, 820, 480]) {
    await page.setViewportSize({ width, height: 700 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Horizontal page overflow at ${width}`);
    await page.screenshot({ path: resolve(output, `width-${width}.png`), fullPage: true });
    const editor = page.getByRole('complementary', { name: '事实与原始消息' }).getByRole('textbox');
    await editor.fill('继续验证当前线程');
    const send = page.getByRole('button', { name: '发送消息', exact: true });
    await send.scrollIntoViewIfNeeded();
    assert.ok(await send.evaluate(button => { const rect = button.getBoundingClientRect(); return button.contains(document.elementFromPoint(rect.x + rect.width / 2, rect.y + rect.height / 2)); }), `Send action clipped at ${width}`);
  }
  await page.getByRole('button', { name: '发送消息', exact: true }).click();
  await page.getByRole('button', { name: '标记已完成', exact: true }).waitFor();
  assert.equal(await page.getByLabel('后台更新', { exact: true }).count(), 0);
  const mac = await browser.newPage({ viewport: { width: 980, height: 700 }, userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/130.0.0.0 Safari/537.36' });
  await mac.goto(url, { waitUntil: 'domcontentloaded', timeout: 60000 });
  const controls = mac.locator('.window-navigation-controls');
  await controls.waitFor();
  const before = await controls.boundingBox();
  const buttons = await controls.locator('button').evaluateAll(items => items.map(item => { const r = item.getBoundingClientRect(); return {x:r.x,y:r.y,width:r.width}; }));
  assert.ok(buttons[1].x >= buttons[0].x + buttons[0].width && buttons[2].x >= buttons[1].x + buttons[1].width, 'Toolbar actions must not overlap on macOS');
  await mac.getByRole('button', { name: '收起导航栏', exact: true }).click();
  const anchors = await controls.evaluate(async element => { const positions = []; for (let i=0;i<20;i++) { await new Promise(requestAnimationFrame); positions.push(element.getBoundingClientRect().x); } return positions; });
  assert.ok(anchors.every(x => Math.abs(x-before.x)<1), 'macOS anchor must stay fixed throughout collapse');
  await mac.getByRole('button', { name: '展开导航栏', exact: true }).click();
  await mac.close();
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ passed: ['conversation', 'settings navigation and sections', 'settings and skill selection', 'schedule settings', 'sidebar animation and reduced motion', 'async extraction job', 'task workspace', 'node evidence', 'diagram selection', 'keyboard highlight', 'manual acceptance', 'responsive widths'], output }));
} finally { await browser.close(); server?.kill(); }
