// @generated by tools/protocol-codegen/generate.mjs from protocol/agent/v1/manifest.json and protocol/agent/v1/schema.json.
// DO NOT EDIT MANUALLY.

import type { JsonObject, NativeResourceId, RoutedResourceId, TimestampMs } from "../../codepet-core-sdk/src/generated";
export type { JsonObject, NativeResourceId, RoutedResourceId, TimestampMs } from "../../codepet-core-sdk/src/generated";

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export interface ActivitySummaryContentBlock {
  contentId: NativeResourceId;
  kind: ActivitySummaryContentBlockKind;
  text: string;
  truncation?: ContentTruncation;
}

export type ActivitySummaryContentBlockKind = "activity-summary";

export interface Approval {
  resource: RoutedResourceId;
  conversation: RoutedResourceId;
  turn: RoutedResourceId;
  kind: string;
  title: string;
  description?: string;
  status: ApprovalStatus;
  decisions: Array<ApprovalDecision>;
  requestedAt?: TimestampMs;
  resolvedAt?: TimestampMs;
  decision?: ApprovalDecision;
}

export interface ApprovalConversationItem {
  _meta?: JsonObject;
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: ApprovalConversationItemKind;
  status: ConversationItemStatus;
  title?: string;
  relatedItem?: RoutedResourceId;
  approval: Approval;
}

export type ApprovalConversationItemKind = "approval";

export type ApprovalDecision = "approve" | "deny";

export type ApprovalStatus = "pending" | "approved" | "denied" | "expired";

export interface AudioContentBlock {
  contentId: NativeResourceId;
  kind: AudioContentBlockKind;
  uri: string;
  mimeType?: string;
  name?: string;
  truncation?: ContentTruncation;
}

export type AudioContentBlockKind = "audio";

export interface ChoiceOption {
  id: ProviderId;
  displayName: string;
  description?: string;
  enabled?: boolean;
  disabledReason?: string;
}

export interface ChoiceSet {
  options: Array<ChoiceOption>;
  defaultId?: string;
}

export interface CommandConversationItem {
  _meta?: JsonObject;
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: CommandConversationItemKind;
  status: ConversationItemStatus;
  title?: string;
  tool: ToolInvocation;
}

export type CommandConversationItemKind = "command";

export interface CommandToolInput {
  kind: CommandToolInputKind;
  command: string;
  cwd?: string;
  shell?: string;
  truncation?: ContentTruncation;
  actions?: Array<ToolCommandAction>;
}

export type CommandToolInputKind = "command";

export type ContentBlock = TextContentBlock | ReasoningSummaryContentBlock | OutputContentBlock | ActivitySummaryContentBlock | StructuredJsonContentBlock | ImageContentBlock | AudioContentBlock | ResourceLinkContentBlock | EmbeddedResourceContentBlock;

export interface ContentTruncation {
  originalBytes: number;
  retainedBytes: number;
  strategy: ContentTruncationStrategy;
}

export type ContentTruncationStrategy = "head" | "tail" | "head-tail" | "structural-preview";

export interface Conversation {
  resource: RoutedResourceId;
  project: RoutedResourceId | null;
  title: string;
  preview?: string;
  status: ConversationStatus;
  permissionLevel?: string;
  model?: string;
  reasoningEffort?: string;
  selection?: TurnSelection;
  workspaceRoot?: string;
  createdAt?: TimestampMs;
  updatedAt?: TimestampMs;
  activeTurn?: TurnTask;
  readState?: ConversationReadState;
}

export type ConversationContentKind = "text" | "reasoning-summary" | "output" | "activity-summary" | "structured-json" | "image" | "audio" | "resource-link" | "embedded-resource";

export interface ConversationCreateCapabilities {
  supportsTitle: boolean;
  selection?: TurnSendCapabilities;
  workspaceMode?: ChoiceSet;
}

export type ConversationItem = MessageConversationItem | ReasoningConversationItem | CommandConversationItem | FileChangeConversationItem | ToolConversationItem | ApprovalConversationItem | UnknownConversationItem;

export type ConversationItemRole = "user" | "assistant";

export type ConversationItemStatus = "pending" | "running" | "completed" | "failed" | "interrupted" | "declined" | "approved" | "denied" | "expired" | "unknown";

export interface ConversationReadState {
  unread: boolean;
  activityVersion: string;
}

export type ConversationStatus = "idle" | "running" | "waiting-approval" | "waiting-user-input" | "error" | "archived";

export interface EmbeddedResourceContentBlock {
  contentId: NativeResourceId;
  kind: EmbeddedResourceContentBlockKind;
  text: string;
  mimeType?: string;
  name?: string;
  truncation?: ContentTruncation;
}

export type EmbeddedResourceContentBlockKind = "embedded-resource";

export interface FileChangeConversationItem {
  _meta?: JsonObject;
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: FileChangeConversationItemKind;
  status: ConversationItemStatus;
  title?: string;
  contents: Array<ContentBlock>;
}

export type FileChangeConversationItemKind = "file-change";

export interface FlatModelCatalog {
  kind: FlatModelCatalogKind;
  models: Array<ChoiceOption>;
  defaultSelection?: FlatModelSelection;
}

export type FlatModelCatalogKind = "flat";

export interface FlatModelSelection {
  kind: FlatModelCatalogKind;
  modelId: string;
}

export interface GroupedModelCatalog {
  kind: GroupedModelCatalogKind;
  providers: Array<GroupedModelProvider>;
  defaultSelection?: GroupedModelSelection;
}

export type GroupedModelCatalogKind = "grouped";

export interface GroupedModelProvider {
  id: string;
  displayName: string;
  description?: string;
  models: Array<ChoiceOption>;
}

export interface GroupedModelSelection {
  kind: GroupedModelCatalogKind;
  providerId: string;
  modelId: string;
}

export interface ImageContentBlock {
  contentId: NativeResourceId;
  kind: ImageContentBlockKind;
  uri: string;
  mimeType?: string;
  name?: string;
  truncation?: ContentTruncation;
}

export type ImageContentBlockKind = "image";

export interface MessageConversationItem {
  _meta?: JsonObject;
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: MessageConversationItemKind;
  status: ConversationItemStatus;
  role: ConversationItemRole;
  contents: Array<ContentBlock>;
}

export type MessageConversationItemKind = "message";

export type ModelCatalog = FlatModelCatalog | GroupedModelCatalog;

export type ModelSelection = FlatModelSelection | GroupedModelSelection;

export interface OpaqueToolInput {
  kind: OpaqueToolInputKind;
  value: string;
  mimeType?: string;
  truncation?: ContentTruncation;
}

export type OpaqueToolInputKind = "opaque";

export interface OutputContentBlock {
  contentId: NativeResourceId;
  kind: OutputContentBlockKind;
  text: string;
  truncation?: ContentTruncation;
}

export type OutputContentBlockKind = "output";

export interface Project {
  resource: RoutedResourceId;
  name: string;
  roots: Array<ProjectRoot>;
  metadata: Record<string, string>;
  position: number;
  createdAt: TimestampMs;
  updatedAt: TimestampMs;
}

export type ProjectChangeType = "created" | "updated" | "deleted";

export interface ProjectRoot {
  path: string;
}

export interface ProviderAuthentication {
  status: ProviderAuthenticationStatus;
  displayText?: string;
}

export type ProviderAuthenticationStatus = "unknown" | "signed-in" | "signed-out" | "expired" | "error" | "unsupported";

export type ProviderId = string;

export interface ProviderUsage {
  displayText: string;
  observedAt?: TimestampMs;
  details?: Array<ProviderUsageDetail>;
}

export interface ProviderUsageDetail {
  namespace: string;
  schemaVersion: string;
  data: JsonObject;
}

export interface ReasoningConversationItem {
  _meta?: JsonObject;
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: ReasoningConversationItemKind;
  status: ConversationItemStatus;
  contents: Array<ContentBlock>;
}

export type ReasoningConversationItemKind = "reasoning";

export interface ReasoningSummaryContentBlock {
  contentId: NativeResourceId;
  kind: ReasoningSummaryContentBlockKind;
  text: string;
  truncation?: ContentTruncation;
}

export type ReasoningSummaryContentBlockKind = "reasoning-summary";

export interface ResourceLinkContentBlock {
  contentId: NativeResourceId;
  kind: ResourceLinkContentBlockKind;
  uri: string;
  name?: string;
  mimeType?: string;
  truncation?: ContentTruncation;
}

export type ResourceLinkContentBlockKind = "resource-link";

export interface StructuredJsonContentBlock {
  contentId: NativeResourceId;
  kind: StructuredJsonContentBlockKind;
  value: JsonObject;
  truncation?: ContentTruncation;
}

export type StructuredJsonContentBlockKind = "structured-json";

export interface StructuredToolInput {
  kind: StructuredToolInputKind;
  value: JsonObject;
  truncation?: ContentTruncation;
}

export type StructuredToolInputKind = "structured";

export interface TextContentBlock {
  contentId: NativeResourceId;
  kind: TextContentBlockKind;
  text: string;
  truncation?: ContentTruncation;
}

export type TextContentBlockKind = "text";

export interface ToolAnnotations {
  readOnly?: boolean;
  destructive?: boolean;
  idempotent?: boolean;
  openWorld?: boolean;
}

export type ToolCategory = "command" | "read" | "write" | "search" | "web" | "agent" | "computer" | "media" | "other";

export interface ToolCommandAction {
  kind: ToolCommandActionKind;
  command: string;
  name?: string;
  path?: string;
  query?: string;
}

export type ToolCommandActionKind = "execute" | "read" | "list" | "search" | "unknown";

export interface ToolConversationItem {
  _meta?: JsonObject;
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: ToolConversationItemKind;
  status: ConversationItemStatus;
  title?: string;
  tool: ToolInvocation;
}

export type ToolConversationItemKind = "tool";

export interface ToolExecutionError {
  code?: string;
  message: string;
  retryable?: boolean;
}

export interface ToolFailureOutcome {
  kind: ToolFailureOutcomeKind;
  content: Array<ContentBlock>;
  error: ToolExecutionError;
  exitCode?: number;
  processId?: string;
}

export type ToolFailureOutcomeKind = "failure";

export type ToolInput = CommandToolInput | StructuredToolInput | OpaqueToolInput;

export interface ToolInvocation {
  callId: NativeResourceId;
  name: string;
  namespace?: string;
  category: ToolCategory;
  origin: ToolOrigin;
  input: ToolInput;
  outcome?: ToolOutcome;
  timing?: ToolTiming;
  annotations?: ToolAnnotations;
}

export interface ToolOrigin {
  kind: ToolOriginKind;
  name?: string;
}

export type ToolOriginKind = "builtin" | "mcp" | "plugin" | "server" | "custom" | "unknown";

export type ToolOutcome = ToolSuccessOutcome | ToolFailureOutcome;

export interface ToolSuccessOutcome {
  kind: ToolSuccessOutcomeKind;
  content: Array<ContentBlock>;
  exitCode?: number;
  processId?: string;
}

export type ToolSuccessOutcomeKind = "success";

export interface ToolTiming {
  startedAt?: TimestampMs;
  completedAt?: TimestampMs;
  durationMs?: number;
}

export interface TurnInput {
  kind: TurnInputKind;
  text: string;
}

export type TurnInputKind = "text";

export interface TurnSelection {
  accessModeId?: string;
  reasoningEffortId?: string;
  model?: ModelSelection;
}

export interface TurnSendCapabilities {
  accessMode?: ChoiceSet;
  reasoningEffort?: ChoiceSet;
  modelCatalog?: ModelCatalog;
}

export type TurnStatus = "queued" | "running" | "waiting-approval" | "completed" | "failed" | "interrupted";

export interface TurnTask {
  resource: RoutedResourceId;
  conversation: RoutedResourceId;
  status: TurnStatus;
  displaySummary?: string;
  startedAt?: TimestampMs;
  updatedAt?: TimestampMs;
  completedAt?: TimestampMs;
}

export interface UnknownConversationItem {
  _meta?: JsonObject;
  resource: RoutedResourceId;
  turn: RoutedResourceId;
  conversation: RoutedResourceId;
  kind: UnknownConversationItemKind;
  status: ConversationItemStatus;
  title?: string;
}

export type UnknownConversationItemKind = "unknown";
