// @generated by tools/protocol-codegen/generate.mjs from protocol/core/v1/manifest.json and protocol/core/v1/schema.json.
// DO NOT EDIT MANUALLY.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;


pub type ClientId = String;

pub type Cursor = String;

pub type DeviceId = String;

pub type EventCursor = String;

pub type EventSequence = u64;

pub type JsonObject = BTreeMap<String, serde_json::Value>;

pub type NativeResourceId = String;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PageInfo {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<Cursor>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PageRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<Cursor>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<u64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProtocolError {
    pub code: String,
    pub message: String,
    pub retryable: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<JsonObject>,
}

pub type ProtocolVersion = u32;

pub type ProviderInstanceId = String;

pub type ProviderPluginId = String;

pub type RequestId = String;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct RoutedResourceId {
    pub device_id: DeviceId,
    pub provider_plugin_id: ProviderPluginId,
    pub provider_instance_id: ProviderInstanceId,
    pub native_resource_id: NativeResourceId,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct RpcError {
    pub code: i64,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<JsonObject>,
}

pub type TimestampMs = u64;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct VersionRange {
    pub min_version: ProtocolVersion,
    pub max_version: ProtocolVersion,
}
