// @generated by tools/protocol-codegen/generate.mjs from protocol/core/v1/manifest.json and protocol/core/v1/schema.json.
// DO NOT EDIT MANUALLY.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;


pub const CORE_SCHEMA_VERSION: u64 = 1;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ClientConnectionInfo {
    pub connection_id: String,
    pub client_id: ClientId,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ClientConnectionsSnapshot {
    pub revision: u64,
    pub connections: Vec<ClientConnectionInfo>,
}

pub type ClientId = String;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConnectionStatus {
    #[serde(rename = "connecting")]
    Connecting,
    #[serde(rename = "online")]
    Online,
    #[serde(rename = "offline")]
    Offline,
}

pub type Cursor = String;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct DeviceDescriptor {
    pub device_name: String,
    pub operating_system: String,
    pub system_version: String,
}

pub type DeviceId = String;

pub type EventCursor = String;

pub type EventSequence = u64;

pub type JsonObject = BTreeMap<String, serde_json::Value>;

pub type NativeResourceId = String;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PageInfo {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<Cursor>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct PageRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<Cursor>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<u64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProtocolError {
    pub code: String,
    pub message: String,
    pub retryable: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub details: Option<JsonObject>,
}

pub type ProtocolVersion = u32;

pub type ProviderInstanceId = String;

pub type ProviderPluginId = String;

pub type RequestId = String;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct RoutedResourceId {
    pub provider_id: String,
    pub native_resource_id: NativeResourceId,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct RpcError {
    pub code: i64,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<JsonObject>,
}

pub type TimestampMs = u64;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TraceContext {
    pub traceparent: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tracestate: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct VersionRange {
    pub min_version: ProtocolVersion,
    pub max_version: ProtocolVersion,
}
