// @generated by tools/protocol-codegen/generate.mjs from protocol/desktop/v0/manifest.json and protocol/desktop/v0/schema.json.
// DO NOT EDIT MANUALLY.

use serde::{Deserialize, Serialize};
use std::future::Future;
use std::pin::Pin;

pub use codepet_core_sdk::{Cursor, EventSequence, JsonObject, ProtocolError, ProtocolVersion, RequestId, TimestampMs};

pub const PROTOCOL_VERSION: ProtocolVersion = 0;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct Approval {
    pub id: String,
    pub provider_id: String,
    pub conversation_id: String,
    pub turn_id: String,
    pub kind: String,
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub status: ApprovalStatus,
    pub decisions: Vec<ApprovalDecision>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub requested_at: Option<TimestampMs>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub resolved_at: Option<TimestampMs>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision: Option<ApprovalDecision>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extension: Option<ProviderExtension>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ApprovalDecision {
    #[serde(rename = "approve")]
    Approve,
    #[serde(rename = "deny")]
    Deny,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ApprovalRequestedEvent {
    pub approval: Approval,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ApprovalResolveRequest {
    pub provider_id: String,
    pub approval_id: String,
    pub decision: ApprovalDecision,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ApprovalResolveResponse {
    pub approval: Approval,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ApprovalResolvedEvent {
    pub approval: Approval,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ApprovalStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "denied")]
    Denied,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct Conversation {
    pub id: String,
    pub provider_id: String,
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub preview: Option<String>,
    pub status: ConversationStatus,
    pub permission_level: PermissionLevel,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_effort: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workspace_root: Option<String>,
    pub created_at: TimestampMs,
    pub updated_at: TimestampMs,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub active_turn: Option<TurnTask>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extension: Option<ProviderExtension>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationCreateRequest {
    pub provider_id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    pub permission_level: PermissionLevel,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_effort: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub workspace_root: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationCreateResponse {
    pub conversation: Conversation,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationGetRequest {
    pub provider_id: String,
    pub conversation_id: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationGetResponse {
    pub conversation: Conversation,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationListRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cursor: Option<Cursor>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub limit: Option<u64>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationListResponse {
    pub conversations: Vec<Conversation>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<Cursor>,
    pub event_sequence: EventSequence,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ConversationStatus {
    #[serde(rename = "idle")]
    Idle,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "waiting-approval")]
    WaitingApproval,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "archived")]
    Archived,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ConversationUpsertedEvent {
    pub conversation: Conversation,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct HandshakeRequest {
    pub client_name: String,
    pub client_version: String,
    pub min_protocol_version: ProtocolVersion,
    pub max_protocol_version: ProtocolVersion,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_event_sequence: Option<EventSequence>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct HandshakeResponse {
    pub protocol_version: ProtocolVersion,
    pub server_name: String,
    pub server_version: String,
    pub providers: Vec<Provider>,
    pub event_sequence: EventSequence,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum PermissionLevel {
    #[serde(rename = "read-only")]
    ReadOnly,
    #[serde(rename = "workspace-write")]
    WorkspaceWrite,
    #[serde(rename = "full-access")]
    FullAccess,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct Provider {
    pub id: String,
    pub provider_type: String,
    pub display_name: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    pub status: ProviderStatus,
    pub capabilities: ProviderCapabilities,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extension: Option<ProviderExtension>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderCapabilities {
    pub methods: Vec<String>,
    pub permission_levels: Vec<PermissionLevel>,
    pub models: Vec<String>,
    pub reasoning_efforts: Vec<String>,
    pub quick_replies: Vec<QuickReply>,
    pub can_steer: bool,
    pub can_interrupt: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extension: Option<ProviderExtension>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderExtension {
    pub namespace: String,
    pub data: JsonObject,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderListRequest {

}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderListResponse {
    pub providers: Vec<Provider>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProviderStatus {
    #[serde(rename = "disconnected")]
    Disconnected,
    #[serde(rename = "connecting")]
    Connecting,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "unavailable")]
    Unavailable,
    #[serde(rename = "error")]
    Error,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct ProviderStatusChangedEvent {
    pub provider: Provider,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub previous_status: Option<ProviderStatus>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct QuickReply {
    pub id: String,
    pub label: String,
    pub text: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnInterruptRequest {
    pub provider_id: String,
    pub conversation_id: String,
    pub turn_id: String,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnInterruptResponse {
    pub turn: TurnTask,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnOutputDeltaEvent {
    pub provider_id: String,
    pub conversation_id: String,
    pub turn_id: String,
    pub output_id: String,
    pub kind: String,
    pub delta: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extension: Option<ProviderExtension>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnSendRequest {
    pub provider_id: String,
    pub conversation_id: String,
    pub client_message_id: String,
    pub message: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quick_reply_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub steer_turn_id: Option<String>,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnSendResponse {
    pub turn: TurnTask,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnTask {
    pub id: String,
    pub provider_id: String,
    pub conversation_id: String,
    pub status: TurnTaskStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub display_summary: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub started_at: Option<TimestampMs>,
    pub updated_at: TimestampMs,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<TimestampMs>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extension: Option<ProviderExtension>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum TurnTaskStatus {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "waiting-approval")]
    WaitingApproval,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "interrupted")]
    Interrupted,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[serde(deny_unknown_fields)]
pub struct TurnUpsertedEvent {
    pub turn: TurnTask,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProtocolMethod {
    #[serde(rename = "protocol.handshake")]
    ProtocolHandshake,
    #[serde(rename = "provider.list")]
    ProviderList,
    #[serde(rename = "conversation.list")]
    ConversationList,
    #[serde(rename = "conversation.get")]
    ConversationGet,
    #[serde(rename = "conversation.create")]
    ConversationCreate,
    #[serde(rename = "turn.send")]
    TurnSend,
    #[serde(rename = "turn.interrupt")]
    TurnInterrupt,
    #[serde(rename = "approval.resolve")]
    ApprovalResolve,
}

impl ProtocolMethod {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ProtocolHandshake => "protocol.handshake",
            Self::ProviderList => "provider.list",
            Self::ConversationList => "conversation.list",
            Self::ConversationGet => "conversation.get",
            Self::ConversationCreate => "conversation.create",
            Self::TurnSend => "turn.send",
            Self::TurnInterrupt => "turn.interrupt",
            Self::ApprovalResolve => "approval.resolve",
        }
    }
}

impl std::str::FromStr for ProtocolMethod {
    type Err = ();

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "protocol.handshake" => Ok(Self::ProtocolHandshake),
            "provider.list" => Ok(Self::ProviderList),
            "conversation.list" => Ok(Self::ConversationList),
            "conversation.get" => Ok(Self::ConversationGet),
            "conversation.create" => Ok(Self::ConversationCreate),
            "turn.send" => Ok(Self::TurnSend),
            "turn.interrupt" => Ok(Self::TurnInterrupt),
            "approval.resolve" => Ok(Self::ApprovalResolve),
            _ => Err(()),
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProtocolEventName {
    #[serde(rename = "provider.statusChanged")]
    ProviderStatusChanged,
    #[serde(rename = "conversation.upserted")]
    ConversationUpserted,
    #[serde(rename = "turn.upserted")]
    TurnUpserted,
    #[serde(rename = "turn.outputDelta")]
    TurnOutputDelta,
    #[serde(rename = "approval.requested")]
    ApprovalRequested,
    #[serde(rename = "approval.resolved")]
    ApprovalResolved,
}

impl ProtocolEventName {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ProviderStatusChanged => "provider.statusChanged",
            Self::ConversationUpserted => "conversation.upserted",
            Self::TurnUpserted => "turn.upserted",
            Self::TurnOutputDelta => "turn.outputDelta",
            Self::ApprovalRequested => "approval.requested",
            Self::ApprovalResolved => "approval.resolved",
        }
    }
}

impl std::str::FromStr for ProtocolEventName {
    type Err = ();

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "provider.statusChanged" => Ok(Self::ProviderStatusChanged),
            "conversation.upserted" => Ok(Self::ConversationUpserted),
            "turn.upserted" => Ok(Self::TurnUpserted),
            "turn.outputDelta" => Ok(Self::TurnOutputDelta),
            "approval.requested" => Ok(Self::ApprovalRequested),
            "approval.resolved" => Ok(Self::ApprovalResolved),
            _ => Err(()),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "status", rename_all = "camelCase")]
pub enum ResponsePayload<T> {
    Ok { result: T },
    Error { error: ProtocolError },
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "method")]
pub enum ProtocolRequest {
    #[serde(rename = "protocol.handshake")]
    ProtocolHandshake {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        params: HandshakeRequest,
    },
    #[serde(rename = "provider.list")]
    ProviderList {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        params: ProviderListRequest,
    },
    #[serde(rename = "conversation.list")]
    ConversationList {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        params: ConversationListRequest,
    },
    #[serde(rename = "conversation.get")]
    ConversationGet {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        params: ConversationGetRequest,
    },
    #[serde(rename = "conversation.create")]
    ConversationCreate {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        params: ConversationCreateRequest,
    },
    #[serde(rename = "turn.send")]
    TurnSend {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        params: TurnSendRequest,
    },
    #[serde(rename = "turn.interrupt")]
    TurnInterrupt {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        params: TurnInterruptRequest,
    },
    #[serde(rename = "approval.resolve")]
    ApprovalResolve {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        params: ApprovalResolveRequest,
    },
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "method")]
pub enum ProtocolResponse {
    #[serde(rename = "protocol.handshake")]
    ProtocolHandshake {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        response: ResponsePayload<HandshakeResponse>,
    },
    #[serde(rename = "provider.list")]
    ProviderList {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        response: ResponsePayload<ProviderListResponse>,
    },
    #[serde(rename = "conversation.list")]
    ConversationList {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        response: ResponsePayload<ConversationListResponse>,
    },
    #[serde(rename = "conversation.get")]
    ConversationGet {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        response: ResponsePayload<ConversationGetResponse>,
    },
    #[serde(rename = "conversation.create")]
    ConversationCreate {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        response: ResponsePayload<ConversationCreateResponse>,
    },
    #[serde(rename = "turn.send")]
    TurnSend {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        response: ResponsePayload<TurnSendResponse>,
    },
    #[serde(rename = "turn.interrupt")]
    TurnInterrupt {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        response: ResponsePayload<TurnInterruptResponse>,
    },
    #[serde(rename = "approval.resolve")]
    ApprovalResolve {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        id: RequestId,
        response: ResponsePayload<ApprovalResolveResponse>,
    },
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "event")]
pub enum ProtocolEvent {
    #[serde(rename = "provider.statusChanged")]
    ProviderStatusChanged {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        #[serde(rename = "eventSequence")]
        event_sequence: EventSequence,
        payload: ProviderStatusChangedEvent,
    },
    #[serde(rename = "conversation.upserted")]
    ConversationUpserted {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        #[serde(rename = "eventSequence")]
        event_sequence: EventSequence,
        payload: ConversationUpsertedEvent,
    },
    #[serde(rename = "turn.upserted")]
    TurnUpserted {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        #[serde(rename = "eventSequence")]
        event_sequence: EventSequence,
        payload: TurnUpsertedEvent,
    },
    #[serde(rename = "turn.outputDelta")]
    TurnOutputDelta {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        #[serde(rename = "eventSequence")]
        event_sequence: EventSequence,
        payload: TurnOutputDeltaEvent,
    },
    #[serde(rename = "approval.requested")]
    ApprovalRequested {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        #[serde(rename = "eventSequence")]
        event_sequence: EventSequence,
        payload: ApprovalRequestedEvent,
    },
    #[serde(rename = "approval.resolved")]
    ApprovalResolved {
        #[serde(rename = "protocolVersion")]
        protocol_version: ProtocolVersion,
        #[serde(rename = "eventSequence")]
        event_sequence: EventSequence,
        payload: ApprovalResolvedEvent,
    },
}

pub type ProtocolFuture<'a, T> = Pin<Box<dyn Future<Output = Result<T, ProtocolError>> + Send + 'a>>;

pub trait ProtocolServer: Send + Sync {
    fn protocol_handshake<'a>(&'a self, _request: HandshakeRequest) -> ProtocolFuture<'a, HandshakeResponse> {
        Box::pin(async { Err(method_not_implemented("protocol.handshake")) })
    }

    fn provider_list<'a>(&'a self, _request: ProviderListRequest) -> ProtocolFuture<'a, ProviderListResponse> {
        Box::pin(async { Err(method_not_implemented("provider.list")) })
    }

    fn conversation_list<'a>(&'a self, _request: ConversationListRequest) -> ProtocolFuture<'a, ConversationListResponse> {
        Box::pin(async { Err(method_not_implemented("conversation.list")) })
    }

    fn conversation_get<'a>(&'a self, _request: ConversationGetRequest) -> ProtocolFuture<'a, ConversationGetResponse> {
        Box::pin(async { Err(method_not_implemented("conversation.get")) })
    }

    fn conversation_create<'a>(&'a self, _request: ConversationCreateRequest) -> ProtocolFuture<'a, ConversationCreateResponse> {
        Box::pin(async { Err(method_not_implemented("conversation.create")) })
    }

    fn turn_send<'a>(&'a self, _request: TurnSendRequest) -> ProtocolFuture<'a, TurnSendResponse> {
        Box::pin(async { Err(method_not_implemented("turn.send")) })
    }

    fn turn_interrupt<'a>(&'a self, _request: TurnInterruptRequest) -> ProtocolFuture<'a, TurnInterruptResponse> {
        Box::pin(async { Err(method_not_implemented("turn.interrupt")) })
    }

    fn approval_resolve<'a>(&'a self, _request: ApprovalResolveRequest) -> ProtocolFuture<'a, ApprovalResolveResponse> {
        Box::pin(async { Err(method_not_implemented("approval.resolve")) })
    }
}

fn method_not_implemented(method: &str) -> ProtocolError {
    ProtocolError {
        code: "method_not_implemented".to_string(),
        message: format!("protocol method is not implemented: {method}"),
        retryable: false,
        details: None,
    }
}

pub async fn dispatch<S: ProtocolServer + ?Sized>(server: &S, request: ProtocolRequest) -> ProtocolResponse {
    match request {
        ProtocolRequest::ProtocolHandshake { protocol_version, id, params } => {
            let response = match server.protocol_handshake(params).await {
                Ok(result) => ResponsePayload::Ok { result },
                Err(error) => ResponsePayload::Error { error },
            };
            ProtocolResponse::ProtocolHandshake { protocol_version, id, response }
        },
        ProtocolRequest::ProviderList { protocol_version, id, params } => {
            let response = match server.provider_list(params).await {
                Ok(result) => ResponsePayload::Ok { result },
                Err(error) => ResponsePayload::Error { error },
            };
            ProtocolResponse::ProviderList { protocol_version, id, response }
        },
        ProtocolRequest::ConversationList { protocol_version, id, params } => {
            let response = match server.conversation_list(params).await {
                Ok(result) => ResponsePayload::Ok { result },
                Err(error) => ResponsePayload::Error { error },
            };
            ProtocolResponse::ConversationList { protocol_version, id, response }
        },
        ProtocolRequest::ConversationGet { protocol_version, id, params } => {
            let response = match server.conversation_get(params).await {
                Ok(result) => ResponsePayload::Ok { result },
                Err(error) => ResponsePayload::Error { error },
            };
            ProtocolResponse::ConversationGet { protocol_version, id, response }
        },
        ProtocolRequest::ConversationCreate { protocol_version, id, params } => {
            let response = match server.conversation_create(params).await {
                Ok(result) => ResponsePayload::Ok { result },
                Err(error) => ResponsePayload::Error { error },
            };
            ProtocolResponse::ConversationCreate { protocol_version, id, response }
        },
        ProtocolRequest::TurnSend { protocol_version, id, params } => {
            let response = match server.turn_send(params).await {
                Ok(result) => ResponsePayload::Ok { result },
                Err(error) => ResponsePayload::Error { error },
            };
            ProtocolResponse::TurnSend { protocol_version, id, response }
        },
        ProtocolRequest::TurnInterrupt { protocol_version, id, params } => {
            let response = match server.turn_interrupt(params).await {
                Ok(result) => ResponsePayload::Ok { result },
                Err(error) => ResponsePayload::Error { error },
            };
            ProtocolResponse::TurnInterrupt { protocol_version, id, response }
        },
        ProtocolRequest::ApprovalResolve { protocol_version, id, params } => {
            let response = match server.approval_resolve(params).await {
                Ok(result) => ResponsePayload::Ok { result },
                Err(error) => ResponsePayload::Error { error },
            };
            ProtocolResponse::ApprovalResolve { protocol_version, id, response }
        }
    }
}

pub struct ProtocolDispatcher<S> {
    server: S,
}

impl<S> ProtocolDispatcher<S> {
    pub const fn new(server: S) -> Self {
        Self { server }
    }

    pub const fn server(&self) -> &S {
        &self.server
    }
}

impl<S: ProtocolServer> ProtocolDispatcher<S> {
    pub async fn dispatch(&self, request: ProtocolRequest) -> ProtocolResponse {
        dispatch(&self.server, request).await
    }
}

pub type ProtocolTransportFuture<'a> = Pin<Box<dyn Future<Output = Result<serde_json::Value, ProtocolError>> + Send + 'a>>;

pub trait ProtocolTransport: Send + Sync {
    fn request<'a>(&'a self, method: ProtocolMethod, params: serde_json::Value) -> ProtocolTransportFuture<'a>;
}

pub struct ProtocolClient<T> {
    transport: T,
}

impl<T> ProtocolClient<T> {
    pub const fn new(transport: T) -> Self {
        Self { transport }
    }

    pub const fn transport(&self) -> &T {
        &self.transport
    }
}

impl<T: ProtocolTransport> ProtocolClient<T> {
    pub fn protocol_handshake<'a>(&'a self, request: HandshakeRequest) -> ProtocolFuture<'a, HandshakeResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ProtocolHandshake, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn provider_list<'a>(&'a self, request: ProviderListRequest) -> ProtocolFuture<'a, ProviderListResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ProviderList, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn conversation_list<'a>(&'a self, request: ConversationListRequest) -> ProtocolFuture<'a, ConversationListResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ConversationList, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn conversation_get<'a>(&'a self, request: ConversationGetRequest) -> ProtocolFuture<'a, ConversationGetResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ConversationGet, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn conversation_create<'a>(&'a self, request: ConversationCreateRequest) -> ProtocolFuture<'a, ConversationCreateResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ConversationCreate, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn turn_send<'a>(&'a self, request: TurnSendRequest) -> ProtocolFuture<'a, TurnSendResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::TurnSend, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn turn_interrupt<'a>(&'a self, request: TurnInterruptRequest) -> ProtocolFuture<'a, TurnInterruptResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::TurnInterrupt, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }

    pub fn approval_resolve<'a>(&'a self, request: ApprovalResolveRequest) -> ProtocolFuture<'a, ApprovalResolveResponse> {
        Box::pin(async move {
            let params = serde_json::to_value(request).map_err(|error| codec_error("encode request params", error))?;
            let result = self.transport.request(ProtocolMethod::ApprovalResolve, params).await?;
            serde_json::from_value(result).map_err(|error| codec_error("decode response result", error))
        })
    }
}

pub fn encode_request(value: &ProtocolRequest) -> Result<Vec<u8>, ProtocolError> {
    serde_json::to_vec(value).map_err(|error| codec_error("encode request", error))
}

pub fn decode_request(value: &[u8]) -> Result<ProtocolRequest, ProtocolError> {
    serde_json::from_slice(value).map_err(|error| codec_error("decode request", error))
}

pub fn encode_response(value: &ProtocolResponse) -> Result<Vec<u8>, ProtocolError> {
    serde_json::to_vec(value).map_err(|error| codec_error("encode response", error))
}

pub fn decode_response(value: &[u8]) -> Result<ProtocolResponse, ProtocolError> {
    serde_json::from_slice(value).map_err(|error| codec_error("decode response", error))
}

pub fn encode_event(value: &ProtocolEvent) -> Result<Vec<u8>, ProtocolError> {
    serde_json::to_vec(value).map_err(|error| codec_error("encode event", error))
}

pub fn decode_event(value: &[u8]) -> Result<ProtocolEvent, ProtocolError> {
    serde_json::from_slice(value).map_err(|error| codec_error("decode event", error))
}

fn codec_error(context: &str, error: serde_json::Error) -> ProtocolError {
    ProtocolError {
        code: "protocol_codec_error".to_string(),
        message: format!("{context}: {error}"),
        retryable: false,
        details: None,
    }
}
